### ISSUE TITLE
UnsupportedClassVersionError

### ISSUE THREAD

**Issue by zhoube** [nus-cs2103-AY2021S2/forum#10]
While doing A-TextUiTesting, I come across this error 

Kelbot has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I am using IntelliJ Version 2020.3, Java Version 11 (at least I believe so as for some reason when I do java -version on my IntelliJ terminal it insists on being Java 8 despite me choosing the runtime to be 11 using the Choose Runtime plugin, adding Java 11 to my PATH environment and also ensuring that the Project Settings have it at Java 11)

Due to this, the ACTUAL.txt is forever empty and thus cannot be compared with EXPECTED.txt

Also, I am also unable to see my tags at https://github.com/zoeykobe/ip/tags, even though in my git bash if I do git tag it will show me all the tags

**Comment by w2vgd** [comment]
You can double check if the JDK location is correct (without any other subfolders behind the jdk-11.0.6). You may also try rebooting your IntelliJ/computer after ensuring the JDK location is correct.
![image](https://user-images.githubusercontent.com/65358857/104838671-7ea76c80-58f7-11eb-976a-7a2622eb22bb.png)


> Also, I am also unable to see my tags at https://github.com/zoeykobe/ip/tags, even though in my git bash if I do git tag it will show me all the tags

Did you manually push the tags to your remote repository? Tags are not pushed to the remote repository by default. You can try running the command `git push origin --tags` to push all your tags to the remote repository.

**Comment by zhoube** [comment]
Hello, thank you for your help!

I have checked that the JDK location is correct, it is the exact same location as the one shown in your photo.

As for the tags, is it normal that everytime i run git push, they ask for my username and password, and I have to key it in twice because of `Logon failed, use ctrl+c to cancel basic credential prompt.`?

**Comment by JonahhGohh** [comment]
Hi, can you try typing `where java` in your terminal. It shows the location of your current java installations in your computer. If you see more than 1 location, it might be that you are using one of your older version (java 8) to run your runtest.bat file.

**Comment by zhoube** [comment]
Hello! I do have more than 1 Java Version installed, Java 11.0.6, 11.0.5 and 8!

**Comment by w2vgd** [comment]
> Hello! I do have more than 1 Java Version installed, Java 11.0.6, 11.0.5 and 8!

In this case, I think you should remove the other 2 from your PATH under environment variables and try again.


> As for the tags, is it normal that everytime i run git push, they ask for my username and password, and I have to key it in twice because of `Logon failed, use ctrl+c to cancel basic credential prompt.`?

Sometimes, the issue may be caused by outdated version of git bash. Try to update your git with `git update-git-for-windows` if you are using Windows or just `git update` if you are using mac. 
You may want to refer to this thread for more information (https://stackoverflow.com/questions/55768926/logon-failed-use-ctrlc-to-cancel-basic-credential-prompt-to-git-in-azure-devop).

**Comment by zhoube** [comment]
Hmmm there is only one Java Path in my Environment Variable though!

Ill try out the update part! Thank you!

**Comment by tjtanjin** [comment]
Hello! Just to add on to what @w2vgd said above, the reason for the version incompatibility is due to [github deprecating their password authentication](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/). For anyone facing a similar issue on SourceTree, [this thread](https://stackoverflow.com/questions/63615535/sourcetree-error-logon-failed-use-ctrlc-to-cancel-basic-credential-prompt) also contains relevant information. Hope you get your issue sorted out!

**Comment by JonahhGohh** [comment]
I believe that your current Java path in your environment variable is pointing to Java 8. Can you replace that path with your java 11 path (you can use the directory given in the `where java` command) and try to run your runtest.bat file again?

**Comment by damithc** [comment]
@zoeykobe In future, try to limit each issue to one problem only. Trying to solve multiple unrelated issues in a single issue thread can cause confusion.

**Comment by zhoube** [comment]
> I believe that your current Java path in your environment variable is pointing to Java 8. Can you replace that path with your java 11 path (you can use the directory given in the `where java` command) and try to run your runtest.bat file again?

I have done the `where java` and changed the PATH environment variable, it still has the same issue :(

Could it be that the file for Java exists, but not the installation?

**Comment by tjtanjin** [comment]
Hey @zoeykobe! See if the accepted answer (and its comments) in [this thread](https://stackoverflow.com/questions/57366359/troubleshooting-unsupportedclassversionerror-in-intellij-idea) helps. It seems to describe an issue very similar to yours! :)

**Comment by zhoube** [comment]
> Hey @zoeykobe! See if the accepted answer (and its comments) in [this thread](https://stackoverflow.com/questions/57366359/troubleshooting-unsupportedclassversionerror-in-intellij-idea) helps. It seems to describe an issue very similar to yours! :)

I have seen that already!! Seems to be a different issue than mine. I decided to uninstall all my Java and reinstall only Java 11, it works now! Thank you everyone!

> @zoeykobe In future, try to limit each issue to one problem only. Trying to solve multiple unrelated issues in a single issue thread can cause confusion.

I see, sorry for the confusion Prof!

**Comment by damithc** [comment]
> I have seen that already!! Seems to be a different issue than mine. I decided to uninstall all my Java and reinstall only Java 11, it works now! Thank you everyone!

Glad to hear that. Java 8 is especially sticky and often the easy solution is to uninstall it.

**Comment by Diwu-Yi** [comment]
Hi @zoeykobe just a gentle reminder if the issue is resolved and all doubts are clarified, it is a good time to **close** this issue now to keep the forum focused and updated :) .
