### ISSUE TITLE
Messages are getting "shortened" Level-10 

### ISSUE THREAD

**Issue by colintkn** [nus-cs2103-AY2021S2/forum#101]
It seems that my messages are not rendering properly as I type more and more commands. 

I start by typing "list" and the output is fine.  
![image](https://user-images.githubusercontent.com/65516485/106599592-40b37500-6594-11eb-9d55-8455b14cf20f.png)

I type "list" the second time and the previous and current output is shortened.  

![image](https://user-images.githubusercontent.com/65516485/106599616-4610bf80-6594-11eb-960a-ff25c400a004.png)

I type "list" the third time and current and prior messages are further shortened.  
![image](https://user-images.githubusercontent.com/65516485/106599636-4c9f3700-6594-11eb-8580-580db367dce2.png)

I am using the view fxml given in the javaFx tutorial. Is this something to do with the scrolling?

**Comment by tjtanjin** [comment]
Assuming you are using scenebuilder, you may want to go to `label` within `DialogBox.fxml` file. In the right panel, go under `layout` and check if it has min, max and pref width/height set to something like this (by default it should all be computed):
<img width="262" alt="Screenshot 2021-02-02 at 8 32 40 PM" src="https://user-images.githubusercontent.com/43908963/106600889-f59a6180-6595-11eb-8a70-0499d453df73.png">

**Comment by colintkn** [comment]
Thank you
