### ISSUE TITLE
Unable to find XML from given xmlns in MainWindow.fxml

### ISSUE THREAD

**Issue by Juzzanoob** [nus-cs2103-AY2021S2/forum#102]
I have followed the steps given in the JavaFX Tutorial. However, at the final step when implementing FXML, I encountered an error in my MainWindow.fxml file whereby IntelliJ is unable to find an XML from the given xmlns.

A snapshot of the MainWindow.fxml file is given below:
![image](https://user-images.githubusercontent.com/18525019/106617961-048b0f00-65aa-11eb-8f92-48396f096d44.png)

As a result, when I try to run the main() method from my Launcher class, I get a NullPointerException. Does anyone know how to fix this issue?

**Comment by tjtanjin** [comment]
Your `fx:controller:` needs to include the full package name e.g. `fx:controller:"duke.MainWindow"` :)

Edit: It seems you are not using packages hold on :3 If you click around on the errors at the bottom left side of your panel, does it not show a full stacktrace of the exception?

**Comment by Juzzanoob** [comment]
Yup I haven't implemented packages yet, do I need to do that for this to work?

As for the stacktrace of the exception, I've made a snapshot of it but I think it just points back to those two red lines:
![image](https://user-images.githubusercontent.com/18525019/106631565-d7455d80-65b7-11eb-9e56-f0feed23a8a1.png)
![image](https://user-images.githubusercontent.com/18525019/106631616-e1675c00-65b7-11eb-89af-c62815be2d04.png)

**Comment by tjtanjin** [comment]
> Yup I haven't implemented packages yet, do I need to do that for this to work?

Nope you don't need packages for this to work!

Could you share where you are storing your images and how you are referring to them?

**Comment by onnwards** [comment]
I've encountered this same issue just now. I think it is likely that you need to add the resources folder to your project classpath/source path.

**Comment by Juzzanoob** [comment]
I am currently storing my images in the folder here:
![image](https://user-images.githubusercontent.com/18525019/106633409-c5fd5080-65b9-11eb-870c-802e93fbc61d.png)

As for the project classpath/source path, I tried marking my resources folder as "Source Root" but it still didn't work.

**Comment by tjtanjin** [comment]
It might help to share your `Main` and `MainWindow` files since the error seems to involve line 22 of `Main.java` and line 23 of `MainWindow.java`.

Edit: Might also want to check the image file name in your code since the images you are using have different names from the code provided in the tutorial :D

**Comment by onnwards** [comment]
A workaround (while you are waiting for a reply/figuring out the solution) can be:
instead of using
`private Image user = new Image(this.getClass().getResourceAsStream("/images/DaUser.png"));`
you can use
`private Image user = new Image("file:./pathToFileFromRootDirectory/DaUser.png")`
you may need to handle cross platform `/` or `\` though if you do this.

**Comment by Juzzanoob** [comment]
Thanks everyone for your suggestions so far.

I've attached snapshots of my `Main` and `MainWindow` files. As for @onnwards' suggestion, I tried implementing the direct path but the two lines remain red.

`MainWindow`
![image](https://user-images.githubusercontent.com/18525019/106638041-605f9300-65be-11eb-9875-5abf109506f2.png)
![image](https://user-images.githubusercontent.com/18525019/106638073-69506480-65be-11eb-8b43-7ab8ef88667e.png)

`Main`
![image](https://user-images.githubusercontent.com/18525019/106638101-740af980-65be-11eb-9aa9-703180dbc351.png)

**Comment by tjtanjin** [comment]
This might be worth a try. Try changing the image paths in `MainWindow.java` to this:
```
new Image(this.getClass().getResourceAsStream("/images/User.png"));`
new Image(this.getClass().getResourceAsStream("/images/Duke.png"));
```
And in `Main.java` file:
```
new FXMLLoader(Main.class.getResource("/view/MainWindow.fxml"));
```

**Comment by Juzzanoob** [comment]
I restarted the entire JavaFX process and it managed to work, so I'm guessing something went wrong somewhere in between but I'm still unable to figure out exactly what. Anyway, thanks everyone so much for your suggestions!
