### ISSUE TITLE
Cannot resolve symbol 'DukeException'

### ISSUE THREAD

**Issue by figo2127** [nus-cs2103-AY2021S2/forum#103]
Hello friends! I have a problem :(

After implementing the checkstyle, there seems to be an import error for DukeException in my Duke.java, while import for all the other files works just fine. I can't do * because the checkstyle.xml issues an error for that. I checkstyled my DukeException.java and there's no error whatsoever. Any of ya knows what's the problem? Huge thanks!

**Duke.java:**
![image](https://user-images.githubusercontent.com/61351392/106630682-060f0400-65b7-11eb-8236-f54f2cc219f5.png)

**DukeException.java**
![image](https://user-images.githubusercontent.com/61351392/106631287-92b9c200-65b7-11eb-8d57-4e110ad33ef7.png)

**Comment by damithc** [comment]
Just in case, can try `File` > `Invalidate cache /restart` feature in intellij

**Comment by figo2127** [comment]
Thank you! it worked
