### ISSUE TITLE
Updating checkstyle to match module coding standard

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#105]
Hello, 

does anyone know how to update the checkstyle file to match the coding standard for specifically the rule on making all final variables (including member variables) use SCREAMING_SNAKE case?

There are two errors for the current version of checkstyle
1. AbbreviationAsWordInName

I figured we could disable this by updating line **88** in this way:
Before:
`<property name="ignoreFinal" value="false"/>` 

After:
`<property name="ignoreFinal" value="true"/>`

2. MemberName

Have not figured out how to do this yet. Does anyone know how we can overcome this warning?

**Comment by onnwards** [comment]
From what I see from reading the [Checkstyle documentation](https://checkstyle.sourceforge.io/config_naming.html), it doesn't look like its very possible unless you write? your own module for checkstyle. I don't think there's a module in checkstyle that applies specifically only to final variables.

I suppose you could include a Regexp module to check for final variables, but it does seem quite overkill. Also, not sure how overlapping modules work.

**Comment by onnwards** [comment]
Anyway, I believe this is a case of where a discrepancy exists between coding standards and the given `checkstyle.xml`, since as you pointed out, you will violate both `AbbreviationAsWordInName` and `MemberName` if you rename the final (nonstatic) variable to SCREAMING_SNAKE_CASE. From what prof mentioned in [the issue you raised previously on final variables](https://github.com/nus-cs2103-AY2021S2/forum/issues/98#issuecomment-771352035), I believe we will not be faulted if we do not use SCREAMING_SNAKE_CASE for final (nonstatic) variables.

@damithc for clarification

**Comment by damithc** [comment]
> Anyway, I believe this is a case of where a discrepancy exists between coding standards and the given `checkstyle.xml`, since as you pointed out, you will violate both `AbbreviationAsWordInName` and `MemberName` if you rename the final (nonstatic) variable to SCREAMING_SNAKE_CASE. From what prof mentioned in [the issue you raised previously on final variables](https://github.com/nus-cs2103-AY2021S2/forum/issues/98#issuecomment-771352035), I believe we will not be faulted if we do not use SCREAMING_SNAKE_CASE for final (nonstatic) variables.
> 
> @damithc for clarification

Yes, it should be fine not to use SCREAMING_SNAKE for non-static final variables if it is not allowed by the given checkstyle file.

**Comment by figo2127** [comment]
@w2vgd I managed to get rid of the warnings by digging the checkstyle.xml and comment out the code block for MemberName (line 120). But I'm not sure if that's allowed.

@damithc Are we allowed to comment out that part?

**Comment by damithc** [comment]
> @damithc Are we allowed to comment out that part?

@figo2127 You are allowed to change checkstyle config files any way you wish :-) It's fine as long as the code your produce follows the given coding standard.

**Comment by w2vgd** [comment]
> @w2vgd I managed to get rid of the warnings by digging the checkstyle.xml and comment out the code block for MemberName (line 120). But I'm not sure if that's allowed.

Hi @figo2127, just my personal opinion but I would think its best not to comment out that part since it serves to check if all of your member variables are named correctly (those that are non-final too). Although the check is kind of simple as I seen from the regex, i.e. only making sure that the variable name starts with a lowercase and that the name only consist of letters and digits, I think that it may still be useful as a final safety check (given that we have quite a number of files to check, and even more so for tP later on). 

As such, I have reverted to using camelCase for static non-final member variables to comply with the checkstyle rules (because I can't stand the warnings generated by checkstyle 😅).

**Comment by yhtMinceraft1010X** [comment]
I found a javadoc checkstyle module for the one line before tags check: [RequireEmptyLineBeforeBlockTagGroupCheck](https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/checks/javadoc/RequireEmptyLineBeforeBlockTagGroupCheck.html)

Tried setting it up in checkstyle but I got this error: 
```
Unable to instantiate 'RequireEmptyLineBeforeBlockTagGroup' class, it is also not possible to instantiate it as .RequireEmptyLineBeforeBlockTagGroup, RequireEmptyLineBeforeBlockTagGroupCheck, .RequireEmptyLineBeforeBlockTagGroupCheck. 
Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. 
Please also recheck that provided ClassLoader to Checker is configured correctly.
```

Anyone managed to set this up?

**Comment by kouyk** [comment]
The following is extracted from the link you have provided.
> Since:
> 8.36

Doing a quick check on build.gradle shows that the version of checkstyle we are using is 8.29, so that should explain the error you have encountered :)

**Comment by yhtMinceraft1010X** [comment]
Thanks, but I'm not sure if for this mod, it's okay to change the checkstyle version to 8.36

**Comment by damithc** [comment]
> Thanks, but I'm not sure if for this mod, it's okay to change the checkstyle version to 8.36

You may use a different version but you'll need to adjust the config files yourself to match the selected version (as there may be syntax differences between different versions)
