### ISSUE TITLE
Gradle run could not find or load main class

### ISSUE THREAD

**Issue by Cp-John** [nus-cs2103-AY2021S2/forum#106]
Hi, anyone knows how to resolve this issue? Thanks in advance!
After I merged the add-gradle-support branch, I encountered this error when running by clicking on run under application in the gradle panel.
<img width="521" alt="Screenshot 2021-02-03 at 8 10 08 PM" src="https://user-images.githubusercontent.com/60333492/106745520-2a70ec00-665c-11eb-878a-53847a29c811.png">

Here is my file structure:
<img width="355" alt="Screenshot 2021-02-03 at 8 10 32 PM" src="https://user-images.githubusercontent.com/60333492/106745433-0e6d4a80-665c-11eb-8f1b-22bd4e7d12f6.png">

**Comment by damithc** [comment]
Do you have a class named `seedu.duke.Duke`? If not, find where that class name is specified and update it to match your main class?

**Comment by candyhy** [comment]
Hello, I believe you have to update your main class name in build.gradle!
(Application clause)

**Comment by Eriksen2411** [comment]
Sorry, can i ask that this class name is like Duke only or it should come with its path. Cause i try with Duke only and cannot

**Comment by tjtanjin** [comment]
You will need to include the package so for example: `duke.Duke` :)

**Comment by georgepwhuang** [comment]
Remember to change the class name when you do the switch from Text UI to GUI, considering that the main class should be different.

**Comment by jlxw48** [comment]
I had the same issue too! For me, changing it to the location of the Launcher class in the package worked.

**Comment by litone01** [comment]
Updating the main class name in build.gradle works for me! Remember to include your package name as @tjtanjin mentioned if needed:)

**Comment by Cp-John** [comment]
Thank you, guys! I have resolved the issue by updating the main class name in the build.gradle file.
