### ISSUE TITLE
Cannot add configuration file for CheckStyle

### ISSUE THREAD

**Issue by Eriksen2411** [nus-cs2103-AY2021S2/forum#108]
Hi everyone,
I'm having some problems with adding configuration gile for Checkstyle. I downloaded the source code of AB3 and then copy the config folder to my IP repo. After that i started adding configuration file to Checkstyle as instructed. 
![image](https://user-images.githubusercontent.com/65208242/106766914-4e8cf700-6675-11eb-9e06-3688a23e06cc.png)
But then an error appeared:
![image](https://user-images.githubusercontent.com/65208242/106767035-6ebcb600-6675-11eb-9f5a-3afa8b9c2e7a.png)
I'm not sure if I'm doing wrong at any steps and find no clue about this error also.
Please send some help.
Thank you.

**Comment by tjtanjin** [comment]
You might want to double check if you have both `checkstyle.xml` and `suppressions.xml` within `./config/checkstyle/`. The `build.gradle` would also need to be updated in case you missed it. Hopefully [this](https://github.com/nus-cs2103-AY2021S2/forum/issues/93) also helps :3

**Comment by Eriksen2411** [comment]
yes i have both 2 files in config/checkstyle. And also, I do not think that this is related to Gradle cause I'm just adding the configuration file for CheckStyle. Am I right?

**Comment by tjtanjin** [comment]
You need to update `build.gradle` file as well :D It's one of the steps outlined [here](https://github.com/nus-cs2103-AY2021S2/forum/issues/93) see if that solves the issue :D

**Comment by Eriksen2411** [comment]
i figure it now with the same solution from this issue:
https://github.com/nus-cs2103-AY2021S2/forum/issues/92
What is problem of the checkstyle.xml, why changing its content makes it work?

**Comment by tjtanjin** [comment]
If you took the checkstyle file from AB3 directly then to be very honest I am not sure as well since the file contents I had were also from AB3 😅. Perhaps it has to do with the way it was retrieved (I copied the raw contents of the file, didn't actually download it).

**Comment by georgepwhuang** [comment]
Some checkstyle files have syntax errors or version incompatibility, not sure which. But most of them are issues with `TreeWalker`. Edit the xml file and move the modules in the warnings out of `TreeWalker` one by one.

Like for this screenshot, you'll want to move the entire `FileContentsHolder` module out of `TreeWalker`.

Just move them warning by warning. I don't think there are that many of them.
