### ISSUE TITLE
Is there a need to use Fxml?

### ISSUE THREAD

**Issue by candyhy** [nus-cs2103-AY2021S2/forum#111]
I have implemented my GUI entirely in code, factorising my code into MainWindow, DialogBox, to prevent overloading of my Main class. May I check if it is necessary to use Fxml, as seen from the tutorial guide provided?
Please advise, thank you!

**Comment by damithc** [comment]
@candyhy Not compulsory, but given the objective of the iP is to prepare you for the tP (which uses fxml), you may want to try using fxml anyway.

**Comment by candyhy** [comment]
Okay thanks prof! will play around with FXML, just wondering if its ok to stick with code if I find it to be more readable in the end 👍
