### ISSUE TITLE
How to add JUnit dependencies to build.gradle?

### ISSUE THREAD

**Issue by CSmortal** [nus-cs2103-AY2021S2/forum#112]
I was following the Scenario 2 of "Adding Gradle to the project" in the Gradle tutorial. Because one of my test classes uses `@ParameterizedTest`, it now doesn't work after the gradle stuff was added to the project, and I figured that it was because the dependencies section in build.gradle didn't "import" the relevant junit class (package? Idk what to call it). How do I import it?

**Comment by tjtanjin** [comment]
Does this [guide](https://www.baeldung.com/parameterized-tests-junit-5) help you?

**Comment by Jh123x** [comment]
Hi @CSmortal , I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems)

The guide from @tjtanjin is really good.
This is another guide that might help
[JUnit5 Docs](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle)

**Comment by CSmortal** [comment]
@tjtanjin I tried adding `testCompile("org.junit.jupiter:junit-jupiter-params:5.7.0")` to the dependencies section of the build.gradle. Not sure what I had to do next so I went to the relevant java file and tried to see if the tag `@ParameterizedTest` is recognised, still doesnt work. So what i did next was to click the "run" button next to the dependencies section cuz i thought some downloading or something was required. Still didnt work after that.

![image](https://user-images.githubusercontent.com/67994626/107111648-b1a4a680-688c-11eb-8c51-6c2dce692119.png)

**Comment by tjtanjin** [comment]
I am not using `@ParameterizedTest` myself so I am not too familiar but for a start you might want to standardise the JUnit versions specified in your dependencies first (perhaps to 5.5.0). After which try reloading/reopening your project and see if `@ParameterizedTest` would be recognised :)

**Comment by richardcom** [comment]
Hi @CSmortal , I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems).

After you added `junit-jupiter-params` to gradle, have you imported the package as well, e.g.`import org.junit.jupiter.params.ParameterizedTest`. Re-build project and `@ParameterizedTest` annotation should be available. If not, then restart IntelliJ and libraries should be loaded.

If not, see if [this](https://stackoverflow.com/a/64283439/12754287) or [this](https://stackoverflow.com/questions/46290916/missing-org-junit-jupiter-params-from-junit5) helps.

**Comment by CSmortal** [comment]
@tjtanjin Thanks, reloading project solves the issue.
@richardcom Rebuilding also worked too, thanks! I also wanna ask if i wanna add more dependencies but the code is still not yet fixed/ready for building, is there a better way than having to reload(restart) the project every time i add a single dependency?

**Comment by richardcom** [comment]
Hi @CSmortal , great to hear that your problem is resolved. Personally, I think that the building process is essential when you try to run the code after modification. Just like when we write simple programs and make modifications, we always need to recompile the original code in order to run the program.
