### ISSUE TITLE
Duke A-Enums: Use Enums (if-applicable)

### ISSUE THREAD

**Issue by figo2127** [nus-cs2103-AY2021S2/forum#12]
Hello friends. I'm sorry if this has been mentioned. But will we be penalized if we happen to skip this part if I don't see the need to use Enums?
![image](https://user-images.githubusercontent.com/61351392/104852064-8127b780-5933-11eb-8195-3516fa68f15a.png)

**Comment by damithc** [comment]
There is no penalty if you skip optional or if-applicable increments.

**Comment by figo2127** [comment]
Alright thank you :)

**Comment by damithc** [comment]
@figo2127 you may want to subscribe to the thread #14 though.
