### ISSUE TITLE
Requesting for help to check if my Git tree is incorrect

### ISSUE THREAD

**Issue by ZhangAnli** [nus-cs2103-AY2021S2/forum#120]
Hello, 

So I followed the instructions of this week's IP closely and I am pretty sure I did not make any mistakes. 

However, after I was done with branch-A-Assertions and branch-A-CodeQuality, my Git tree looks quite messed up. 

Basically, it seems that branch-A-Assertions is branching out of my branch-A-CodeQuality which is not even possible because I did it stepwise. 

Can someone tell me if I messed up?

<img width="708" alt="Screenshot 2021-02-09 at 6 19 14 PM" src="https://user-images.githubusercontent.com/65236091/107349558-529c9700-6b03-11eb-9a2b-92eec23ba725.png">

**Comment by rajobasu** [comment]
I assume you were checked out at A-CodeQuality when you did a new branch? That is the only way this happens. However this makes me confused as to what the yellow line is. 
Below is how my structure looks like  for reference.

<img width="425" alt="Screenshot 2021-02-09 at 6 48 17 PM" src="https://user-images.githubusercontent.com/34958324/107353114-a27d5d00-6b07-11eb-84a3-7b063eb8ed70.png">


By the way one thing, which bracnh is checked out currently? master right?

**Comment by ZhangAnli** [comment]
But that is unlikely because I did branch-A-CodeQuality last. I'm quite certain I did branch-A-Assertions > checkout to master > branch-A-CodeQuality. 

Yes, I'm on branch master currently.

**Comment by tjtanjin** [comment]
Not sure if this will be helpful but if you are able to pull up command logs within sourcetree, looking at the commands executed might yield some details (the equivalent of `history` on the command line)

Edit: Just theorising here. Based on pure observation alone, in the line `Fix coding violations pointed out by peers`, there was a 3-branch split into assertions (green), codequality (red) and what appears to be a pseudo master (yellow). Perhaps github/sourcetree have some underlying implementations for pull requests resulting in this yellow branch but I am just making wild guesses at this point. Moving on, my guess of the flow is that assertions (green) branch was first completed and merged into your actual master (blue). A merge was then performed automatically to the pseudo master (yellow) to keep the branch updated. The codequality (red) branch then merges the new commits from the pseudo master (yellow) before merging itself to the actual master (blue).

**Comment by damithc** [comment]
@ZhangAnli it's good that you noticed this and trying to figure out what happened. In future, you can monitor more carefully to see if the tree evolves as you expect. But as far as iP grading is concerned, this will not cause any loss of marks to you. So, no need to worry about that.

**Comment by ZhangAnli** [comment]
Thank you all for the help!
