### ISSUE TITLE
Problems in setting up checkstyle

### ISSUE THREAD

**Issue by CSmortal** [nus-cs2103-AY2021S2/forum#124]
I'm following the guide step by step on how to set it up, but when i come to the part where it says 
![image](https://user-images.githubusercontent.com/67994626/107539457-f2d7e600-6bff-11eb-8f46-21515b8f8455.png)
I realise theres no checkstyle.xml file in my project. I installed the plugin, restarted intellij, don't understand what's going wrong.

Nothing is going well for me in this mod haha

**Comment by jasaaanlim** [comment]
You can find the file here: https://github.com/se-edu/addressbook-level3/tree/master/config/checkstyle

Don't give up!

**Comment by tjtanjin** [comment]
If you still face issues see if any of the steps [here](https://github.com/nus-cs2103-AY2021S2/forum/issues/93) help you as well! :D

**Comment by CSmortal** [comment]
@jasaaanlim thanks, I was under the impression that it automatically comes with installing all the stuff mentioned in the tutorial. I thought manually creating the checkstyle file from copying and pasting from github was the "primitive"/unrecommended way, guess I was wrong

**Comment by damithc** [comment]
> I was under the impression that it automatically comes with installing all the stuff mentioned in the tutorial. I thought manually creating the checkstyle file from copying and pasting from github was the "primitive"/unrecommended way, guess I was wrong

checkstyle is the tool for checking against a set of rules - the rules themselves are independent from the tool. A project might have both set up already (e.g., AB3) but when adding checkstyle to a project for the first time, you have to add a rules file (of your choice) yourself. Often, this is done by copying from another project and modifying further to fit your own needs.
