### ISSUE TITLE
Debug the programme when running with the gradle

### ISSUE THREAD

**Issue by QY-H00** [nus-cs2103-AY2021S2/forum#129]
Hi friends! I have a question about debugging with gradle. When I try to use printf() method to debug, it shows nothing in the console and it's hard to get used to it. Could you tell me how to fix it?

**Comment by damithc** [comment]
Somewhat related: An alternative to using print statements for debugging https://nus-cs2103-ay2021s2.github.io/website/schedule/week6/topics.html#w6-3-ides-intermediate-features

**Comment by QY-H00** [comment]
@damithc Thank you Prof!

**Comment by damithc** [comment]
BTW, you should be able to print to the console even when using Gradle.
