### ISSUE TITLE
Clarification on fixing previous levels/tags

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#13]
Hello,

I would like to clarify if we are required to revisit old tags and fix issues that we might have overlooked. In particular, running runtest.sh for `A-TextUiTesting` threw the following error for me despite passing the test:

<img width="531" alt="Screenshot 2021-01-18 at 2 43 47 AM" src="https://user-images.githubusercontent.com/43908963/104852634-17a9a800-5937-11eb-9f54-ef682a67c22b.png">

The error is thrown because I had used a while true loop instead of checking for nextLine in the scanner to take inputs thus far. As I am unaware of how the automated grading scripts work for the previous levels (or rather what they look out for), I am concerned that the previous levels might be affected by the while true loop implementation when ran against the scripts. At the same time, I have also realised that it is impossible to commit to those previous tags which means updating them individually would be quite a hassle.

I would really appreciate advice on this, thank you!

**Comment by damithc** [comment]
There is no need to modify all tags @tjtanjin 
The tags are just a way for you to indicate progress. We don't evaluate your code at every tag.  The evaluation happens only at the end of the iP.
Fix bugs as you find them and improve past increments when you can.

**Comment by tjtanjin** [comment]
Thank you for the clarification!

**Comment by colintkn** [comment]
@tjtanjin I'm getting the same error you got before. How did you solve the NoSuchElementException? This is my way of getting input. I have a Scanner called 'in' as a variable of this class. 

```
   public static String readCommand() {
        String command = "";
        while(command.trim().isEmpty()) {
            command = in.nextLine();
        }
        return command;
    }
```

Could you clarify what you mean by :

> "I had used a while true loop instead of checking for nextLine in the scanner to take inputs thus far."

**Comment by lirc572** [comment]
@colintkn  I think perhaps the NoSuchElementException is thrown when EOF of the input file is reached. If this is the case, you can include a `bye` command at the end of the input file so the program will exit before reaching EOF.

**Comment by tjtanjin** [comment]
@colintkn To add on, you may also consider using the scanner method `hasNextLine()` in your loop condition. In that way, regardless of the input, your loop will only continue if it detects that there are subsequent inputs, thereby eliminating the `NoSuchElementException` you are getting.

**Comment by colintkn** [comment]
Thank you @lirc572  and @tjtanjin appreciate your help.
