### ISSUE TITLE
Gradle java.lang.UnsupportedOperationException: Unable to open DISPLAY

### ISSUE THREAD

**Issue by douglaswja** [nus-cs2103-AY2021S2/forum#133]
Good day,

I'm trying to do Level-10: GUI.
I have followed the [JavaFX tutorial](https://se-education.org/guides/tutorials/javaFx.html) for both my actual [DukeBot](https://github.com/douglaswja/ip/tree/fix-unable-to-open-display) and a [dummy one](https://github.com/douglaswja/gui-dukebot-stub) that uses a DukeBot stub, as recommended by the [Week 4 Project page](https://nus-cs2103-ay2021s2.github.io/website/schedule/week4/project.html#3-add-increments-as-branches-a-gradle-a-checkstyle-level-10-a-varargs).

In both of these projects, whenever I use the command `./gradlew run` I get the following error:
![unable-to-open-display-error](https://user-images.githubusercontent.com/27340314/107868959-e2f02880-6ec3-11eb-810e-f630b9cd2861.png)

However, in the dummy project where a stub of DukeBot was setup to support the JavaFX classes given in the tutorial, running the Launcher via Intellij works fine. (Running my full DukeBot via Intellij gives an error which I suspect might be unrelated).

Notes:
1. I looked at the [forum post about getting Intellij to build and run using Gradle](https://github.com/nus-cs2103-AY2021S2/forum/issues/97) and have confirmed that my Intellij settings are the same as in the post. So it surprises my that running via Intellij works whereas running via `./gradlew run` does not.
2. I have updated my build.gradle to set the main class as the Launcher.java.
3. I have pushed both projects to github repositories so that anyone whos interested can recreate the error:
- [Branch of Full iP](https://github.com/douglaswja/ip/tree/fix-unable-to-open-display)
- [Branch of Stub DukeBot](https://github.com/douglaswja/gui-dukebot-stub)

**Comment by tjtanjin** [comment]
Googling the error returns quite a number of [results ](https://stackoverflow.com/questions/47509287/run-javafx-jar-as-sudo-unable-to-open-display) that seem to lean the issue heavily towards permissions/dependencies, though they seem to occur mostly on `ubuntu`. That said for your `MainWindow.fxml` file, `fx:controller="MainWindow"` needs to reflect the path to where your `MainWindow.java` file is sitting at. So in your case it would look like `fx:controller="dbot.gui.controller.MainWindow"`. Hopefully it brings you closer to a solution :D

**Comment by douglaswja** [comment]
Thank you for the help @tjtanjin, setting `fx:controller="dbot.gui.controller.MainWindow"` resolved the build and run via Intellij issue.
