### ISSUE TITLE
Error when saving to hard disks

### ISSUE THREAD

**Issue by CharlesLee01** [nus-cs2103-AY2021S2/forum#135]
Hi, 

Can anyone tell me how to fix this error? It pops out when I am trying to save the program to the hard disk on the second run. Writing to the file works well as shown in the first screenshot below.

The jar file works if I run it in the same folder for my code with Intellij.
  
First run
![image](https://user-images.githubusercontent.com/77286511/107870721-dd034300-6ed5-11eb-9e93-bbc1f4480bc9.png)
Second run
![image](https://user-images.githubusercontent.com/77286511/107870933-12109500-6ed8-11eb-8fc5-8cb2c8f2fdb6.png)

Thank you.

**Comment by noelmathewisaac** [comment]
Hi, I think that in your `build.gradle` file the `mainClassName` should be "Launcher" instead of "Duke". Try changing this and regenerating the `.jar` file.

**Comment by CharlesLee01** [comment]
Hi, I have changed it to Launcher but the same error is still there. Why is there AccessDeniedException? It only appears when I call save() the second time.

**Comment by noelmathewisaac** [comment]
Hi, I tried cloning your repo and running it locally (also windows) and it's working fine for me. This could mean that your system is blocking access to  `duke.txt` after the first run for some reason.<br>
Maybe you can refer to [this post](https://stackoverflow.com/questions/28670576/getting-java-nio-file-accessdeniedexception-when-trying-to-write-to-a-folder) and see if it helps.

**Comment by damithc** [comment]
@CharlesLee01 does the same happen when you use a powershell started `as administrator`?

**Comment by rajobasu** [comment]
I had a question (a bit tangential from the main post, really sorry for that). I checked @CharlesLee01 ’s code, there are two main methods one inside Duke and one inside Launcher. How does Java determine which main method to call? Secondly how does changing the ```mainClassName``` inside ```build.gradle``` help? If the main method is changed, shouldnt the entire program change? (ie, one was text-based vs one was UI based). 

Again, sorry for going on a tangent.

**Comment by damithc** [comment]
> I had a question (a bit tangential from the main post, really sorry for that). I checked @CharlesLee01 ’s code, there are two main methods one inside Duke and one inside Launcher. How does Java determine which main method to call? Secondly how does changing the `mainClassName` inside `build.gradle` help? If the main method is changed, shouldnt the entire program change? (ie, one was text-based vs one was UI based).
> 
> Again, sorry for going on a tangent.

@rajobasu perhaps post as a separate issue?

**Comment by damithc** [comment]
@CharlesLee01 was the issue resolved? how?

**Comment by CharlesLee01** [comment]
I'm not sure actually. My project team helped me to test out my duke.jar file and seems like it works well in Mac and Linux.
However, the error sometimes happens on windows. I tried to run it as administrator, but it doesn't help 🙁.

If this is the case? Should I just release my jar file?

Thanks for your reply.
________________________________

**Comment by damithc** [comment]
You can release the JAR file and give the link here so that some others using Windows can help you test it.
In the end, it _needs_ to work on Windows. If it doesn't, the problem needs to be identified and fixed.

**Comment by CharlesLee01** [comment]
I think it works now! 

Thanks!
