### ISSUE TITLE
Week 6 Quiz 'Deadline' extension?

### ISSUE THREAD

**Issue by Cheng20010201** [nus-cs2103-AY2021S2/forum#136]
Hi prof @damithc, regarding week 6's luminus quiz, will there be a slight delay of 'finish early' criteria? The admin info says its within 3 days after the the lecture date but I would say that's a bit tough?, provided last week was CNY and the lecture was actually released ealier than usual.

Thanks!

**Comment by damithc** [comment]
It was going to be Monday (despite the early release). I'll make it Tuesday.

**Comment by Cheng20010201** [comment]
Thanks prof :)
