### ISSUE TITLE
Jar file has JavaFX runtime components are missing error

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [nus-cs2103-AY2021S2/forum#138]
I'm not sure why, I've added the JavaFX gradle dependencies to my build.gradle file, but trying to run my jar file (even within the same build/libs) throws this error.

**Comment by Cp-John** [comment]
I encountered the same error before because I ran Duke instead of Launcher.

**Comment by yhtMinceraft1010X** [comment]
Thanks. I managed to get the build/libs one to work after changing the mainClassName.
