### ISSUE TITLE
TP failed CI

### ISSUE THREAD

**Issue by gycc7253** [nus-cs2103-AY2021S2/forum#139]
Hi all,
May I ask what should we do to pass the team CI?
Since we already has the gradle.yml file in .github/workflows
Thanks a lot in advance!

**Comment by arsatis** [comment]
The error message we had received:

Run codecov/codecov-action@v1
/bin/bash codecov.sh -n  -F  -Q github-action -Z -f /home/runner/work/tp/tp/build/reports/jacoco/coverage/coverage.xml

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-20210129-7c25fce


==> git version 2.30.0 found
==> curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1i zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
==> GitHub Actions detected.
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + /home/runner/work/tp/tp/build/reports/jacoco/coverage/coverage.xml bytes=222022
==> Appending adjustments
    https://docs.codecov.io/docs/fixing-reports
    -> No adjustments found
==> Gzipping contents
        16K	/tmp/codecov.NZiGxZ.gz
==> Uploading reports
    url: https://codecov.io
    query: branch=master&commit=e0d7187a865f195c04e10ebae7fc8eb647a257b1&build=568765456&build_url=http%3A%2F%2Fgithub.com%2FAY2021S2-CS2103T-W13-2%2Ftp%2Factions%2Fruns%2F568765456&name=&tag=&slug=AY2021S2-CS2103T-W13-2%2Ftp&service=github-actions&flags=&pr=&job=Java%20CI&cmd_args=n,F,Q,Z,f
->  Pinging Codecov
https://codecov.io/upload/v4?package=github-action-20210129-7c25fce&token=secret&branch=master&commit=e0d7187a865f195c04e10ebae7fc8eb647a257b1&build=568765456&build_url=http%3A%2F%2Fgithub.com%2FAY2021S2-CS2103T-W13-2%2Ftp%2Factions%2Fruns%2F568765456&name=&tag=&slug=AY2021S2-CS2103T-W13-2%2Ftp&service=github-actions&flags=&pr=&job=Java%20CI&cmd_args=n,F,Q,Z,f
HTTP 403
GitHub API: Forbidden

403
==> Uploading to Codecov
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 16029  100    31  100 15998     88  45578 --:--:-- --:--:-- --:--:-- 45666
    HTTP 403
GitHub API: Forbidden
Error: Codecov failed with the following error: The process '/bin/bash' failed with exit code 1

**Comment by Cheng20010201** [comment]
I was facing similar issues after I modified the original `README.md` file. I got it corrected by fixing no-new-line-at-end-of-file issue as well as trailing-whitespace issues. These are specified as shell scripts in `[root]/.github` of the tp folder.

**Comment by damithc** [comment]
@gycc7253 it might help if you give the link to your team repo, or preferably, the GitHub actions page of your team repo showing the error message.

**Comment by gycc7253** [comment]
Hi prof,
Yes, the link to our team repo is https://github.com/AY2021S2-CS2103T-W13-2/tp

**Comment by tjtanjin** [comment]
Not sure if this is entirely related but I recall seeing a similar error when a commit was first pushed to the tP fork. Interestingly, re-running the workflow a couple of times with literally no other changes did the magic. Could there be some rate limiting going on? Interested to know this as well :D

**Comment by damithc** [comment]
> Yes, the link to our team repo is https://github.com/AY2021S2-CS2103T-W13-2/tp

For the record, this is the error log in concern https://github.com/AY2021S2-CS2103T-W13-2/tp/runs/1903941349?check_suite_focus=true

**Comment by damithc** [comment]
Given the error involves codecov, this part of the AB3 DG may be relevant https://nus-cs2103-ay2021s2.github.io/tp/DevOps.html#code-coverage
It's something you need to do anyway, even if it doesn't fix this problem.

**Comment by arsatis** [comment]
> Given the error involves codecov, this part of the AB3 DG may be relevant https://nus-cs2103-ay2021s2.github.io/tp/DevOps.html#code-coverage
> It's something you need to do anyway, even if it doesn't fix this problem.

I've followed the guide and it seems to have fixed the issue. Thanks prof!
