### ISSUE TITLE
How do we give credit in .md files

### ISSUE THREAD

**Issue by Cheng20010201** [nus-cs2103-AY2021S2/forum#140]
E.g. For the `A-UserGuide` of ip tasks this week, I want to take the design idea from the AddressBook3 user guide, but it seems like the markdown language does not support commenting without displaying.

Anyone got suggestions for how I can possibly give credit to the design idea of others in a markdown file? :))

**Comment by damithc** [comment]
Markdown files can contain HTML comments e.g,,
```html
<!-- this
is a comment -->
```

**Comment by Cheng20010201** [comment]
> Markdown files can contain HTML comments e.g,,
> 
> ```
> 
> ```

Thanks. Didn't notice that. mb :)
