### ISSUE TITLE
How to use the Safe Delete feature in IntelliJ

### ISSUE THREAD

**Issue by nickyfoo** [nus-cs2103-AY2021S2/forum#141]
Hello, I am currently trying to follow the Tutorial: Removing Fields found here: https://nus-cs2103-ay2021s2.github.io/tp/tutorials/RemovingFields.html, but I am having difficult understanding the instructions, namely the line underlined below.
![image](https://user-images.githubusercontent.com/67411893/107990286-11c6e580-700f-11eb-8e89-22ee881a6250.png)

What does it mean to be performing `Safe Delete`s on each entry? 

For instance, in the case in the screenshot, should I be trying to safe delete the parseAddress(String) method (shown below)

![image](https://user-images.githubusercontent.com/67411893/107990619-c3fead00-700f-11eb-8dfc-83a5a289a559.png)

 Because this raises even more safe delete conflicts, and I'm not sure what to do about them
![image](https://user-images.githubusercontent.com/67411893/107990665-db3d9a80-700f-11eb-97d2-77fc3b545f4c.png)

Also, I tried to google intellij safe delete, and it said to "proceed with the appropriate action", but I am not sure what the appropriate action is supposed to be.
![image](https://user-images.githubusercontent.com/67411893/107990812-353e6000-7010-11eb-9c37-9a957b7d2f50.png)

**Comment by rajobasu** [comment]
Essentially the thing is to remove everything that uses that particular class/variable whatnot. Safe delete is just deleting all occurences, and you have to manually change the places which uses that particular class/variable. 

From IntelliJ : 

<img width="686" alt="Screenshot 2021-02-16 at 8 26 04 AM" src="https://user-images.githubusercontent.com/34958324/108004374-a5f57480-7030-11eb-9f26-185ea957c2b4.png">

**Comment by litone01** [comment]
@rajobasu I have the same queries as @nickyfoo. So does it mean we have to manually delete every relevant usage of the "address" in the project code? I did it but found it very tedious and inefficient and some of them are only highlighted after running the tests. Wandering if there is a better way or a recommended flow of thoughts, like you can do this first, then that, then ....
Many thanks!

**Comment by vevek** [comment]
I found [this link](https://www.jetbrains.com/help/idea/safe-delete.html#safe_delete_example) from IntelliJ useful for some examples.

Personally when I use safe delete I like to briefly check the safe delete conflict list to see if there are any areas I would not like safe delete to automatically delete something for me. 

If I recall you can right click the specific conflict to exclude it from safe delete. Although tedious, it would help avoid further issues down the line.

**Comment by nickyfoo** [comment]
Thanks for all the help everyone!
