### ISSUE TITLE
Jar file throwing error on Windows platform (Mac User) 

### ISSUE THREAD

**Issue by ZhangAnli** [nus-cs2103-AY2021S2/forum#142]
Hello, 

I am a mac user and I am trying to verify that my jar file runs cross-platform. It seems to work on mac and linux but it is throwing error on windows platform. 

I tried to google the issue but I can't really get definitive answers, but some are saying its pointing to the discrepancy between Java runtime environment versions. 

For reference, this is the error that appears when attempted to run on Windows through CLI. 

<img width="594" alt="Screenshot 2021-02-16 at 10 30 20 AM" src="https://user-images.githubusercontent.com/65236091/108011398-f923f300-7041-11eb-871d-67dfdbaa2aca.png">

Thanks in advance!

**Comment by tjtanjin** [comment]
Just to rule out possibilities, does building your jar file with `./gradlew clean shadowJar` help?

**Comment by rajobasu** [comment]
Take a look at [this](https://stackoverflow.com/questions/50590250/javafx-exception-in-thread-windowsnativerunloopthread-java-lang-nosuchmethoder) post maybe?

**Comment by damithc** [comment]
@ZhangAnli solved? how?

**Comment by ZhangAnli** [comment]
It managed to work when tested on other Windows machines, probably the error was thrown due to outdated java runtime environment.

**Comment by damithc** [comment]
> It managed to work when tested on other Windows machines, probably the error was thrown due to outdated java runtime environment.

Glad to hear that. Always ensure that you are using Java 11 when testing the JAR file.
