### ISSUE TITLE
A-Streams and A-Lambdas PR branch naming

### ISSUE THREAD

**Issue by nighoggDatatype** [nus-cs2103-AY2021S2/forum#144]
If we complete A-Streams and A-Lambdas in the same commit, how should we name the branch? Does the participation code need us to name the branches for those "branch-A-Streams" or can we just name them something sensible like "branch-A-Streams-Lambda"?

**Comment by chewterence** [comment]
For myself, I tagged A-Streams and A-Lambdas in the same commit, within the branch called branch-A-Lambdas. It kind of makes sense to me to do so because it's only natural to use lambdas with your streams.

**Comment by damithc** [comment]
Doing both in one commit or in one branch is fine, given that these are optional increments. 
But by right, you should have done them as separate PRs, in separate branches. Reason: A secondary objective is to learn how to manage parallel PRs.
![image](https://user-images.githubusercontent.com/1673303/108046796-019b1e80-7080-11eb-9ff6-3536c634af61.png)

**Comment by nighoggDatatype** [comment]
I get that, but it seems weird to separate them in my case, since it doesn't seem sensible to implement streams without lambdas, or vice versa. At least in my case, they are tightly intertwined, and belong together in one logical commit. Anyway, thanks for your feedback.

**Comment by damithc** [comment]
> I get that, but it seems weird to separate them in my case, since it doesn't seem sensible to implement streams without lambdas, or vice versa. At least in my case, they are tightly intertwined, and belong together in one logical commit. Anyway, thanks for your feedback.

Yes, you have a point there. Probably should remove the `A-Lambdas` one.
