### ISSUE TITLE
How will example.jar be launched during testing?

### ISSUE THREAD

**Issue by vevek** [nus-cs2103-AY2021S2/forum#146]
![photo_2021-02-16 19 11 49](https://user-images.githubusercontent.com/1643581/108055357-d669fc80-708a-11eb-9f45-a999627aab7e.jpeg)

Can I confirm that the jar file will only be launched only with the command "java -jar example.jar" in terminal or will it be launched via a double click?

I am wondering about this because the /data/tasks.txt file does not appear to be stored in the same folder as the executable when run via a double-click on my computer (Mac). It works perfectly when launched via the command line.

Thank you!

**Comment by tjtanjin** [comment]
Just to share an observation, I downloaded your final release and tried launching the application via a double click as well as using `java -jar apollo.jar`. In both instances, I noticed that the data folder was created in the directory of the executable.

**Comment by vevek** [comment]
> Just to share an observation, I downloaded your final release and tried launching the application via a double click as well as using `java -jar apollo.jar`. In both instances, I noticed that the data folder was created in the directory of the executable.

Thank you for testing it @tjtanjin ! 😄 For some reason it doesn't work on my computer specifically, but it worked well on my friends mac.

**Comment by chewterence** [comment]
@vevek I am sort of facing the same problem as you are (i am a mac user too and double-clicking on the jar file doesn't launch it). One workaround I found apart from launching from the command line is to right-click > open with > JavaLauncher.
Perhaps that might work for you as well!

**Comment by vevek** [comment]
> @vevek I am sort of facing the same problem as you are (i am a mac user too and double-clicking on the jar file doesn't launch it). One workaround I found apart from launching from the command line is to right-click > open with > JavaLauncher.
> 
> Perhaps that might work for you as well!

Hi @chewterence ! Thank you for the suggestion! Unfortunately that didn't work on my computer. Seeing that it works fine on other computers I'll leave it be. 😄
