### ISSUE TITLE
Use of break with return in a switch block.

### ISSUE THREAD

**Issue by nighoggDatatype** [nus-cs2103-AY2021S2/forum#147]
Lets say I have code that goes like: 
```
switch(x){
case 1:
    return "Bomb";
case 2:
    return "Gun";
default:
    return "Knife";
}
```
Do I have to insert breaks?

**Comment by damithc** [comment]
Hi,
Given below is a backup copy (sent via an alternate server) of the
instructions to access your new TEAMMATES account, in case the first email
landed in your spam box.
-damith (for TEAMMATES)

**Comment by w2vgd** [comment]
`return` statements serve as the break themselves, as the function will exit upon reaching the `return` statement. So I do not think it is necessary to include any `break` in this code snippet.

**Comment by rajobasu** [comment]
If I am not wrong, the ```break``` s wont compile at all -- java will mark it as an unreachable statement.

**Comment by jlxw48** [comment]
I second what @w2vgd has said. `break` allows your program to break out of the switch block, while `return` allows your program to break out of the method call. Choosing one of them will do!

**Comment by creativequotient** [comment]
To add on to what other people have said, IntellIJ will actually highlight the `break` statements as errors as well.
