### ISSUE TITLE
User Guide Tables  and Images not showing on website but showing on Github

### ISSUE THREAD

**Issue by markuz5116** [nus-cs2103-AY2021S2/forum#148]
I uploaded my UG for my IP onto Github, from Github I can see the images and tables just fine. However, when I access my website, the images are not shown and the table is not in format. How do I resolve this? Thanks for your help!
![Screenshot 2021-02-16 205704](https://user-images.githubusercontent.com/50469557/108065863-8d6d7480-7099-11eb-9191-5d102a7c939c.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/50469557/108065867-8e9ea180-7099-11eb-95ae-cf5d7b83c228.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/50469557/108065871-8f373800-7099-11eb-801d-5059824e0f45.png)

**Comment by lirc572** [comment]
Maybe you can try adding `|` at the start and end of all rows, including the header and the separator row. I'm also not sure if you are allowed to have `<br />` tags in a table.

**Comment by damithc** [comment]
Try adding a blank line just above the table.
For images, use relative paths.

**Comment by markuz5116** [comment]
Thank you!! I got it to work! Apparently the issue was my formatting of the table was not constant (i.e. some rows have | at the start and the end, some didn't) and I did not have the new line before it, for the images, the relative path solved the issue.
