### ISSUE TITLE
Java version Issues in JAR

### ISSUE THREAD

**Issue by rajobasu** [nus-cs2103-AY2021S2/forum#149]
I have compiled my Jar file using java version 59.0 it seems. Is it certain that the testers will also use the latest version? Otherwise the file wont open....

**Comment by kouyk** [comment]
According to the [admin page](https://nus-cs2103-ay2021s2.github.io/website/admin/programmingLanguages.html), I think we are supposed to use JDK 11, which should correspond to Bytecode version 55.0 which is what I believe you're referencing to. Testers are also supposed to be running your jar file on JDK 11.

**Comment by Yihe-Harry** [comment]
Hi, same issue here, how can I downgrade the jar file to java 11 ah?

**Comment by rajobasu** [comment]
This seems not to be possible since it is essentially determined at compile time. So you can create a new jar file using a downgraded compiler version but I doubt it is possible to downgrade after the JAR has been created.
