### ISSUE TITLE
Make Duke static or create an object of Duke in the main function? 

### ISSUE THREAD

**Issue by QY-H00** [nus-cs2103-AY2021S2/forum#15]
Hello friends! I'm torn between using static variable and function in Class Duke and not using it but create an object of Duke in main function. The one I'm using right now is making it static.  Will this result in any negative effects?

**Comment by candyhy** [comment]
Personally used static functions in Duke class, and don't think there is any difference in functionality for either options. Probably personal preference:)

Edit: I stand corrected hahhah @kormingsoon 's rationale hits - in view of design rather than simply functionality :')

**Comment by kormingsoon** [comment]
While it would not have any issue for the requirements, down the line. I do think that the negative effect in the future might be the fact that you might be "overloading" your Class Duke right now.

**Comment by kormingsoon** [comment]
Hello, took CS2103 last semester myself, here to give advice when necessary!

While it would not have any issue for the requirements now, you might want to consider the usage of your Duke Class down the line with evolving requirements. (What is the purpose of the class? Right now from your code, it seems to be handling a lot of functions such as parsing and prompting)

I do think that a possible negative effect in the future might be the fact that you might be "overloading" your Class Duke right now.

For example, if you see next week's requirement, where you need to implement a "Find" function, you need to refactor your Duke Class, making it even longer and more complex. Hence more prone to errors and decreased readability.

A suggestion that I have is to divide these functions you have into different classes (perhaps Parser.java). This would allow you to better define the purpose of your Duke Class, and ultimately make your code base as a whole neater and more readable.

This comes hand in hand when you start to implement testing code, which is very often a reflection of your existing code. 

These are just some food for thought and may not be the best way to implement it, but the considerations behind the design is the key focus here! Personally, I often peered ahead in the weeks to observe the different requirements, and altered my current code accordingly.

**Comment by QY-H00** [comment]
> Hello, took CS2103 last semester myself, here to give advice when necessary!
> 
> While it would not have any issue for the requirements now, you might want to consider the usage of your Duke Class down the line with evolving requirements. (What is the purpose of the class? Right now from your code, it seems to be handling a lot of functions such as parsing and prompting)
> 
> I do think that a possible negative effect in the future might be the fact that you might be "overloading" your Class Duke right now.
> 
> For example, if you see next week's requirement, where you need to implement a "Find" function, you need to refactor your Duke Class, making it even longer and more complex. Hence more prone to errors and decreased readability.
> 
> A suggestion that I have is to divide these functions you have into different classes (perhaps Parser.java). This would allow you to better define the purpose of your Duke Class, and ultimately make your code base as a whole neater and more readable.
> 
> This comes hand in hand when you start to implement testing code, which is very often a reflection of your existing code.
> 
> These are just some food for thought and may not be the best way to implement it, but the considerations behind the design is the key focus here! Personally, I often peered ahead in the weeks to observe the different requirements, and altered my current code accordingly.

Yes, that is exactly what I'm worried about. The suggestion to divide functions into different classes is helpful to me. Thank you for your advice!

**Comment by rajobasu** [comment]
I feel since the Duke is the main entry point, it should be only used to set up other processes like an Input loop. Everything else should be taken care of other classes, the main method and indeed the Duke class itself should be very minimal! That is usually how I write my code at least.

**Comment by richardcom** [comment]
Hi!  I think that as for this week's tasks, there is no big difference between the two approaches. However, personally, I prefer to create an object of Duke instead of making its methods and variables static.

Besides the vry good reasons mentioned by @kormingsoon, my answer would add on more from the perspective of OOP practice. If we use static methods/variables in Duke, it means that the states of Duke can be affected by all the instances of the class. Thus the Duke class is not in complete control of its own states, and those static methods can be seen as methods at a global stage. As a result, the principle of encapsulation is not well followed here and it results in more dependence(coupling) between components.

Thus, personally I think creating a Duke object would be better.

**Comment by w2vgd** [comment]
> Hi! I think that as for this week's tasks it would not be of a great difference to choose either one of the two. However, personally, I prefer to create an object of Duke instead of making its methods and variables static.
> 
> Besides the vry good reasons mentioned by @kormingsoon, my answer would add on more from the perspective of OOP practice. If we use static methods/variables in Duke, it means that the states of Duke can be affected by all the instances of the class. Thus the Duke class is not in complete control of its own states, and those static methods can be seen as methods at a global stage. As a result, the principle of encapsulation is not well followed here and it results in more coupling between components.
> 
> Thus, personally I think creating a Duke object would be better.

I think this is a very good point raised by @richardcom, as static methods/fields can be accessed by all instances of the class. 
Below is what I think but I am not very sure if my logic/understanding is accurate though. (Please feel free to correct me if I am wrong!) 

What if this chatbot is to be used by multiple users at once? Then the likely scenario is that there will be multiple threads that each create a new instance of the Duke chatbot to engage with the user. However, with static methods/fields, all of the different instances of Duke chatbot will be accessing the same field. 

Take for example, if we have a static attribute `static List<Task> taskList = new ArrayList<>();` and static methods `addTask(Task task)` and `printAllTasks()`. Then when user A and user B each add a task to their own instance of chatbot and proceed to print their tasks respectively, each user will be able to see both taskA (task that user A added) and taskB (task that user B added) inside their list!!! 

Therefore, I think making the methods and attributes belong to the instance of the class will make more sense in this case.

**Comment by damithc** [comment]
Good discussion guys. Keep it going!
As usual, the important thing is to identify the pros and cons of each alternative and choose the one that fits the context (there is no one answer that fits all situation). It is also fine to go with what works best for the current situation and change it to a different alternative when the situation changes later (compared to outputs in other industries e.g., buildings in civil engineering, code is a lot easier to change later). It's not always possible/practical to come up with a fully future-proof solution, given the future is not 100% predictable.
