### ISSUE TITLE
CI - Code Coverage, which fork to add to Codecov

### ISSUE THREAD

**Issue by nickyfoo** [nus-cs2103-AY2021S2/forum#151]
Regarding CI, code coverage, I looked at this guide: https://nus-cs2103-ay2021s2.github.io/tp/DevOps.html#code-coverage
![image](https://user-images.githubusercontent.com/67411893/108180277-8732d300-7141-11eb-8992-cab579588ea9.png)
and it tells us to 
2.Once you are inside Codecov web app, add your fork to Codecov. 
Can i just clarify which fork is supposed to be added? is it the tp fork of our own group, or do we also have to add our local forks?
I've added the fork of my tp group, as seen below. Is this sufficient?
![image](https://user-images.githubusercontent.com/67411893/108180537-dc6ee480-7141-11eb-8ba5-99c8ba295944.png)

**Comment by damithc** [comment]
The team fork, for sure. Optional for the individual fork.

CodeCov is used as part of the CI that runs when the repo receives a PR or a commit. If you don't configure CodeCov for the individual fork, it will not be able to run CI (will fail half-way). But those commits will still be subjected to CI when they reach the team fork. If you configure CodeCov for both forks, the new commits will get the CI treatment at both levels.

**Comment by nickyfoo** [comment]
Thank you!
