### ISSUE TITLE
arraylist checkstyle error 

### ISSUE THREAD

**Issue by Yihe-Harry** [nus-cs2103-AY2021S2/forum#153]
Hi, checkstyle gives me this error:

[ant:checkstyle] [ERROR] C:\repos\ip\src\main\java\duke\task\TaskList.java:98:28: Array brackets at illegal position. [ArrayTypeSt
yle]

line 98: String eventArr[] = userInput[1].split(" /at ", 2);

How should I fix this? thank you! 👍

**Comment by Yihe-Harry** [comment]
String[] eventArr = userInput[1].split(" /at ", 2); is the answer, though I don't understand what's the propose of this

**Comment by kouyk** [comment]
According to https://se-education.org/guides/conventions/java/intermediate.html#types, it should be String[] eventArr = userInput[1].split(" /at ", 2);

> Rationale: The arrayness is a feature of the base type, not the variable. Java allows both forms however.

Edit: include the rationale
