### ISSUE TITLE
Issues regarding Ui.png on ip showcase page

### ISSUE THREAD

**Issue by lirc572** [nus-cs2103-AY2021S2/forum#155]
Hi prof! According to the instructions on the CS2103 website:

![instructions](https://user-images.githubusercontent.com/34601854/108234377-b23c1780-717f-11eb-893a-27700e8f2d9c.png)

we are supposed to put `Ui.png` under `docs` directory for it to be shown in the [ip showcase page](https://nus-cs2103-ay2021s2.github.io/website/admin/ip-showcase.html), but on the ip showcase page I noticed that the webpage is actually trying to fetch the picture from <https://USERNAME.github.io/ip/Ui.png>, which means if the product website is not set up using GitHub pages exactly as instructed, it might not be shown in the ip showcase page.

Do you think it may be better to use <https://raw.githubusercontent.com/USERNAME/ip/master/docs/Ui.png> as the url of the picture? Otherwise, maybe it woule be better to state explicitly in the instructions that we need to serve our `Ui.png` at <https://USERNAME.github.io/ip/Ui.png>?

**Comment by damithc** [comment]
This way, it helps to detect if the website is set up correctly as well? 🤔

**Comment by lirc572** [comment]
It just gave me a little bit of confusion :sweat_smile:. Since the instructions said using GitHub pages and jekyll is just "one simple way to do it", I thought it is okay to do it in other ways.

![simpleway](https://user-images.githubusercontent.com/34601854/108241040-60e35680-7186-11eb-986e-ba73e3211efc.png)

That's why I suggested the following. :grin:

> Otherwise, maybe it woule be better to state explicitly in the instructions that we need to serve our `Ui.png` at https://USERNAME.github.io/ip/Ui.png?

**Comment by damithc** [comment]
> It just gave me a little bit of confusion 😅. Since the instructions said using GitHub pages and jekyll is just "one simple way to do it", I thought it is okay to do it in other ways.

Good point. I'll remove that phrase. And mention the expectation on the location it should appear.
