### ISSUE TITLE
TP: Anyone encountering errors with jacocoTestReport?

### ISSUE THREAD

**Issue by Cheng20010201** [nus-cs2103-AY2021S2/forum#157]
For tp:
Hi! When Im running `gradle::Tasks/verification/jacocoTestReport` and it is saying something like `Can't add different class with same name: seedu/address/ui/PersonCard` with no further information.

I got this issue because when I try to run the test cases, at the end it shows me something like this:
```bash
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':jacocoTestReport'.
```

This error seems a bit strange to me hmmm, anyone seen anything similar?

**Comment by damithc** [comment]
Does the same happen when GitHub runs the CI?

**Comment by Cheng20010201** [comment]
> Does the same happen when GitHub runs the CI?

No, the CI on github works fine. 🤔

**Comment by Jh123x** [comment]
Hi @Cheng20010201 
I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems).

Maybe you can take a look inside your build folder to see if there are duplicate java class files.
Remove the duplicate class files and see if it still runs

The source below seems to have a similar issue as you.
[Source](https://groups.google.com/g/jacoco/c/Fe3E0oozCwQ?pli=1)

**Comment by Cheng20010201** [comment]
> Hi @Cheng20010201
> I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems).
> 
> Maybe you can take a look inside your build folder to see if there are duplicate java class files.
> Remove the duplicate class files and see if it still runs
> 
> The source below seems to have a similar issue as you.
> [Source](https://groups.google.com/g/jacoco/c/Fe3E0oozCwQ?pli=1)

This one helps! I found on the pc I'm working on there are indeed duplicate java class files (dk why). I moved to another pc and everything is fine. I suppose it was some issues for me locally. Thanks for the help!

**Comment by damithc** [comment]
Thanks @Jh123x for the help.
