### ISSUE TITLE
Why is there nothing to compare between my branch-A-Assertions and master in the remote?

### ISSUE THREAD

**Issue by CSmortal** [nus-cs2103-AY2021S2/forum#159]
**Background:**

I finished doing my parallel branches "branch-A-Assertions" and "branch-A-CodeQuality" for Wk 5 iP. Then I created a PR for ONLY 
"branch-A-Assertions" (my mistake), then merged the PR with the repo. Here is where I realised my mistake, so I followed this [post](https://stackoverflow.com/questions/6481575/undo-a-merge-by-pull-request) and did these steps to reverse the merge PR.

```
git fetch origin
git checkout origin/master -b revert/CSmortal/branch-A-Assertions
git revert -m 1 61720c8e5aa82d127e8eb6ee17e636e7e515d6b7
```

It's my first time using git fetch, so I'm not sure if `git fetch origin` did anything cuz there was no output when the command finished. After doing `git revert -m 1 61720c8e5aa82d127e8eb6ee17e636e7e515d6b7`, there were many unstaged files (not sure if this the expected behaviour), then I committed them with the commit message "revert merge pull request".

**Problem:**
So now I'm trying to create another PR from my remote's "branch-A-Assertions" to "master", but I get the issue mentioned in the title: 
![image](https://user-images.githubusercontent.com/67994626/108364002-8462db80-7230-11eb-881e-50545e048d82.png)
After some toying around, my guess is that this local branch called "revert/CSmortal/branch-A-Assertions" is in someway equals (i'm not sure) to the remote branch "branch-A-Assertions", which explains the picture above. My question is ...

1.  What is this "revert/CSmortal/branch-A-Assertions" branch? Is it just a local branch thats why I can't see it on my remote repo? What is its relationship with the local and remote "branch-A-Assertions"
2.  What do I do now to create a PR from "branch-A-Assertions" to "master"?

This is how it looks like on my SourceTree right now, if you do need them: 
![image](https://user-images.githubusercontent.com/67994626/108365859-a9f0e480-7232-11eb-8334-a47e843cf3ea.png)

Sorry I can't put the link to my PR to the upstream repo here, not sure how

**Comment by kouyk** [comment]
Your branch-A-Assertions share a common history as your master branch, differing only by the merge and undo commit, hence there is nothing to be merged into master. For this case, it is easier to just undo your last 2 commits and do a force push on your master branch. You might want to take reference from [here](https://stackoverflow.com/questions/22682870/git-undo-pushed-commits).

> What is this "revert/CSmortal/branch-A-Assertions" branch? Is it just a local branch thats why I can't see it on my remote repo? What is its relationship with the local and remote "branch-A-Assertions"

it is just a local branch named as "revert/CSmortal/branch-A-Assertions", before doing any reverts it is just a 1:1 copy of your master branch, after the revert commit if you didn't also push the local branch but only merged the revert branch, you won't be able to see the branch on the remote.

**Comment by CSmortal** [comment]
I'm done with that but I'm still kinda confused on the instructions.

![image](https://user-images.githubusercontent.com/67994626/108380071-7a95a400-7241-11eb-9eb8-61ee51d59a39.png)

I don't seem to be able to follow it.  My PR from "branch-A-CodeQuality" to "master" is unable to merge due to conflicts. So do I:

1. Merge my local "master" into local "branch-A-CodeQuality" and resolve merge conflicts
2. Merge the PR
3. Pull from fork to my local "master" (and leave out "branch-A-Assertions"?)

Is that all? I don't seem to be following the instructions at all from the pic.

**Comment by damithc** [comment]
> I don't seem to be able to follow it. My PR from "branch-A-CodeQuality" to "master" is unable to merge due to conflicts.

Step to resolve the conflict.
1. Merge local `master` to local `branch-A-CodeQuality`. This will result in the same conflict. 
2. Resolve the conflict. Complete the merge.
3. Push the `branch-A-CodeQuality` to your fork. Now, the PR will no longer have the conflict and you should be go ahead with merging the PR.
