### ISSUE TITLE
Splitting only on the first space using Regex

### ISSUE THREAD

**Issue by rajobasu** [nus-cs2103-AY2021S2/forum#16]
I was trying to split on the given input string but only at the first space. Simple enough to do with substring/findFirstOccurance operations.

However, how do I do it in shorter/simpler code? 
One option is to figure out some regex using lookbehind. Something like ```“(?<!\s.*)\s”``` should work right? However, I was [reading](https://www.logicbig.com/tutorials/core-java-tutorial/java-regular-expressions/regex-lookbehind.html) that Java doesn’t allow such regexing (or indeed most regex engines).

I wanted to ask if there is indeed any way to make a regex which does do it? 

(Alternate methods with other library functions which are succinct are welcome as well)

**Comment by tjtanjin** [comment]
Hello!

The split function in java allows a second parameter called limit, which is the threshold for the number of elements obtained in the result.

For example:
```
String str = "Hello there, nice to meet you!";
String[] parsedStr = str.split(" ", 2);
```
In the above example, parsedStr will contain these 2 elements:
```
{"Hello", "there, nice to meet you!"}
```

Hope this helps! :)

**Comment by rajobasu** [comment]
Oh right! Thanks a lot for pointing this out. I was under the impression from the documentation that it would only return the first two strings that are matched by the pattern, my bad. 

Still interested in finding a regex way though! Will close the issue later then.

**Comment by tlylt** [comment]
```java
import java.util.regex.Matcher;
import java.util.regex.Pattern;

Scanner sc = new Scanner(System.in);
String line = sc.nextLine();

Pattern p = Pattern.compile("^(\\S+)\\s(.*)$");
Matcher m = p.matcher(line);
if (m.find()) {
  System.out.println(m.group(1));
  System.out.println(m.group(2));
};

// Works for this primitive test case
// Sample input
// todo regex tasks

// Sample output
// todo
// regex tasks
```
Using `Pattern` and `Matcher` does work, although solutions such as the one given by @tjtanjin seem to be more succinct :)

**Comment by tjtanjin** [comment]
> Oh right! Thanks a lot for pointing this out. I was under the impression from the documentation that it would only return the first two strings that are matched by the pattern, my bad.
> 
> Still interested in finding a regex way though! Will close the issue later then.

I edited the example for clarity to future viewers. Didn't realise the example wasn't obvious in highlighting that it returns the rest of the string, thanks too :D

**Comment by litone01** [comment]
Alternatively, we may make use of the `.next()` from the `Scanner` object you have created. It automatically takes in the next String in the input, which is the command word in our case. Then, based on the command, we can carry out relevant steps, for example a `.nextLine()` to read in the rest of the line. 

However, I do agreee with @tjtanjin that his way of splitting may be more elegent during implementation:) Hope it helps in providing another perspective.

**Comment by w2vgd** [comment]
> Alternatively, we may make use of the `.next()` from the `Scanner` object you have created. It automatically takes in the next String in the input, which is the command word in our case. Then, based on the command, we can carry out relevant steps, for example a `.nextLine()` to read in the rest of the line.
> 
> However, I do agreee with @tjtanjin that his way of splitting may be more elegent during implementation:) Hope it helps in providing another perspective.

Used this method mentioned by @litone01 as well. However, one thing to note is that if you use `.next()` to scan for the command first, and proceed to use `.nextLine()` to scan for the remaining string immediately, then the test script _input.txt_ should end with a newline character as the method `.nextLine()` is blocking. For e.g. the _input.txt_ file should be something like

![image](https://user-images.githubusercontent.com/65358857/104986292-b6282d00-5a4d-11eb-830d-b5f36f6d5c52.png)
(where the last empty line in the file simulates the user pressing "enter/return" keyboard button)

Without the last empty line, and if `.next()` is immediately followed by `.nextLine()`, the command would not be executed as the `.nextLine()` call would be blocking to wait for an input that is not there. A workaround without the last empty line may to be check the whether the command is "bye" right after the `.next()` method, and not calling `.nextLine()` if the command is indeed "bye". But I do not think this is a good way to code our program.


However, I do agree that the `.split(regex, limit)` method provided by @tjtanjin is much more cleaner and simpler! Didn't think of this previously. May want to update my code accordingly too 😅
