### ISSUE TITLE
Can't pass Person Test / AddCommandIntegrationTest 

### ISSUE THREAD

**Issue by ZhangAnli** [nus-cs2103-AY2021S2/forum#160]
Hello, 

Basically, I'm trying to complete the testing stage of Tuturial 3 and I can't pass this last test case. 

I followed the instructions closely and am currently this issue: 

![Screenshot 2021-02-18 at 10 46 47 PM](https://user-images.githubusercontent.com/65236091/108373747-2f789280-723b-11eb-9ecb-3dc3ee769b35.png)

Delving into this test case, I see that the error lies in the code here: 

![Screenshot 2021-02-18 at 10 47 14 PM](https://user-images.githubusercontent.com/65236091/108373801-40290880-723b-11eb-9fc2-86a3e0cd6037.png)

Basically, it's testing that the same name with different attributes should still be considered the "same person". (Refer to last highlighted line (assertTrue....)

So what I tried to do is to go to Person.java's isSamePerson() and edit it as such: 

![Screenshot 2021-02-18 at 10 48 40 PM](https://user-images.githubusercontent.com/65236091/108374010-74042e00-723b-11eb-8646-a658d422bf1b.png)

However, if I edit it as such and run the testing again, I get faced with another test case that fails. (below) 

![Screenshot 2021-02-18 at 10 49 19 PM](https://user-images.githubusercontent.com/65236091/108374091-8aaa8500-723b-11eb-84c7-da366c74dc32.png)

I've tried to solve this particular test case error but was not successful.  (Refer below) 

![Screenshot 2021-02-18 at 10 52 30 PM](https://user-images.githubusercontent.com/65236091/108374498-fbea3800-723b-11eb-8a80-40009e2ecc57.png)

Has anyone faced a similar issue with these two related test cases? 

Thanks in advance!

**Comment by Prabhakaran-Gokul** [comment]
@ZhangAnli Hi, Maybe you are looking for this [particular commit](https://github.com/se-edu/addressbook-level3/commit/1fe37e1913f576a8d6711d6c4f3d51471d39d89b) ?

**Comment by ZhangAnli** [comment]
Thank you so much! This solved my issue!
