### ISSUE TITLE
ClassNotFoundException when opening jar file

### ISSUE THREAD

**Issue by hengyiqun** [nus-cs2103-AY2021S2/forum#163]
Hi all

I am trying to open my jar file with the following command:
`java -jar Duke.jar`

but it keeps reporting a ClassNotFoundException.
![image](https://user-images.githubusercontent.com/20364508/108525936-8cdc1480-730b-11eb-88a1-aedac08fbb15.png)

I am wondering if any of you all have experienced similar issues, and could advise me on how to proceed.
Thanks!

**Comment by tjtanjin** [comment]
Try changing your `mainClassName` in `build.gradle` to `duke.Launcher` :)

**Comment by hengyiqun** [comment]
Hi @tjtanjin 
Thanks for your help. I have tried both duke and Launcher, and for some reasons, it didn't occur to me that I needed to use duke.Launcher haha
