### ISSUE TITLE
Codecov issue for Tutorial 2 for TP

### ISSUE THREAD

**Issue by markuz5116** [nus-cs2103-AY2021S2/forum#164]
![image](https://user-images.githubusercontent.com/50469557/108528902-e134c380-730e-11eb-8461-428f875ad4a2.png)
I received this message when I was trying to submit my pull request for TP. 
I was wondering is it because my code is different from the one shown?

**Comment by damithc** [comment]
@markuz5116 CodeCov is a tool used in the tP but not in the iP. So, you are likely to use a CodeCov report for every PR you submit in the tP. The report tells you about how your PR affects the test coverage level of the code base.
That being said, the topic _test coverage_ is to be covered in week 8. So, you can ignore it for now.
