### ISSUE TITLE
Typo in Week 7 - Topics - [W7.2] Design: High-Level View

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#167]
Hello, would like to point out a very minor typo in the instruction right before
[W7.2] Design: High-Level View:
![image](https://user-images.githubusercontent.com/41845017/108617026-cddc4200-744d-11eb-9ba5-5e3c5e71fa53.png)
Thank you.

**Comment by damithc** [comment]
Good catch! Thanks very much reporting this bug @tlylt Will fix in the next update.
