### ISSUE TITLE
Questions about update the link of Github Actions build status badge

### ISSUE THREAD

**Issue by enhao25** [nus-cs2103-AY2021S2/forum#168]
Hi. In this week's tp, one of the task we are required to do is to "Update the link of the GitHub Actions build status badge (Build Status) so that it reflects the build status of your team repo.". However, I tried to go to the Actions page and tried google searching but then I am still unsure of what actions are required for this task. 

Please advise.

Thank you.

**Comment by kouyk** [comment]
![image](https://user-images.githubusercontent.com/1729497/108620495-8b276380-7467-11eb-8c3e-f43e1939d6db.png)

Assuming that you have enabled Github Actions on your team repo, from the image above you can see that after selecting the "Java CI", the right submenu has an option to create the status badge, in the pop up will be the markdown formatted link of the badge that you can copy and paste into the README.md in your team repo.

**Comment by enhao25** [comment]
Ahhh! I didn't click on the right submenu button that leads to the "Create status badge" functionality!

Thank you so much!
