### ISSUE TITLE
Clarification on commit message

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#169]
Hello!

Just a small clarification to make. Given that the first word of the commit message has to be capitalised, would both of the following be acceptable for commit messages?
```
Docs: update readme to include image
Docs: Update readme to include image
```
That is, for the word immediately after the type of commit, do we need to capitalise it as well?

Thank You!

**Comment by damithc** [comment]
The example given [here](https://se-education.org/guides/conventions/git.html) doesn't capitalize, but either way is fine.
In some cases, it may not be appropriate to capitalize the scope e.g., if the word is supposed to be a folder name that is in lower case e.g., `docs:`
When grading, we don't check specifically for the capitalization of the commit messages.

**Comment by tjtanjin** [comment]
Ok thank you!
