### ISSUE TITLE
Debug console does not appear for AB3

### ISSUE THREAD

**Issue by fairyinabottle4** [nus-cs2103-AY2021S2/forum#172]
(Issue with IntelliJ 2021.03.01)

Hi, I'm going through the "Get Familiar with Code Base" part of week 6 for the AB3. I am facing an issue where I am unable to start the debugger for some reason. I never faced this issue in my IP. When I click 'debug' the UI opens as per normal, but nothing appears on the debug console. Could someone tell me why>

<img width="743" alt="tp debugger" src="https://user-images.githubusercontent.com/46418515/108800984-7ebe1a80-75cf-11eb-9565-fa85fb5252b1.PNG">

**Comment by YuFeng0930** [comment]
I have the same message as yours in the debug console, but I got another pop up window after a few seconds showing all the debugging message. Also, I have the "Main.main()" tab, so I guess maybe you should check whether you set the configuration (the drop down list next to "Run") or not.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/56251951/108801566-08bab300-75d1-11eb-898c-502848c858d2.png">

**Comment by damithc** [comment]
Other things to try:
* Ensure you have put a breakpoint in the code and breakpoint is in a statement that will be executed during normal operations
* If the GUI is open, try running a few commands in the GUI

**Comment by fairyinabottle4** [comment]
> Ensure you have put a breakpoint in the code and breakpoint is in a statement that will be executed during normal operations

Sorry, forgot to do that. That solved my problem
