### ISSUE TITLE
QuantumRenderer Error

### ISSUE THREAD

**Issue by WeiLiangLOL** [nus-cs2103-AY2021S2/forum#173]
```text
On Linux, using Java 11, for the SimpleBot.jar uploaded on 02-19-2021 (MM-DD-YYYY) at 19:35:34:
Graphics Device initialization failed for : es2, sw Error initializing QuantumRenderer: no suitable pipeline found 
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found at 
com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280) at 
com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222) at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260) 
at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267) at
```

Hi, anyone experience a similar issue with their iP? I can't seem to reproduce the error. Any advice would be nice!

**Comment by damithc** [comment]
This issue (from the previous semester) seems relevant https://github.com/nus-cs2103-AY2021S1/forum/issues/265

**Comment by WeiLiangLOL** [comment]
Hi, thanks prof, I've referred to the linked issue. It has to do with the dependency resolution process in gradle.

I <s>am using</s> was using the openjfx plugin to manage the jfx dependencies, but didn't realise the plugin only pulls the version specific to your distribution. Thanks so much! Will quickly update and push.

For others that are in same predicament, please change the 

```groovy
plugins {
    id 'org.openjfx.javafxplugin' version '0.0.9'
}
```

to individually pulling the dependencies

```text
dependencies {   
...
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
...
```

**Comment by damithc** [comment]
Nice. Thanks for sharing the solution @WeiLiangLOL

**Comment by jxrrelo** [comment]
Hi, thank you Prof and Weiliang. I faced a similar issue and couldn't resolve it even after attempting several suggestions I found online. The proposed solution by Weiliang was straightforward and worked for me. Thanks also, for providing an explanation to what caused the issue. Cheers!
