### ISSUE TITLE
Github page failed to build UG site.

### ISSUE THREAD

**Issue by markuz5116** [nus-cs2103-AY2021S2/forum#179]
![image](https://user-images.githubusercontent.com/50469557/109129162-4e22e000-778b-11eb-9799-1ecd4dce3474.png)
When updating the UG of our tp, there was a build failure for the pages, but no error was given. 
How should I start to tackle this?

Thank you for your help!

**Comment by tlylt** [comment]
Hello, perhaps you might want to leave this in at the top of your UserGuide.md?
![image](https://user-images.githubusercontent.com/41845017/109130146-5b8c9a00-778c-11eb-9182-09efe6a13a7a.png)

**Comment by markuz5116** [comment]
> Hello, perhaps you might want to leave this in at the top of your UserGuide.md?
> ![image](https://user-images.githubusercontent.com/41845017/109130146-5b8c9a00-778c-11eb-9182-09efe6a13a7a.png)

This worked! Thank you!
