### ISSUE TITLE
Call to super() in AB3 StorageManager.java, is it necessary?

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#181]
Hello, just browsing through the inherited TP code and I saw this weird line that invokes `super()` in the concrete implementation of the `Storage` interface, within the `StorageManager` class (line 23 -30):
```java
    /**
     * Creates a {@code StorageManager} with the given {@code AddressBookStorage} and {@code UserPrefStorage}.
     */
    public StorageManager(AddressBookStorage addressBookStorage, UserPrefsStorage userPrefsStorage) {
        super();
        this.addressBookStorage = addressBookStorage;
        this.userPrefsStorage = userPrefsStorage;
    }
```
While I understand that calling `super()` invokes the parent constructor, in this particular case, it seems to do nothing? 
P.S. I Googled it and found this [stackoverflow post](https://stackoverflow.com/questions/21181125/super-constructor-if-there-is-no-super-class) which seems to confirm my suspicion. Wonder if anyone knows of any other reason why the `super()` is there?

**Comment by damithc** [comment]
Something to try: remove it and see if it makes any difference.

**Comment by tlylt** [comment]
> Something to try: remove it and see if it makes any difference.

Running the application with & without it seems to have no observable differences that I can tell. Tests are fine as well. I guess I will conclude that the call to super is unnecessary for now.

**Comment by damithc** [comment]
Java inserts a `super()` call automatically at the start of the child classes (if one is missing). An explicit call to `super(...)` is needed only if the parent class doesn't have a parameter-less constructor or you want to use a different constructor of the parent class. In this case, the parent class is by default the `Object` class which already has a parameter-less constructor (again, Java automatically inserts a parameter-less constructor if the class doesn't have _any_ constructors at all).

So, you are right @tlylt. This call to `super()` is useless and should be removed. I suspect it is some legacy code that got left behind by mistake.  Good catch 👍 Feel free to create an issue in https://github.com/se-edu/addressbook-level3/issues to report it.

**Comment by tlylt** [comment]
> An explicit call to `super(...)` is needed only if the parent class doesn't have a parameter-less constructor

Hi prof, could you explain the above statement? I don't understand why there is a need to call `super()` if the parent class doesn't have a parameter-less constructor.

**Comment by damithc** [comment]
Good question @tlylt . Let's see if someone else in the class wants take a crack at it first.

**Comment by samuelfangjw** [comment]
@tlylt If you would like to use a constructor of the parent class that requires parameters, you have to explicitly call `super(...)` with the parameters, else by default `super()` without parameters will be called.

**Comment by vevek** [comment]
I agree with @samuelfangjw . In this case since the parameters of super aren't being used, you can omit super() as it would be called regardless.

**Comment by kouyk** [comment]
@tlylt if the parent class does not have a parameter-less constructor, it means that the default call to one will fail to match any constructors, but it is not quite possible to deduce what arguments are to be passed to the parent class constructor, hence an explicit call is necessary in this case. The parent class constructor has to be called in one way or another, be it implicit or explicit, or else the parent class data members and virtual method table cannot be initialised.

**Comment by tlylt** [comment]
Thanks guys for contributing to this discussion. I think I overlooked the details when I thought about the issue, which I will now add below the extracted statements from sources that I just found:
- If no constructor is defined in a class, Java compiler automatically create a no-argument (no-arg) constructor, that simply issues a super() call
- The default no-arg constructor will not be automatically generated, if one (or more) constructor was defined. In other words, you need to define no-arg constructor explicitly if other constructors were defined.
- If the immediate superclass does not have the default constructor (it defines some constructors but does not define a no-arg constructor), you will get a compilation error in doing a super() call. Note that Java compiler inserts a super() as the first statement in a constructor if there is no super(args).
- Java guarantees that the constructor method of a class is called whenever an instance of that class is created. It also guarantees that the constructor is called whenever an instance of any subclass is created. In order to guarantee this second point, Java must ensure that every constructor method calls its superclass constructor method. Thus, if the first statement in a constructor does not explicitly invoke another constructor with this() or super(), Java implicitly inserts the call super(); that is, it calls the superclass constructor with no arguments. If the superclass does not have a constructor that takes no arguments, this implicit invocation causes a compilation error. docstore.mik.ua/orelly/java-ent/jnut/ch03_04.htm

I will just walk through this example from a StackOverflow post, to convince myself of this fact that I am unaware of until today:sweat:
```java
public class Base {
   public Base(int foo) {
   }
}

public class Subclass extends Base {
   public Subclass() {
      super(15);
   }
}
```
If the constructor of `Subclass` does not include the `super(15)` call, Java will implicitly insert `super()` in the first line of the constructor, which will cause an issue in the case where the `Base` class does not have an parameter-less constructor(`Base()`), which unfortunately will not be automatically generated because there is an existing constructor(`Base(int foo)`).

Sources:
- https://www3.ntu.edu.sg/home/ehchua/programming/java/J3b_OOPInheritancePolymorphism.html#zz-2.
- https://docstore.mik.ua/orelly/java-ent/jnut/ch03_04.htm
- https://stackoverflow.com/questions/2632882/calling-super

**Comment by damithc** [comment]
Thanks @tlylt for compiling and sharing this very good summary

**Comment by damithc** [comment]
@tlylt you can close this issue if the matter is resolved.
