### ISSUE TITLE
jar file keeps failing even though im using java 11

### ISSUE THREAD

**Issue by rachelljt** [nus-cs2103-AY2021S2/forum#182]
This is the error i have been getting: "Error: Main method not found in class duke.Duke, please define the main method as: public static void main(String[] args) or a JavaFX application class must extend javafx.application.Application"

I don't seem to know whats wrong as the app runs perfectly fine on my computer but the jar file couldn't be opened by my teammates. 

Does anyone know what should i do? Thank you!

**Comment by tjtanjin** [comment]
Within your `build.gradle` file, try changing `mainClassName` to `duke.Launcher` instead :)

**Comment by rachelljt** [comment]
Hi! I have tried changing it to duke.Launcher but it still doesn't work...

**Comment by tjtanjin** [comment]
The issue might be in `Storage.java`. Based on the latest commit on your remote repository, the path for your data storage is absolute. Try a relative path instead :)

**Comment by rachelljt** [comment]
hello thank you so much for your help! it worked :D

**Comment by damithc** [comment]
thanks @tjtanjin for the help.
@rachelljt you can close this issue if the problem is resolved.
