### ISSUE TITLE
jar file keep failing smoke test even though it runs locally and on other laptops

### ISSUE THREAD

**Issue by austenjs** [nus-cs2103-AY2021S2/forum#183]
I failed automated smoke testing of my final jar file for IP. I have tried the jar file on my friend's laptop and it worked. I am using Java version 11 and IntelliJ 2020.1.3 on my local computer.

**Comment by SoonKeatNeo** [comment]
Could you share what was the problem that the automated smoke test was finding? That might make it easier to narrow the issue down.

**Comment by austenjs** [comment]
The error sent from the automated test:
•	On Windows, using Java 11, for the duke.jar uploaded on 02-22-2021 (MM-DD-YYYY) at 21:47:45:
Error: LinkageError occurred while loading main class Launcher java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0 
•	On Linux, using Java 11, for the duke.jar uploaded on 02-22-2021 (MM-DD-YYYY) at 21:47:45:
Error: LinkageError occurred while loading main class Launcher java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0 
•	On Mac, using Java 11, for the duke.jar uploaded on 02-22-2021 (MM-DD-YYYY) at 21:47:45:
Error: LinkageError occurred while loading main class Launcher java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0 


> 
> 
> Could you share what was the problem that the automated smoke test was finding? That might make it easier to narrow the issue down.

**Comment by samuelfangjw** [comment]
[this](https://github.com/nus-cs2103-AY2021S2/forum/issues/68#issuecomment-769674560) issue seems to be similar to yours, can try and see if the solution provided by @tjtanjin works for you!

**Comment by austenjs** [comment]
> 
> 
> [this](https://github.com/nus-cs2103-AY2021S2/forum/issues/68#issuecomment-769674560) issue seems to be similar to yours, can try and see if the solution provided by @tjtanjin works for you!

Thanks!
