### ISSUE TITLE
About weekly progress in TP dashboard

### ISSUE THREAD

**Issue by Hzxin** [nus-cs2103-AY2021S2/forum#184]
![weekly report](https://user-images.githubusercontent.com/61725744/109305822-3fb2f200-7879-11eb-8f24-746f8948edb7.png)
![history](https://user-images.githubusercontent.com/61725744/109305928-6b35dc80-7879-11eb-84fa-d1d25efc6d9f.png)

About the weekly report, I have already made quite a few PRs/commit to the team repo master, but the team progress dashboard isn't updated. Am I missing out on some steps to be detected?

**Comment by damithc** [comment]
@Hzxin is it possible the PRs were merged _after_ the dashboard was updated? In that case, please check again after the next dashboard update.

**Comment by Eriksen2411** [comment]
@damithc Hi prof, I'm having the same situation as @Hzxin so I think it's better for me to include in here also. My tp weekly progress is also: Did not contribute any commits to the master branch of the team repo. Although I have made some pr and do the merge by myself also to team tp repo. Here is an example of pr by me and merge by me also:
![image](https://user-images.githubusercontent.com/65208242/109342838-6d169480-78a7-11eb-9645-7886597a3fa0.png)
This merge and other merge of my pr has been done on Feb 25, but the tp dashboard does not update it for 2 days already. I wonder if any bug in the checking system or it's my fault somewhere. I also think that I have followed the step for the tp.
![image](https://user-images.githubusercontent.com/65208242/109343160-d8f8fd00-78a7-11eb-9d8f-b339e06fd85b.png)

**Comment by damithc** [comment]
@Eriksen2411 Should be rectified now. Please check.

**Comment by damithc** [comment]
@Hzxin problem resolved now?

**Comment by Hzxin** [comment]
@damithc Problem has been resolved Thank you for the explanation
