### ISSUE TITLE
CommandExecutor interface not directly implemented

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#187]
Hi, there's a piece of code that I do not understand while trying to read and understand the given code in addressbook. 

In the `MainWindow#fillInnerParts` method on line 122, `CommandBox commandBox = new CommandBox(this::executeCommand);` is called and according to the constructor for `CommandBox`, it takes in a `CommandExecutor` object. So my question is, why is `this::executeCommand` an object of type `CommandExecutor`? I can't seem to understand why is the method reference inferred to be an object of type `CommandExecutor`. 

The relevant pieces of code is given below for easier reference:
`MainWindow#fillInnerParts` method line 122-123:
![image](https://user-images.githubusercontent.com/65358857/109326109-b825ad00-7891-11eb-9a52-e45e8cbca4d9.png)

`MainWindow#executeCommand` method:
![image](https://user-images.githubusercontent.com/65358857/109326365-0c309180-7892-11eb-8924-fd0e36b9a03b.png)

Constructor for `CommandBox`:
![image](https://user-images.githubusercontent.com/65358857/109326183-cc69aa00-7891-11eb-9260-aed8fa8559b5.png)

Definition for `CommandExecutor` under `CommandBox.java`:
![image](https://user-images.githubusercontent.com/65358857/109326308-f4f1a400-7891-11eb-8c5e-e622ea96b1f6.png)

**Comment by samuelfangjw** [comment]
`CommandExecutor` is a functional interface. Functional interfaces have a single abstract method and we can declare them by assigning a lambda expression or method reference to them. 

In this case, we do not actually call the `executeCommand()` method to get the return result, we are just assigning the method to the `CommandExecutor` function interface and calling the constructor with the `CommandExecutor` object.

Perhaps writing this example as follows will make it more clear:
```java
CommandBox.CommandExecutor commandExecutor = this::executeCommand;
CommandBox commandBox = new CommandBox(commandExecutor);
commandBoxPlaceholder.getChildren().add(commandBox.getRoot());
```

**Comment by samuelfangjw** [comment]
[This link](http://tutorials.jenkov.com/java-functional-programming/functional-interfaces.html) explains functional interfaces a lot better than I can! It only shows lambda expressions being assigned to functional interfaces, but according to the [java 11 documentation](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/function/package-summary.html) method references can be assigned as well.

**Comment by w2vgd** [comment]
Thanks @samuelfangjw for the explanation. I think I understand now. Because method references are a special kind of lambdas, and functional interfaces can be instantiated with lambda expressions, `this::executeCommand` is just an instantiation of the `CommandExecutor` interface.

**Comment by samuelfangjw** [comment]
> Thanks @samuelfangjw for the explanation. I think I understand now. Because method references are a special kind of lambdas, and functional interfaces can be instantiated with lambda expressions, `this::executeCommand` is just an instantiation of the `CommandExecutor` interface.

This is how I understand it too. Thanks for adding that "method references are a special kind of lambdas", I learnt something new today! From the [official java tutorials](https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html),  Method references "are compact, easy-to-read lambda expressions for methods that already have a name."
