### ISSUE TITLE
Failing tests after adding remark command 

### ISSUE THREAD

**Issue by mesyeux** [nus-cs2103-AY2021S2/forum#189]
After I finished the tutorial for the remark command, I tried to ran the tests again but a lot of them failed and I'm not sure why, since I did not modify tests in other test classes except for RemarkCommandTest. In the picture below there's an error for the equals method in RemarkCommandTest, but looking at the code it doesn't make sense as both objects are the same. I tried to run the debugger and the error "Cannot find local variable 'addressBookFromFile'" comes up, but I can't seem to find which local variable it is referencing to in the RemarkCommandTest method. If anyone could help it would be greatly appreciated!

![error](https://user-images.githubusercontent.com/70282468/109388359-8f5cf080-7941-11eb-9ec2-b375923d8568.jpg)
![error2](https://user-images.githubusercontent.com/70282468/109388529-a6501280-7942-11eb-994e-0d0ab56e585e.jpg)

**Comment by tjtanjin** [comment]
You may not have modified other test files within `src/test` but the modifications to the classes within `src/main` may be the reason for this failed test cases. Seeing as there are only 11 failing test cases, they should be resolvable with more persistent digging. Unfortunately it is a bit hard to tell from the screenshots alone what the causes are. Alternatively, you may push a temporary branch and link it here for others to have a better look. All the best! :D

**Comment by cyf930** [comment]
Also remember to change all the json files associated with the tests:))

**Comment by YuFeng0930** [comment]
Also remember to change all the json files associated with the tests:))

**Comment by ypinhsuan** [comment]
Hi I'm from your senior batch, dropping by to see if I can help with tech problems. I took a look at your code and I think the problem is in the `equals` method of `Remark` class. Hope it helps :)

**Comment by mesyeux** [comment]
Thank you so much, that was the problem!
