### ISSUE TITLE
Errors like "java: package javafx.collections does not exist" while running JUnit Tests in iP

### ISSUE THREAD

**Issue by mesyeux** [nus-cs2103-AY2021S2/forum#191]
When I use "gradlew test" to run the JUnit tests in my iP, everything works fine. However if I right click the test folder and click on "Run 'All Tests'", a lot of errors come up (in all the classes where I imported javafx). Is there something wrong and will this affect the grading? 
![errorr](https://user-images.githubusercontent.com/70282468/109410881-21fc9e80-79d9-11eb-9779-cae936226064.jpg)
![errorss](https://user-images.githubusercontent.com/70282468/109410901-3a6cb900-79d9-11eb-9036-8601aade0c3e.jpg)

**Comment by candyhy** [comment]
Hello, have u tried changing your mainClassName in build.gradle to duke.Launcher?

**Comment by kouyk** [comment]
I've cloned your repo and tested it myself, the tests do run except that they are failing. Perhaps you can delete the `.idea` directory and import the project again to see if intellij corrects everything.

**Comment by mesyeux** [comment]
That's odd! I tried deleting the .idea and then tried to run the tests with both 'gradlew test' and right clicking "Run 'All Tests'", and both methods had all test cases pass, so I'm not sure why it's failing on yours. 
<img width="960" alt="testsuccess" src="https://user-images.githubusercontent.com/70282468/109412137-3e9cd480-79e1-11eb-8c12-785acaeba4cb.png">
However after I did this, I can only run my jar file by 'gradlew run' and not when I right click "run" on my Launcher class...

**Comment by kouyk** [comment]
> I'm not sure why it's failing on yours

If it helps I'm on your master branch `918128baee8c7e5933dd1ee7e683bc3f3fe3ec6d`, perhaps you have commits not yet pushed to remote or you're on another branch?

> However after I did this, I can only run my jar file by 'gradlew run' and not when I right click "run" on my Launcher class...

I did manage to run it both ways, perhaps the intellij run configuration is still wrong? A simple way to find out is to push all changes to github, clone into another directory and import into intellij again.

**Comment by mesyeux** [comment]
Hmm I checked and all my commits are already pushed. I tried importing the project again after cloning and both launching & the tests work now! I suppose it was something wrong with the IntelliJ configuration. Thanks so much for your help!

**Comment by damithc** [comment]
Thanks @kouyk for the help.
@kouyk it's possible that you had unstaged changes (i.e., those changes will not be in the fork even if all your commits have been pushed).
