### ISSUE TITLE
Run repository-wide tests keeps failing when trying to PR

### ISSUE THREAD

**Issue by figo2127** [nus-cs2103-AY2021S2/forum#192]
![image](https://user-images.githubusercontent.com/61351392/109422454-8ab63c00-7a16-11eb-863a-7986ff952fc1.png)
Hi guys why do I keep failing this when I made sure build is already successful? And I resolved all checkstyle errors.
![image](https://user-images.githubusercontent.com/61351392/109422467-9b66b200-7a16-11eb-9d0c-54a106ee4520.png)
All the JUnit tests passed as well, I just can't seem to get past this error. Thanks in advance!

**Comment by candyhy** [comment]
Hello, Ive had this issue when my code failed style check (missing a newline in one of the files). Perhaps u can check on that just to make sure?

**Comment by figo2127** [comment]
Hi @candyhy yea I made sure those errors are all resolved.
![image](https://user-images.githubusercontent.com/61351392/109422637-5a22d200-7a17-11eb-904a-f4da4ac174c7.png)
Is there by any chance this could be the problem?

**Comment by damithc** [comment]
@figo2127 did you (or your team members) modify the `run-checks.sh` file?

**Comment by figo2127** [comment]
@damithc I don't think so. Their PR seems to pass the checks

**Comment by candyhy** [comment]
Hi yes i later noticed that the checkstyle tests have been passed. Based on your error messages, I believe it could be a type issue. Perhaps your string values were not enclosed in double quotes, which is necessary in JSON. You might find this link useful as they seem to have encountered the same error as you:
https://stackoverflow.com/questions/29856116/handling-unrecognized-token-exception-in-custom-json-with-jackson

**Comment by figo2127** [comment]
I tried copying a working copy of the run-checks.sh file from the remote repo to my local copy. Still failed the check.

**Comment by damithc** [comment]
@figo2127 please share the link to your PR here so that others can have a look at the code.

**Comment by figo2127** [comment]
https://github.com/AY2021S2-CS2103T-T13-2/tp/runs/1998547056?check_suite_focus=true

**Comment by damithc** [comment]
First clue:
![image](https://user-images.githubusercontent.com/1673303/109423337-f948c900-7a19-11eb-9c49-3f4bfe96622b.png)
The above (i.e., Unix saying there is an `^M` at the end of a line) happens when you modify a file in Windows, resulting in a line ending that is not compatible with Unix.

Second clue:
![image](https://user-images.githubusercontent.com/1673303/109423407-31500c00-7a1a-11eb-866b-6b5ee21736e6.png)

**Comment by figo2127** [comment]
I replaced the entire config directory from a working repository. Still failing checks though..

**Comment by damithc** [comment]
> I replaced the entire config directory from a working repository. Still failing checks though..

@figo2127 Looks at the `Files changed` tab of your PR. Did you intend for this PR to contain changes to 250 files?

**Comment by figo2127** [comment]
@damithc Nope. I did not intend to

**Comment by figo2127** [comment]
@damithc I guess those files are automatically changed to be compatible with linux? Im not sure

**Comment by damithc** [comment]
As a general rule, never commit without checking if the commit contains exactly the changes you wanted.
You need to revert all those unintended changes.

Also, figure out how those changes happened in the first place. One usual suspect is the IDE. Some IDEs automatically change the line endings of all files to suit the local OS. If that is the case, that feature need to be disabled. Intellij doesn't usually do that by default. Are you using some other IDE?

**Comment by figo2127** [comment]
@damithc I'm using Intellij. But I faced this problem of not being able to find remote branch "tutorial-adding-command" in sourcetree to push to so I used my WSL ubuntu terminal to push my changes. 

I think that's where the file changes problem originated?

https://github.com/nus-cs2103-AY2021S2/forum/issues/193

**Comment by damithc** [comment]
> @damithc I'm using Intellij. But I faced this problem of not being able to find remote branch "tutorial-adding-command" in sourcetree to push to so I used my WSL ubuntu terminal to push my changes.
> 
> I think that's where the file changes problem originated?

Yup, most likely.

**Comment by figo2127** [comment]
@damithc 
![image](https://user-images.githubusercontent.com/61351392/109425860-6dd53500-7a25-11eb-9858-939823e85fa4.png)
![image](https://user-images.githubusercontent.com/61351392/109425878-7cbbe780-7a25-11eb-8493-61a2174f378f.png)
Hi Prof Damith, I still couldn't pass the tests despite making sure the line separator is system-dependent

**Comment by figo2127** [comment]
Thank you prof @damithc and @candyhy, I think I solved it :)
