### ISSUE TITLE
Weekly progress in TP dashboard

### ISSUE THREAD

**Issue by arsatis** [nus-cs2103-AY2021S2/forum#194]
Similar to issue #184, my group members have already made quite a few PRs/commits to the team repo master. We have made some merging back on 26 and 27 Feb (the dashboard was last updated on 28 Feb), but the team progress dashboard still isn't updated.

![image](https://user-images.githubusercontent.com/55139982/109445874-81ab8600-7a7b-11eb-87bc-f46a610d1b71.png)

Is there anything that my team might have missed out? We have did some commenting/peer reviewing, merging by another teammate, and creating PRs from a separate branch. A log of our PRs can be found here: https://github.com/AY2021S2-CS2103T-W13-2/tp/pulls?q=is%3Apr+is%3Aclosed

**Comment by damithc** [comment]
@arsatis The PRs need to be added to the milestone v1.1 for them to be considered _in v1.1_.

**Comment by arsatis** [comment]
Oh alright, thanks for your reply!
