### ISSUE TITLE
Does the FXML file need to follow java coding standard?

### ISSUE THREAD

**Issue by TeoHoeKeat** [nus-cs2103-AY2021S2/forum#195]
When using the scene builder, the FXML is generated.
The FXML generated will violate the following coding standard
-  Imported classes should always be listed explicitly. (Generated FXML sometime use *) 
-  Line length should be no longer than 120 chars. (Generated FXML does not  wrap)

Do we need to manually fix the FXML every time the scene builder generates the FXML to meet the java coding standard?

**Comment by damithc** [comment]
No need @TeoHoeKeat
