### ISSUE TITLE
Java CI error

### ISSUE THREAD

**Issue by kieron560** [nus-cs2103-AY2021S2/forum#197]
For some reason, by Java CI keeps failing (build ubuntu-latest). This is even though for the developer guide, it is literally newline spaces that are present throughout the document, and it doesn't make  sense for there to be newlines in the iml file (or else the entire iml file should have newlines).

Not sure if its related but the checkstyle has no errors as well.

Any helps?

![image](https://user-images.githubusercontent.com/60651926/109545353-bb27d400-7b03-11eb-8805-a1e3a14263d7.png)

**Comment by tjtanjin** [comment]
The `no newline at EOF` error means you need to hit enter after the last line in `/src/main/main.iml` and `/src/test/test.iml` to insert a newline at EOF (end of file).

The warning about trailing whitespace means that at the end of the specified line, there is an extra space that needs to be removed.

Though on a side note, I noticed my team's tP does not have .iml files present under `/src/main` and `/src/test` :3

**Comment by kieron560** [comment]
Ok for some reason, deleting my iml files fixed everything haha
Thanks for the help regardless! 

I was confused about the errors listed above because it made no sense to me (the developer guide had trailing white spaces throughout the entire file for example, which are needed as they are used for formatting -- leaving newlines etc), but I'm glad it was solved!
