### ISSUE TITLE
Deletion of Branch after approved PR

### ISSUE THREAD

**Issue by ssoonwee** [nus-cs2103-AY2021S2/forum#198]
Hi guys,

I would like to check for the branches that we have in our local repository, are we allowed, or is it a good practice to delete those once the PRs are being approved by our teammates? From what I could foresee in the near future, there could be many overlapping branches that could contain outdated branches (for instance branch-Ui-Update, branch-Ui-Update1, branch-Ui1-Update) in our local repo as we further improve upon our codes and this format could vary from individuals. Would love to hear from you guys how you all approach this, thanks!

**Comment by tjtanjin** [comment]
Hello! I have been leaving the branches as they are and if there is a need to say `update-user-guide` again, I checkout to the branch, fetch and merge it with the upstream repository's master branch and then proceed on with the work to be done. 

I personally feel that for a branch, if one is certain that it will be a one-time update, it is alright to delete it (though for the purpose of this module I think they track our branches to see if we follow the forking workflow so better to leave it). 

On the other hand, if there will be constant updates with regards to a particular feature, I would keep the branch there and just be sure to update it before making any further changes. This has been working out for me but I'd like to hear alternatives as well :D

**Comment by damithc** [comment]
It's better to leave the branch intact as our scripts check for the existence of the branches at times, to verify if you are following the expected workflow.

**Comment by kouyk** [comment]
I think this [post](https://softwareengineering.stackexchange.com/questions/284903/reusing-a-merged-branch-good-practice) sums things up pretty well in terms of reusing branches. Reusing branches introduces needless complications that git intends to solve by make branching cheap and simple.

Following advice from [here](https://deepsource.io/blog/git-branch-naming-conventions/), and since we are recommended to use the issue tracker to manage task delegation as well, it feels much simpler to name a branch along the lines of `50-update-userguide-add-command`, where 50 is the issue number.

**Comment by ssoonwee** [comment]
Thanks guys for the feedback! 

@tjtanjin Yea I feel that is a good POV to see from and I think it is a good idea to keep the branch for future updates, in case we need to backtrack to them for future updates / potential bugs to isolate back there. 
@damithc Okay thanks prof for the clarification 👍
@kouyk Thanks for sharing! Yea the issue number labelling the branch certainly brings about some convenience in navigating back to the issue/feature that the branch is intended to solve.

**Comment by damithc** [comment]
To add: In practice, the more common practice is to delete the branch after merging, to avoid clutter. It is true that sometimes you need to track back to the commits of a specific branch. For that, the issue or PR number can be mentioned in the merge commit subject. See example below from AB3's past:
![image](https://user-images.githubusercontent.com/1673303/109631026-886ff100-7b80-11eb-84cf-3b99b6441a3a.png)

But we recommend keeping the branches in this module, purely for admin reasons.
