### ISSUE TITLE
Textbook: 'C++ to Java' minor typo

### ISSUE THREAD

**Issue by riyadh-h** [nus-cs2103-AY2021S2/forum#2]
Hello everyone!

Just wanted to highlight a possible typo while I was reading the CS2103/T online textbook.
In the _Polymorphism_ section of the _Supplementary: C++ to Java_ chapter, the ```Cat``` and ```Dog``` classes in the ```PetShelter``` example seem to miss the ```extends``` keyword.

While it is a small typo, the Java file will not compile due to the calls of the ```super``` constructor in both classes.

Thank you.

![dog](https://user-images.githubusercontent.com/69278589/104805805-a0c4c000-580d-11eb-9d1e-e927fcc09759.png)
![cat](https://user-images.githubusercontent.com/69278589/104805806-a1f5ed00-580d-11eb-9b91-61f0d95dc241.png)

**Comment by damithc** [comment]
Thanks for bringing this up @riyadh-h 
Are you referring to the following instance?
![image](https://user-images.githubusercontent.com/1673303/104808272-fd30db00-581f-11eb-8cd2-2d9e01ea646f.png)

**Comment by riyadh-h** [comment]
My pleasure, Prof. @damithc!
Yes. I believe it is the same case for ```Dog``` class too.

**Comment by damithc** [comment]
> Yes. I believe it is the same case for `Dog` class too.

In that case I think those two classes are not supposed to have `extends Animal` as this code is supposed to illustrate the situation _before applying polymorphism_? Or did I misunderstand your bug report?

**Comment by riyadh-h** [comment]
> In that case I think those two classes are not supposed to have extends Animal as this code is supposed to illustrate the situation before applying polymorphism? Or did I misunderstand your bug report?

Oh right, it could be. But if that was the case, then the ```super``` calls in the constructors of ```Cat``` and ```Dog``` would raise a compile-time error when trying to compile these classes.

**Comment by damithc** [comment]
> Oh right, it could be. But if that was the case, then the `super` calls in the constructors of `Cat` and `Dog` would raise a compile-time error when trying to compile these classes.

Indeed. Good catch @riyadh-h 
Fixed. Thanks again.
