### ISSUE TITLE
Request permission to use Apache HttpClient

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#200]
## Library

[Apache HttpClient](https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5.13)

## Purpose

Make API calls as part of app functionality.

## License

[Apache License 2.0](http://www.apache.org/licenses/LICENSE-2.0)

**Comment by damithc** [comment]
Approved.
