### ISSUE TITLE
The correct way to show a for-loop in UML diagram

### ISSUE THREAD

**Issue by JulietTeoh** [nus-cs2103-AY2021S2/forum#203]
I was reviewing the mistakes from my previous quizzes and I was confused as to why [i = 1 to 5] is an incorrect way to show a for-loop, and what would be a correct way to show a for-loop. 

<img width="1440" alt="Screenshot 2021-02-22 at 1 21 45 PM" src="https://user-images.githubusercontent.com/34907949/109900881-07753e80-7cd3-11eb-9fd4-49fb9a98f55a.png">

**Comment by tjtanjin** [comment]
Hello! If I remember correctly, the notation for a loop should use the word `loop` instead of `for`.

**Comment by JulietTeoh** [comment]
Oh I see! >_<
