### ISSUE TITLE
Bi-directional relationships, good, bad or doesn't matter?

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#205]
Hi guys, I was reading through the topics for this week and there was this **Bi-directional association** in the video, specifically:

Class `Box` has a `Lid` & Class `Lid` has a `Box`. (See screenshot below)

![image](https://user-images.githubusercontent.com/41845017/110048595-1ae3e080-7d8b-11eb-94b7-8fc155eba00e.png)

Another similar situation is that sometimes we may want a quick way to pass a reference of the "producer" to the thing that is being "produced". For a slightly different example, one may have a `BookStore` class that contains a method that returns a `Book` as follows:
```java
class BookStore {
    // other details omitted
    Book randomBook() {
         return new Book(this, "The Great Gatsby");
    }
}
```
So in this case, while a `BookStore` may not have a direct association to `Book`, `BookStore` has a dependency on `Book` (correct me if I am wrong here). And `Book` has a direct association to `BookStore`
So in this case, `BookStore` points to `Book` (via dependency) and `Book` points to `BookStore` (via association). (Reading the textbook tells me that association is really just dependency.)

In gist, my question is:
Does it matter that we have a design that involves a bi-directional relationship between objects?
- Both objects are associated with each other.
- One is associated with the other while the other depends on the former.
- Both objects are dependent on each other.

Is it a situation where this is unavoidable, or that we should try to avoid it as much as possible, or it simply does not matter at all in terms of having good software design?

**Comment by ong6** [comment]
Wow, what a coincidence, I was thinking of this question as well. 

My take on this would be that avoiding bi-directional relationships is better since if you decide to change one class down the line, having a bi-directional relationship would cause a lot of issues. 

Also, oftentimes I feel that a bi-direction relationship can be easily represented with a unidirectional as well. So unless bi-direction is strictly required, I feel there is no need to use them.

**Comment by damithc** [comment]
It's usually a case of pros and cons. So, what are the benefits of bi-directional associations?

**Comment by tlylt** [comment]
> It's usually a case of pros and cons. So, what are the benefits of bi-directional associations?

For cons:
- Cyclic dependencies make it hard to test as both classes need to know that the other class exists and is compilable.
- Changes in one class might break the other class.

For pros:
- The remotely plausible reason that I can think of is that having two smaller classes (even though in a bi-directional relationship) is at least better at closely modeling the interaction and real-life relationships between the two objects, as compared to one large class, hence more OOP?
- Convenient.

Any hints for the benefits of having bi-directional associations?

**Comment by YuFeng0930** [comment]
What I can think of is something like the example in Week 8 Topics. If two class they are partners of each other, no one is superior than the other. In that case, both of them should maintain a reference to each other and thus have a bi-directional association. This is just my point of view, correct me if I'm wrong.

**Comment by damithc** [comment]
As for cons, yes, it makes testing harder. Also, it increases the risk of inconsistencies in data. A bi-directional association needs to be managed as two separate mutual references between two objects. There is a chance that we update one reference but forget to update the other. This topics comes up later in the semester https://nus-cs2103-ay2021s2.github.io/website/se-book-adapted/chapters/errorHandling.html#enforcing-referential-integrity .

As for pros, bidirectional links can sometimes improve the efficiency of navigation and search. For example, suppose your system has Book objects and Author objects. Now suppose each Book object keeps references to the corresponding Author objects but Author objects don't keep references to the matching Book objects i.e., a uni-directional association
Now, to find all books authored by Author X, you'll have to search through all Book objects to find which ones are holding references to the Author object of X. But if the association was bi-directional, the Author object will have references to the relevant Book objects already.

That being said, the general best practice is to avoid bi-directional associations as much as possible unless there is a strong justification to have one.

**Comment by tlylt** [comment]
Ok got it. The part on referential-integrity is something that I didn't realize but could in fact be disastrous if that's not accounted for. 
Can I say that association classes are a good alternative to bi-directional associations?
pros:
- Remove the cyclic dependency.

cons:
- Less convenient and potentially require more checking to ensure updates are made to reflect the new state of the program.

**Comment by damithc** [comment]
> Can I say that association classes are a good alternative to bi-directional associations?

Association classes are used when you want to store extra information about an association. E.g., in the Book--Author example, if you want to store the percentage of the book that was written by different authors (in case of co-authored books).

Therefore, it is not strictly an alternative. For example, it doesn't increase the efficiency of search the way a bidirectional association does, unless the association class itself has bidirectional links with the two classes it manages, in which case we are back to the original situation except it's worse now as there are 3 objects and 4 links (compared to 2 links and 2 objects before).
```
Author ---> Authorship <--- Book
       <---            --->
```

**Comment by tlylt** [comment]
> ```
> Author ---> Authorship <--- Book
>        <---            --->
> ```

I have this in mind when I refer to the association classes:
![image](https://user-images.githubusercontent.com/41845017/110639034-323b2780-81ea-11eb-95d8-4edfb4d452e6.png)
Though this way the association class `Authorship` does not have a bi-directional relationship with the other two classes, I would imagine that adding, updating, and querying of the relationship between `Book` and `Author` will be troublesome... Thanks for the food for thought.
