### ISSUE TITLE
Issues regarding to TP progress

### ISSUE THREAD

**Issue by QY-H00** [nus-cs2103-AY2021S2/forum#206]
@damithc Hi Prof! I'm from T13-2. We have updated the DG and wrap up v1.1 milestone on March 4th before 12am. But the tp progress dashboard haven't been updated yet so far. Could you check it?

**Comment by damithc** [comment]
@QY-H00 As per GitHub some update has been done to the milestone v1.1 more recently. Anyway, it should turn green at the next update.
For DG, most likely one of the sections (NFRs?) that was supposed to be updated still remains same as the original. That item will turn green once there are updates to _all_ relevant sections. BTW, remove `{more to be added}` parts as well.

**Comment by QY-H00** [comment]
Noticed. Thank you prof!
