### ISSUE TITLE
UML: Does an enumeration need to display its enumeration values?

### ISSUE THREAD

**Issue by benedictkhoomw** [nus-cs2103-AY2021S2/forum#207]
![image](https://user-images.githubusercontent.com/77471078/110107407-cb7ece00-7de5-11eb-81ba-89647e352d80.png)

Assuming `<<enumeration>>` was added above `Status` enum name, would this then be correct? Or must the values WON and LOST also be included in an attached box below?

The textbook (as far as I know) does not comment on this.

Thanks.

**Comment by damithc** [comment]
@benedictkhoomw Can omit the values if not relevant to the purpose of the diagram.
