### ISSUE TITLE
UG/DG-updated still red?

### ISSUE THREAD

**Issue by rajobasu** [nus-cs2103-AY2021S2/forum#208]
My team has already made the necessary updates to the UG/DG/Readme files for the TP, yet on the dashboard it still shows as red. Any idea why? 
This is our [repo](https://github.com/AY2021S2-CS2103T-W12-2/tp).

**Comment by tjtanjin** [comment]
Hello! I am not entirely sure how updates to the documents are tracked but a quick glance across the UG/DG reveals quite a number of occurrences for `addressbook`. Even if this is not the cause for the dashboard showing red, it might be best to update them to be as relevant to your project as possible :D

**Comment by rajobasu** [comment]
Ah, we were thinking of doing this on an incremental basis, as in removing the ```addressbook``` references as and how we updated the different parts. But okay will do this and see if its better.

**Comment by damithc** [comment]
@rajobasu You can click on these (i) icon to find more information about what is required to turn each item green 
![image](https://user-images.githubusercontent.com/1673303/110193169-535beb00-7e6d-11eb-96ba-1b70671fb32f.png)
