### ISSUE TITLE
Request to use TestFX

### ISSUE THREAD

**Issue by samuelfangjw** [nus-cs2103-AY2021S2/forum#209]
## Library

[TestFX](https://github.com/TestFX/TestFX)

## Purpose

Automated testing of GUI

## License

[EUPL](https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12)

**Comment by damithc** [comment]
Approved.
Note that using TestFX is not GUIs is not trivial. You can use [AB4](https://github.com/se-edu/addressbook-level4) for guidance if you wish. AB4 has automated GUI testing using TestFX.
