### ISSUE TITLE
Do I need to change past commits to comply with the Git conventions?

### ISSUE THREAD

**Issue by mechastriker3** [nus-cs2103-AY2021S2/forum#21]
Hi Prof,
I was testing using git CLI to commit and did not follow the convention for a few of my commits locally. I've since changed to follow the conventions for subsequent commits, is that ok or do I have to update the commit messages and redo them?

**Comment by damithc** [comment]
It's fine @mechastriker3 Just follow the convention for future commits.

**Comment by mechastriker3** [comment]
Ok thanks prof!!

**Comment by richardcom** [comment]
Hi @mechastriker3 , just a gentle reminder that please remeber to close the issue if the problem has been solved. 😄

**Comment by mechastriker3** [comment]
Oh sorry my bad ! 😅 @richardcom

**Comment by richardcom** [comment]
> Oh sorry my bad ! 😅 @richardcom

haha no problem, thanks a lot!

**Comment by damithc** [comment]
Changed the issue subject to be more descriptive so that it's easier for others with the same doubt to locate it.
