### ISSUE TITLE
UML: When can we omit the instance name?

### ISSUE THREAD

**Issue by nicoleang09** [nus-cs2103-AY2021S2/forum#214]
<img src=https://user-images.githubusercontent.com/60417365/110276526-40cce780-800e-11eb-86da-c8fd78f466c6.png width="550px">

I would like to clarify when the instance name can be omitted in object diagrams. In the textbook, it states that if the instance name is omitted, the object instance can be interpreted as an unnamed instance. In this question, however, the Member instances are all named, yet their instance names were omitted.

Does this mean that in UML object diagrams, the instance names are always optional, regardless of whether the instance is named or unnamed?

**Comment by damithc** [comment]
Good question @nicoleang09 
_unnamed_ here doesn't mean _no name given in the **code**_. It means, _no name given in the **diagram**_. Which means it is entirely up to the person drawing the diagram, and **depends on the purpose of the diagram**. For example, if the diagram is used to explain some design decision and the explanation doesn't need to refer to specific Member objects, it may be OK to omit the object names.
That being said, exam questions sometimes has an instruction 'show all known details' in which case you should show the object name if the code already specifies a name.

**Comment by rajobasu** [comment]
Just to add on maybe but one example when it definitely won’t have a name : **lambda functions/Anonymous Inner Classes!**
If we want to draw them, we can’t really associate names right?

**Comment by nicoleang09** [comment]
@damithc I see, thanks for the clarification!
