### ISSUE TITLE
CSS not working in fxml format

### ISSUE THREAD

**Issue by banchiang** [nus-cs2103-AY2021S2/forum#215]
Hi so im trying out css to make fxml format look neater. I'm looking at how the _**mainwindow.fxml**_ does it with the **_darktheme.css_** and below is my css code:
<img width="315" alt="css" src="https://user-images.githubusercontent.com/72375578/110276350-e6338b80-800d-11eb-8546-dae1fedba002.png">

Here is the code in my fxml, basically im trying to replicate `text:"Sat"` properties to `text:"Sun"` with css (styleclass):
<img width="666" alt="label" src="https://user-images.githubusercontent.com/72375578/110278849-031e8d80-8013-11eb-8eef-1a2e398d202c.png">

I have also added the css at the start of the fxml file
<img width="445" alt="css_added" src="https://user-images.githubusercontent.com/72375578/110279014-55f84500-8013-11eb-97a7-03998d189db8.png">

However, the Ui does not register the css style 
<img width="260" alt="calendar_ui" src="https://user-images.githubusercontent.com/72375578/110279145-8dff8800-8013-11eb-9047-f80452e5bb39.png">

the `text:sun` is not in red and not of the same font and size as dicpicted in the `text:sat`.
Anyone knows what is the issue here? Is it because there is no presense of ids? Thank you in advance :) !

**Comment by samuelfangjw** [comment]
Try changing `-fx-font-fill` to `-fx-text-fill`.

**Comment by samuelfangjw** [comment]
I tried the following with your tp branch and it seems to fix your issue.
```
.weekend {
    -fx-font-size: 16.0;
    -fx-font-family: "Abyssinica SIL";
    -fx-text-fill: red;
}
```

<img width="267" alt="Screenshot 2021-03-08 at 2 04 29 PM" src="https://user-images.githubusercontent.com/60355570/110281199-34995800-8017-11eb-84a9-29e527bcde50.png">

**Comment by banchiang** [comment]
Oh alright thanks! @samuelfangjw :D
