### ISSUE TITLE
Java CI check fail (macOS latest)

### ISSUE THREAD

**Issue by banchiang** [nus-cs2103-AY2021S2/forum#217]
Hi I have imported the javafx media as dependencies, and in my pull request the checks were alright.
![build gradle](https://user-images.githubusercontent.com/72375578/110309672-9a4c0b00-803c-11eb-9630-8c8cda85827e.png)

However, when I merge the pull request, a check (macOS latest) failed and I'm not sure how do I rectify this problem. (I did not modify the build.gradle other than the 3 lines I've inserted).  Anyone knows how to solve this issue? Thanks in advance :D
![build error](https://user-images.githubusercontent.com/72375578/110309692-9f10bf00-803c-11eb-8e7d-6cc418fbe40a.png)

**Comment by damithc** [comment]
Could be a temporary problem with the download locations of dependencies. Can try rerunning the CI for the merge commit again.

**Comment by banchiang** [comment]
Oh yes it works now thanks prof! @damithc
