### ISSUE TITLE
checkStyle violations - Ordering of import statements

### ISSUE THREAD

**Issue by maikongeh** [nus-cs2103-AY2021S2/forum#218]
I'm encountering many checkstyle errors mainly because of ordering of import statements. When i try to reorder them, intelliJ is automatically putting it back into the incorrect order. Has anyone encountered this same issue with intelliJ and knows how to resolve it?

**Comment by w2vgd** [comment]
You may like to refer to this [guide](https://se-education.org/guides/tutorials/intellijCodeStyle.html#tweak-import-order)
