### ISSUE TITLE
Person.equals() doesn't work properly after amendments

### ISSUE THREAD

**Issue by fairyinabottle4** [nus-cs2103-AY2021S2/forum#219]
Hi all, I changed the `@Override equals()` method in Person.java, after adding several new fields to the class. The purpose was to update the `equals()` method so that it will account for the new fields when comparing instances. However, that also causes some of the existing tests to not work, and I really don't understand why. 

<img width="900" alt="err" src="https://user-images.githubusercontent.com/46418515/110357016-c9cb3980-8075-11eb-9cc7-7eac7b40db9f.PNG">

The image here shows what happens. Line 150 is `assertEquals(expectedModel, model);`

I ran in debug mode and I found that the fields of the Person instance were the same for both `expectedModel` and `model`. 

<img width="700" alt="is same" src="https://user-images.githubusercontent.com/46418515/110357953-d00de580-8076-11eb-966e-daa7bbaac06a.PNG">

So I am really not sure why this is happening, especially since this didn't happen when I didn't update the `equals()` method, even after I had added the new fields. 

Appreciate any and all help. Thank you.

**Comment by tjtanjin** [comment]
Hello! Perhaps it might help to share a quick screenshot of the section of the code you modified :D On a side note, you may also want to remove the new fields from `equals` and then try again by adding one new field for comparison every time. This should at least help further narrow down the problem :D

**Comment by fairyinabottle4** [comment]
For some reason my teammate didn't face this issue, so I'll close this for now...
