### ISSUE TITLE
A question about committing the files

### ISSUE THREAD

**Issue by skinnychenpi** [nus-cs2103-AY2021S2/forum#22]
Hi Prof, I'm wondering whether we need to commit and tag the A-TextUiTesting to our repo because I only run the test on my laptop and there is no change of my java code? Another question is that as long as we push all the codes to our own forked repo, then will the project be regarded as done or do we need anything else?

**Comment by damithc** [comment]
> Hi Prof, I'm wondering whether we need to commit and tag the A-TextUiTesting to our repo because I only run the test on my laptop and there is no change of my java code?

@skinnychenpi Files used for testing are part of the project, for example, the expected.txt, and need to committed/pushed. Otherwise anyone cloning your project will not be able to run the tests.


> Another question is that as long as we push all the codes to our own forked repo, then will the project be regarded as done or do we need anything else?

Yes, that's all. Our scripts will pick the code from your fork.

**Comment by skinnychenpi** [comment]
> > Hi Prof, I'm wondering whether we need to commit and tag the A-TextUiTesting to our repo because I only run the test on my laptop and there is no change of my java code?
> 
> @skinnychenpi Files used for testing are part of the project, for example, the expected.txt, and need to committed/pushed. Otherwise anyone cloning your project will not be able to run the tests.
> 
> > Another question is that as long as we push all the codes to our own forked repo, then will the project be regarded as done or do we need anything else?
> 
> Yes, that's all. Our scripts will pick the code from your fork.

Thank you Prof!
