### ISSUE TITLE
UserGuideAdapted not updating on tP dashboard

### ISSUE THREAD

**Issue by Stratostorm** [nus-cs2103-AY2021S2/forum#222]
References to AB3 were replaced in the UserGuide and initial changes were made but it is not being updated on the tP dashboard. Link to the User Guide shown is: https://ay2021s2-cs2103t-w13-3.github.io/tp/UserGuide.html

**Comment by damithc** [comment]
@Stratostorm Looks like some of it still remain. e.g., this link points to se-edu/addressbook-level3
![image](https://user-images.githubusercontent.com/1673303/110580742-36dced00-81a4-11eb-9152-a5042a32f2e9.png)

**Comment by Stratostorm** [comment]
Ah, thanks prof!
