### ISSUE TITLE
Creating new Java file, filename sometimes not recognized in Intellij 

### ISSUE THREAD

**Issue by figo2127** [nus-cs2103-AY2021S2/forum#223]
![image](https://user-images.githubusercontent.com/61351392/110592078-cab6b500-81b4-11eb-90ec-9f934b662725.png)
Above is when I name the file Find.java, everything works fine.

![image](https://user-images.githubusercontent.com/61351392/110592312-149f9b00-81b5-11eb-96ba-d2a7c4b96b1a.png)
But now when I changed it to camelcase naming, the java file recognization breaks.

In case this helps:
![image](https://user-images.githubusercontent.com/61351392/110592540-647e6200-81b5-11eb-9679-64dd55396896.png)
![image](https://user-images.githubusercontent.com/61351392/110592665-8546b780-81b5-11eb-8a92-7afe08c12071.png)
![image](https://user-images.githubusercontent.com/61351392/110592680-8a0b6b80-81b5-11eb-94da-08a95dd0b49c.png)

After doing some research, I tried changing the sources root but to no avail. Anyone knows what's up with this? Thanks in advance!!

**Comment by damithc** [comment]
@figo2127 did you manage to resolve it? Based on the lack of response, seems like others haven't faced a similar problem. You can also try cloning the project to another location and setting up Intellij for it again to see if that helps.

**Comment by figo2127** [comment]
@damithc Hi prof. No I tried cloning & clearing cache and restarting but none of that works. My TA also helped me but it still does not work. But overall it doesn't affect running tests and the program so I think its fine?

**Comment by damithc** [comment]
@figo2127 One possibility is the rogue setting is at the IDE level, which means it affects all your projects. You can test that hypothesis by uninstalling  the IDE (including the settings) and reinstalling it -- but that's a drastic measure. So, can stay with the status quo if it doesn't hamper you much.
