### ISSUE TITLE
Java CI Validate Gradle Wrapper Test Fail

### ISSUE THREAD

**Issue by jxrrelo** [nus-cs2103-AY2021S2/forum#227]
Hi does anyone know what is causing this "validate gradle wrapper" test to fail? I have been asking around and nobody seems to experience this before. Also, none of my team members are facing this issue. This happened when I pulled the latest from the upstream repo, branched off to make changes, and then pushed the changes to create the new pull request. I have followed the URL as provided in the error message but didn't manage to fix it. Would appreciate if anyone could help, thanks!

![IMAGE 2021-03-11 16:00:30](https://user-images.githubusercontent.com/17845521/110754532-e8525000-8282-11eb-8bd3-a2adf5c49029.jpg)

**Comment by damithc** [comment]
@jxrrelo provide the link to the PR that is causing this CI failure as well. The PR diff might contain clues as to why the failure happens.

**Comment by jxrrelo** [comment]
@damithc Here is the link to the PR.

https://github.com/AY2021S2-CS2103T-W14-2/tp/pull/55/checks?check_run_id=2084376976

**Comment by damithc** [comment]
Not a solution but your PR seems to contain lot of unrelated stuff? Perhaps close it and create another clean PR (containing only the intended changes) to see if that makes a difference?
You can also rerunning the CI workflow, in case it was a temporary problem.

**Comment by damithc** [comment]
Oh wait, you _did_ actually add a new gradle-wrapper.jar in this PR. How come? All the more reason to close this PR and create a clean PR. Branch off from the latest tip of the master branch and modify only what is necessary for your PR.

**Comment by jxrrelo** [comment]
@damithc Yup that was the issue. Overlooked on the clutter within my PR. Solution as mentioned above works. After I created a new clean PR, the CI tests cleared without any issues. Thanks Prof.
