### ISSUE TITLE
Request for usage of 3rd party library FuzzyWuzzy

### ISSUE THREAD

**Issue by darkdestry-t** [nus-cs2103-AY2021S2/forum#228]
## Library

[FuzzyWuzzy](https://github.com/xdrop/fuzzywuzzy)

## Purpose

Fuzzy string matching for string searches

## License

GPL-2.0 License
[LICENCE](https://github.com/xdrop/fuzzywuzzy/blob/master/LICENSE)

**Comment by damithc** [comment]
Approved.
