### ISSUE TITLE
Source of Logs

### ISSUE THREAD

**Issue by colintkn** [nus-cs2103-AY2021S2/forum#229]
![image](https://user-images.githubusercontent.com/65516485/110889496-3326a300-8329-11eb-982d-bc335d4d2552.png)

Everytime I gradle run, I get these log files. What is triggering these logs? Is it because of config.json

**Comment by w2vgd** [comment]
They are triggered by such logging statements in the code:
![image](https://user-images.githubusercontent.com/65358857/110891410-e5139e80-832c-11eb-8a28-0f0bab463474.png)

Everytime you start the app, or run a command, logging output is printed to such files for logging purposes (think of it as the black box for recording what happened when you are using the app). Every single run of the app will write to such files, and if a single file exceeds 5MB, a new file will be created to continue to record the logging output, for a maximum of up to 5 files. (Not sure what happens after 5 files though, but my guess is it will just not record anything anymore). 

You can delete the log file after every run if you like.

If you will like to know where the code for producing such a file comes from, it comes from `LogsCenter.java`

**Comment by damithc** [comment]
> Not sure what happens after 5 files though, but my guess is it will just not record anything anymore

This is configurable. IIRC, the current configuration is to keep the most recent 5 files i.e., when it reaches the limit, the oldest file will be deleted to make room for the next log file.

**Comment by colintkn** [comment]
Interesting! thanks.
