### ISSUE TITLE
LSP: Example used in [W9.5] Design principles

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#230]
The `BankSystem` expects `Account` to throw an exception if `i` is not within the range of 0 to 100 (both exclusive). While B is definitely correct and C is definitely wrong, I feel uncomfortable saying that A follows LSP.
- if `i` is 100, `BankSystem` expects `Account` to throw an exception, but `AccountTypeA` will not.
- Perhaps an alternative example will be more suitable? 
  - method `Boolean hasAccount(int i)` will return true if  0 < i < 1000, return  false otherwise. 
  - `AccountTypeA` returns true if  0 < i < 1000, false otherwise, hence does not follow LSP

![image](https://user-images.githubusercontent.com/41845017/111022939-01890700-8411-11eb-938f-9302261954b8.png)

**Comment by damithc** [comment]
Good point @tlylt 
The contract of the getAccount method is supposed to be 'works as long as 0 < i <100'  i.e., 0 < i < 100 is a precondition. If the precondition is not met, the behavior is undefined. Thus, as per LSP, the sub-class should not tighten the range of i but is allowed to widen it.

But the way the example is presented (my fault) gives the impression that the method also promises a certain behavior when i is outside the specified range as if checking the validity of the parameter is part of the method's deliverables. This takes i into the territory of post-conditions as well. As LSP doesn't allow the sub-class to loosen post-conditions, AccountTypeA doesn't follow LSP. I'll have to tweak the example next time.
