### ISSUE TITLE
Typo in [w9.2] activity diagram > UML Activity Diagrams → Basic Notation → Alternate Paths

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#232]
Under Week 9 topics
 - 9.2 activity diagram > UML  Activity Diagrams → Basic Notation → Alternate Paths
    - Exercises > Which activity diagrams are correct?
      - Which of these activity diagrams use the correct UML notation?
Last option should be `vi`
![image](https://user-images.githubusercontent.com/41845017/111027762-4458d800-842d-11eb-8d9e-72440faab530.png)

**Comment by damithc** [comment]
Thanks for the bug report @tlylt 
Will fix in the next update.
