### ISSUE TITLE
Wrong options set for Week 9 Quiz - Part 1 Q12 Some books ...

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#233]
I believe as prof mentioned... Source code is not a book but a movie, so the last option should not be set as correct?
(albeit source code is a movie that I would recommend to anyone)
![image](https://user-images.githubusercontent.com/41845017/111028009-baaa0a00-842e-11eb-9e0c-60039d6f4faf.png)

**Comment by damithc** [comment]
Good catch @tlylt . I've corrected it. Thanks for the bug report.
