### ISSUE TITLE
Graphics Device initialization failed

### ISSUE THREAD

**Issue by maikongeh** [nus-cs2103-AY2021S2/forum#237]
I am getting this error when i run my tp from the main file

java 11.0.6

Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found

Anyone has a similar problem/ knows how to resolve this issue?

**Comment by damithc** [comment]
This seems relevant https://github.com/nus-cs2103-AY2021S2/forum/issues/173
