### ISSUE TITLE
Classes appearing red, commands not found 

### ISSUE THREAD

**Issue by mesyeux** [nus-cs2103-AY2021S2/forum#238]
Previously re-cloned my own tp project, but after that I encountered these problems. The import statements are appearing red and so are the classes in the code as well as their respective methods, even though they exist. I keep getting the 'Cannot resolve symbol 'xx'' error. Would appreciate any help, thank you in advance!

![errororor2](https://user-images.githubusercontent.com/70282468/111249549-d851bc00-8646-11eb-9625-affff46f546b.jpg)
![errororor](https://user-images.githubusercontent.com/70282468/111249554-da1b7f80-8646-11eb-9d28-17cbd62a2796.jpg)
![errororor3](https://user-images.githubusercontent.com/70282468/111249710-19e26700-8647-11eb-9977-34367d04a776.jpg)

**Comment by kouyk** [comment]
You might want to try File > Invalidate cache and restart.  ---- On Tue, 16 Mar 2021 11:04:22 +0800  ***@***.***  wrote ----
Previously re-cloned my own tp project, but after that I encountered these problems. The import statements are appearing red and so are the classes in the code as well as their respective methods, even though they exist. I keep getting the 'Cannot resolve symbol 'xx'' error. Would appreciate any help, thank you in advance!

**Comment by mesyeux** [comment]
Thank you so much, that solved the problem!
