### ISSUE TITLE
Can we change the UserGuide format? 

### ISSUE THREAD

**Issue by ong6** [nus-cs2103-AY2021S2/forum#239]
As the title suggests, can we change the format of our user guide to make it look better? Or should we follow AB3's format?

**Comment by damithc** [comment]
@ong6 If you mean the way the content is structured and shown, yes you can change the format.
But if you mean the way it is stored in source code, you should use an editing-friendly textual format such as Markdown (i.e., the current format)

**Comment by ong6** [comment]
Thanks, prof! I meant the content structure so this answers my question!
