### ISSUE TITLE
What do we need to tag?

### ISSUE THREAD

**Issue by nighoggDatatype** [nus-cs2103-AY2021S2/forum#24]
I understand that Level-1, Level-2, Level-3, Level-4, A-TextUiTesting, Level-5, Level-6, A-Enums are all things we need to have tags for, with A-Enums being optional. However, if we do the extensions: A-Classes, A-Inheritance, A-Exceptions, A-Collections, do we need to tag them to get credit?

**Comment by damithc** [comment]
Yes @nighoggDatatype , go ahead and add those tags as well.

**Comment by ming-00** [comment]
Hi Prof, what if we implemented the extensions directly in each level so they are in the same commit?

**Comment by damithc** [comment]
> Hi Prof, what if we implemented the extensions directly in each level so they are in the same commit?

@ming-00 You can add multiple tags to the same commit.

**Comment by vevek** [comment]
Hi Prof @damithc, what if we had used enums earlier than the given order? 

In the instructions it states "Implement the following increments in the given order." where the given order was "Level-1, Level-2, Level-3, Level-4, A-TextUiTesting, Level-5, Level-6, A-Enums". However in my case it made sense to use enums before Level-6. In this case does the tag ordering matter?

**Comment by damithc** [comment]
> In the instructions it states "Implement the following increments in the given order." where the given order was "Level-1, Level-2, Level-3, Level-4, A-TextUiTesting, Level-5, Level-6, A-Enums". However in my case it made sense to use enums before Level-6. In this case does the tag ordering matter?

The tag ordering doesn't matter. As long as the tag is found in _any_ commit, we assume the corresponding work has been done. In this context, we use tags simply as self-declarations of progress. We don't use it for any other purpose.

**Comment by vevek** [comment]
Thank you Prof @damithc
