### ISSUE TITLE
Cannot scroll down in the search box of CS2103T website

### ISSUE THREAD

**Issue by QY-H00** [nus-cs2103-AY2021S2/forum#245]
When searching something in the search box of the top right corner in the website, there is many search results going beyond the scope of the screen. When I scroll down and want to see them, only web pages scroll down but the search results display bar does not. Is it an issue of the website?

**Comment by damithc** [comment]
Thanks for reporting this @QY-H00 
This is a known issue cased by the underlying generator tool (i.e., MarkBind) used by the website. We are waiting for it to be fixed in MarkBind.
