### ISSUE TITLE
Can't download exe from CATcher on macos. CATcher not reflected in system preferences

### ISSUE THREAD

**Issue by maikongeh** [nus-cs2103-AY2021S2/forum#246]
I can't seem to download the executable file from CATcher3.3.7. When i download the zip file and manually npm install and start, i'm not sure how to access the cs2013T session.

<img width="761" alt="Screenshot 2021-03-22 at 3 15 54 PM" src="https://user-images.githubusercontent.com/67374087/111953400-8535a880-8b21-11eb-9707-ec4b2465d1f9.png">

**Comment by damithc** [comment]
exe is for Windows. For Mac, I think it's the .dmg file you need to use instead.
