### ISSUE TITLE
Architecture diagram of AB3

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#248]
Why is there an arrow from the `Ui` component to the `Model` component? Does the arrow mean a dependency/association or does it mean `Ui` knows of `Model`?
![image](https://user-images.githubusercontent.com/65358857/112151408-2739bb80-8c1c-11eb-903e-697235ff51dd.png)

But as seen from the code, `Ui` only keeps a reference to `Logic` and does not know of `Model`?
![image](https://user-images.githubusercontent.com/65358857/112151536-4c2e2e80-8c1c-11eb-92f4-559838133136.png)

**Comment by damithc** [comment]
Aren't some GUI components linked to the Model so that the GUI updates automatically when the model is changed?

**Comment by w2vgd** [comment]
> Aren't some GUI components linked to the Model so that the GUI updates automatically when the model is changed?

Ohh, I see. Thanks for the clarification!
