### ISSUE TITLE
PlantUML: How to draw a sequence diagram ref frame properly?

### ISSUE THREAD

**Issue by benedictkhoomw** [nus-cs2103-AY2021S2/forum#250]
Hello, I noticed that ref frames [as shown in the textbook](https://nus-cs2103-ay2021s2.github.io/website/schedule/week6/topics.html#tools-uml-sequence-diagrams-reference-frames) have their captions placed beside the `ref` label in the top-left, rather than below the label. Here is a screenshot of the relevant portion of the textbook.

![image](https://user-images.githubusercontent.com/77471078/112240778-ee353180-8c83-11eb-95b4-fe179ce7c37a.png)

However, I have searched the PlantUML [language reference](http://plantuml.com/guide) and [searched around](https://forum.plantuml.net/6867/sequence-diagram-sub-diagrams) but cannot find out how to position the caption next to the `ref` label. The sources I found only show how to place it underneath. Here is a screenshot of the reference frame section of the PlantUML language reference (page 16).

![image](https://user-images.githubusercontent.com/77471078/112240498-6818eb00-8c83-11eb-8203-e30aad0ced67.png)

Thank you for your time.

**Comment by richardcom** [comment]
Hi @benedictkhoomw 
I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems).

Actually I think it is okay for the default position of the caption in plantUML. Below is a sequence diagram that I have seen previously.

![image](https://user-images.githubusercontent.com/65701775/112260645-4892ba00-8ca5-11eb-8385-42688457c0aa.png)

**Comment by damithc** [comment]
> Actually I think it is okay for the default position of the caption in plantUML.

Yes, the PlantUML default is acceptable for this case.

**Comment by benedictkhoomw** [comment]
Ah okay, thank you both.
