### ISSUE TITLE
Developer Guide: Should we write the name of the author for each section? 

### ISSUE THREAD

**Issue by ong6** [nus-cs2103-AY2021S2/forum#251]
This question arose as some of the developer guides from the last sem had their names written beside the parts they wrote.

**Comment by damithc** [comment]
There is no such requirement from CS2103/T side.

**Comment by ong6** [comment]
Thanks prof, I'll leave this post open (for more visibility) in case anyone else was wondering.

**Comment by damithc** [comment]
OK to close @ong6. Others should know they need to look among closed issues when they are looking for something.
