### ISSUE TITLE
Overlapping arrowheads in class diagram

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#253]
![image](https://user-images.githubusercontent.com/65358857/112295056-7dffcd80-8cce-11eb-8b09-de3c70a7bc8c.png)

Hi, I have been trying to update the `Ui` class diagram for my team's project, but I can't seem to solve the issue of the overlapping arrowheads. Is the class diagram above acceptable or is there any way to make the lines more spread out and nicer? Appreciate any help. Thanks!

**Comment by damithc** [comment]
Yes, it should be fine, as it is limitation of PlantUML.

**Comment by w2vgd** [comment]
👍
