### ISSUE TITLE
Can Activity Diagrams have multiple end nodes?

### ISSUE THREAD

**Issue by DrWala** [nus-cs2103-AY2021S2/forum#254]
Can Activity Diagrams have multiple end nodes?

These folks say yes: [https://softwareengineering.stackexchange.com/a/215137](https://softwareengineering.stackexchange.com/a/215137)

However, the textbook neither explicitly says we can, nor does it say we cannot. Does anyone have any ideas?

**Comment by damithc** [comment]
Yes, can. You will encounter an example in this week's tutorial.
