### ISSUE TITLE
Updating contributions in DG

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#255]
Hi, just a quick question, are we supposed to update the contributions of each team member in the DG directly (as stated in the Project tab), or are we supposed to update the contributions in the `{github-username}.md` file of each member (which will be reflected in the `AboutUs` rather than the DG?

![image](https://user-images.githubusercontent.com/65358857/112298583-1e0b2600-8cd2-11eb-8353-39c8a365e3d9.png)

**Comment by damithc** [comment]
This item is about the DG. So, 
1. update the DG to match the current or target end design/implementation
2. when you do the above, each person should update the areas they worked on

**Comment by w2vgd** [comment]
Ohh, I see. Thank you!
