### ISSUE TITLE
Clarification on OS specific installations

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#256]
Hello!

Our application has unicode characters which shows up fine on mac/windows but require the additional installation below to show up on ubuntu:
`apt-get install ttf-ancient-fonts`

May I clarify if it is alright to include this as an instruction specific to ubuntu users?

Thank You!

**Comment by damithc** [comment]
Preferred not to impose additional burdens on users, especially because this can affect the tester performance during the PE. Can the app do without this Unicode characters or automatically use an alternative if the OS doesn't support it?

**Comment by tjtanjin** [comment]
Our team will explore alternatives to using unicode characters. Thank you for the clarification!

**Comment by damithc** [comment]
Another option you can consider is to auto-detect Ubuntu and pop up clear instructions to the user on what to do, provided the installation is painless and quick. This at least avoids the situation where the tester doesn't realize some additional installation is required and wastes time reporting the behavior as a bug.
