### ISSUE TITLE
Logic class diagram of AB3

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#257]
Should there be an association from the `LogicManager` to `Storage` as well? Or is it omitted for brevity? Just wondering when is it okay to omit stuff and when we should include.

![image](https://user-images.githubusercontent.com/65358857/112344689-4f4e1b00-8cff-11eb-82dc-4b913f10289f.png)

**Comment by damithc** [comment]
If there is an association, it's best to include it here (given a similar association with the Model is included already -- no good reason for one to be included and the other to be omitted). If confirmed, please report a bug at https://github.com/se-edu/addressbook-level3/issues

**Comment by w2vgd** [comment]
> If there is an association, it's best to include it here (given a similar association with the Model is included already -- no good reason for one to be included and the other to be omitted). If confirmed, please report a bug at https://github.com/se-edu/addressbook-level3/issues

Done!

**Comment by damithc** [comment]
Fixed in https://github.com/nus-cs2103-AY2021S2/tp/commit/571faba8cb1e92d9e2bb2fbc4ce774bc32ba15b1
Thanks @w2vgd for the fix

![image](https://user-images.githubusercontent.com/1673303/113089583-80a47a80-921a-11eb-8a4c-d474b4f668ee.png)
