### ISSUE TITLE
Recommendations for sequence diagrams

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#258]
Hi, will like to seek advice for how to approach this issue. So, I am trying to draw the sequence diagram for an add property command, but since the input command string is kind of long (have already omitted optional fields), if I were to put the whole string in the sequence diagram, then the diagram will be very long in width. Hence, I am not sure what is the best way to label it in this case. I have thought that maybe I can omit all the parameters of the functions (such as the `parseCommand` label below), but this solution seems less than ideal, as it does not help to illustrate the different input string parameters of the respective functions. Hope to get some recommendations here on how to approach this.

![image](https://user-images.githubusercontent.com/65358857/112363219-39952180-8d10-11eb-9fec-3198a5b249ed.png)

**Comment by Prabhakaran-Gokul** [comment]
Not sure if it’s the right way but I split my command into multiple lines!

**Comment by damithc** [comment]
other options:
* Specify the parameter separately, as a UML note
* Specify the parameter outside of the diagram, in the document text

**Comment by w2vgd** [comment]
Hi, may I ask if this diagram is acceptable? Is the `addProperty(property)` part alright because `property` is not actually defined but the `Property` class is too low-level to show in this sequence diagram.

![image](https://user-images.githubusercontent.com/65358857/112438737-36874900-8d83-11eb-9c20-b2b1c8a3af39.png)

**Comment by damithc** [comment]
> Is the `addProperty(property)` part alright because `property` is not actually defined but the `Property` class is too low-level to show in this sequence diagram.

Should be fine if it doesn't hamper the reader from understanding the explanation this diagram is part of.

**Comment by w2vgd** [comment]
Ok! Thanks for the help @Prabhakaran-Gokul and @damithc.
