### ISSUE TITLE
Code quality: assertions

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#259]
Hi, just curious if `requireNonNull` methods are counted for assertions? And do the automated scripts pick only `assert` keywords to be counted as assertions or are other forms such as `requireNonNull`, `requireAllNonNull` and `AssertionError` counted as well?

![image](https://user-images.githubusercontent.com/65358857/112506014-4ecd8700-8dc8-11eb-9af8-0974e664f8ba.png)

**Comment by damithc** [comment]
Not at the moment. I'll add them in the next update.

**Comment by w2vgd** [comment]
Are we recommended to use `requireNonNull` or should we use `assert` for the script?

**Comment by damithc** [comment]
> Are we recommended to use `requireNonNull` or should we use `assert` for the script?

You can use whichever that fits. Both will be picked up by the script from now on.

**Comment by w2vgd** [comment]
Thanks Prof @damithc.
