### ISSUE TITLE
Terminal shows different things IntelliJ vs Ubuntu

### ISSUE THREAD

**Issue by nowknowing** [nus-cs2103-AY2021S2/forum#26]
I've been running my code on IntelliJ, which gives rise to a bug I cannot solve. (only the 1st line includes the desired effect of "head: " appended at the front.
On running my code in Ubuntu, after compiling and running "java Duke", the result it different; it works.
Any idea why this happens?
Does this mean there's something wrong with the IntelliJ terminal?

I am running respond("hi\n" + "bye\n").
```java
public static void respond(String response) {
        System.out.print(Arrays.stream(response.split(System.lineSeparator())).map(line -> "head: " + line).collect(Collectors.joining("\n")));
    }
```
I'm trying to format my responses, with this method respond(String response),
which is intended to help edit any string to the format I want, so it looks better.

![image](https://user-images.githubusercontent.com/49021362/105304698-ccbdb800-5bf6-11eb-9723-0acbfb9c4df2.png)
VS
![image](https://user-images.githubusercontent.com/49021362/105305624-04c4fb00-5bf7-11eb-926e-3b6b4040ab8f.png)

Thank you

**Comment by georgepwhuang** [comment]
I think it may have to do with `System.lineSeparator()` as line separators differ from operating system to operating system. You should be able to toggle the lineSeparator in IntelliJ on the bottom tool bar from a label that says either LF/CR/CRLF. But it might be better to not use `System.lineSeparator()`. 

This [post](https://stackoverflow.com/questions/49340617/difference-between-n-and-system-lineseparator) might help.

**Comment by nowknowing** [comment]
Thank you. Yes that seems to be the case. Hadn't noticed the descriptions when toggled.
I will be using "\n" instead.

**Comment by damithc** [comment]
Thanks @georgepwhuang for the help 💯
