### ISSUE TITLE
TP dashboard not updated progress

### ISSUE THREAD

**Issue by Eriksen2411** [nus-cs2103-AY2021S2/forum#260]
I have followed the instruction on smoked-tested catcher and done this task from Wednesday. However, the TP dashboard did not update this task done for me.
![image](https://user-images.githubusercontent.com/65208242/112567637-266f7800-8e1c-11eb-8852-b26a9d19a181.png)

**Comment by damithc** [comment]
@Eriksen2411 Did you create the bug reports using CATcher? It won't count if you create the bug reports using the GitHub interface.

**Comment by Eriksen2411** [comment]
Yes, Prof. I have created bugs using GitHub interface, CATcher web and CATcher app also.

**Comment by damithc** [comment]
Got it. Will look into it and get back to you soon.

**Comment by damithc** [comment]
@Eriksen2411 Can you create one more bug report using either version of CATcher?

**Comment by Eriksen2411** [comment]
@damithc Yes Prof. I just created one more bug report.

**Comment by damithc** [comment]
@Eriksen2411 It's because your issue tracker doesn't have an issue at number 1. You probably deleted the first issue? In any case, it should be marked as done in the next update.

**Comment by Eriksen2411** [comment]
Tks Prof @damithc. It is marked as done now. Yes, I deleted the first issue because it was not created with catcher. Next time I will pay more attention to that point.
