### ISSUE TITLE
Equivalence Partitions

### ISSUE THREAD

**Issue by creativequotient** [nus-cs2103-AY2021S2/forum#264]
What constitutes the domain on inputs when considering equivalence partitions (EPs)?

For example, lets take the following function as an example

```
def String echo(String s) { return s; }
```

Then there are probably only a few partitioning for strings of different lengths, maybe made up of different characters/encodings, etc. 

But what about things that are not strings? Do those form their on EPs? For instance, this function should throw an exception if we pass in doubles, integers, arrays, etc. Do those also count as EPs?

**Comment by damithc** [comment]
Related: I discussed a EP example in the lecture y'day, which answers some of the questions raised.
