### ISSUE TITLE
Use of `mailto` links

### ISSUE THREAD

**Issue by riyadh-h** [nus-cs2103-AY2021S2/forum#265]
Hello there!

For my team's tP, we're implementing some feature that uses `mailto` links. These links would invoke the user's OS default mail client (e.g., Outlook, Thunderbird, etc.) to send an email, which is technically using external software.  In case the user does not have a default mail client assigned, the user's web browser opens an empty new window.

However, neither does the application require a particular mail client to be installed in the OS, nor does it require the use of third-party Java libraries.

Is it okay to have the aforementioned behaviour in our application? More specifically, does it violate the **[`Constraint-External-Software`](https://nus-cs2103-ay2021s2.github.io/website/admin/tp-constraints.html#constraint-external-software)** constraint?

**Comment by damithc** [comment]
It should be fine, in the same way using an http link (clicking of which opens the link in the default Browser) is fine.

**Comment by riyadh-h** [comment]
Okay 👍 
Thanks prof @damithc !
