### ISSUE TITLE
JavaFX Alerts causes application to crash

### ISSUE THREAD

**Issue by georgepwhuang** [nus-cs2103-AY2021S2/forum#267]
I've been using some JavaFX Alerts in my code and the problem is that sometimes when I switch windows while the Alert is displayed, the Java application just suddenly crashes without me nor the Java application doing anything in the meantime.
It wouldn't crash if I stay on the application even with an indefinite amount of time. So I'm pretty confident it's not a coding issue, and I found out that it's supposedly it's a system issue on MacOS Mojave on window switching.

<img width="1440" alt="Screen Shot 2021-03-28 at 1 36 37 AM" src="https://user-images.githubusercontent.com/71061276/112729335-8c681680-8f66-11eb-8b48-adbe246aa703.png">

This is what I get on IntelliJ after the crash.

So my question is: would this be counted as a bug in the application if this kind of problem occurs during the PE?

**Comment by damithc** [comment]
You wont be penalized if it is known issue of JavaFX that hasn't been fixed yet and there is no reasonable workaround.

**Comment by georgepwhuang** [comment]
Okay thanks professor!
