### ISSUE TITLE
Does User guide section running across two pages count as bugs?

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#269]
After saving our group's user guide as PDF, we realized that some sections cannot fit into one page and on the second page, there will be blank spaces. The next section will carry on at the start of a brand new page. For example, there is a blank space after the following screenshot, and the user guide continues on from the top of the following page. 

Question: will this be counted as a formatting bug during PE/assessment?
![image](https://user-images.githubusercontent.com/41845017/112747025-59189c80-8fe5-11eb-99a3-fade40d63fb2.png)

**Comment by damithc** [comment]
It should be fine, as it doesn't really hinder the reader.
