### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by lrj689** [nus-cs2103-AY2021S2/forum#27]
Is there suppose to be data shown on the iP Progress Dashboard? I have pushed increments into my fork but the site shows [No data yet]. https://nus-cs2103-ay2021s2.github.io/dashboards/contents/ip-progress.html

**Comment by w2vgd** [comment]
It should show from week 3 onwards, similar to the participation marks progress.

**Comment by damithc** [comment]
> It should show from week 3 onwards, similar to the participation marks progress.

Correct.
Thanks @w2vgd

**Comment by lrj689** [comment]
Thank you for the quick answer!
