### ISSUE TITLE
Changing package name resulted in incorrect gradle test cases

### ISSUE THREAD

**Issue by litone01** [nus-cs2103-AY2021S2/forum#270]
Dear all, 

I recently changed the package name of tp from seedu.address to seedu.sochedule. However, upon running the gradle for testing, I noticed that I have doubled test cases now. An screenshot for the test result has been attached at the back. 

Thus, can I check if this issue is relevant to my intellij setting or gradle or some other file?
Some possibilities ruled out:
1. I have checked that the test under seedu.address have disappeared and I only have on test folder under seedu.sochedule
2. For the build.gradle file, the only line changed is the mainappname as shown in the image below. 
![image](https://user-images.githubusercontent.com/56266729/112751755-2af58580-9002-11eb-90df-1044e51fb60f.png)

![image](https://user-images.githubusercontent.com/56266729/112751666-bb7f9600-9001-11eb-901c-2a9a13a52246.png)

Thank you so much!
---------------------------------------------------------------------------------------------------------------------------------------
Update:
CI via github action works and has shown no error. I highly doubt it may be linked to my intellji Junit test, maybe dependency? Can anyone help to point out the possible files to look further into?

**Comment by damithc** [comment]
Be careful with renaming packages at this stage of the project. It can (it may or may not) mess up the code authorship tracking done by RepoSense. That's why we recommended package renaming to be done earlier in the project (in week 8)
![image](https://user-images.githubusercontent.com/1673303/112752865-a7d72e00-9007-11eb-8551-6155085f68dd.png)

**Comment by litone01** [comment]
Sorry Prof @damithc , we overlooked this part:( Can I kindly check if not renaming the package will affect the grading of our tp since it is stated as optional? Thanks

**Comment by damithc** [comment]
> Sorry Prof @damithc , we overlooked this part:( Can I kindly check if not renaming the package will affect the grading of our tp since it is stated as optional? Thanks

Not really. You just need to ensure RepoSense attributes the code to the right persons. In cases where it doesn't, you can use `@@author` tags to tweak the authorship allocation, which creates some extra work for you. More info https://nus-cs2103-ay2021s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking

**Comment by litone01** [comment]
Thank you prof for the answer!
