### ISSUE TITLE
Typo in W11.5 Reuse section

### ISSUE THREAD

**Issue by cnlinh** [nus-cs2103-AY2021S2/forum#271]
![Screenshot 2021-03-29 at 11 13 43 PM](https://user-images.githubusercontent.com/33710749/112858503-8435e580-90e4-11eb-98c8-5985a0defc9d.png)
The name of this section should be "Reuse" instead of "API"?

**Comment by damithc** [comment]
Good catch.
Thanks @cnlinh 
Also realized that I missed out an optional topic that should be here 'Designing APIs'
Fixed.
