### ISSUE TITLE
Are we obliged to consider corrupted data files (by users) for tp?

### ISSUE THREAD

**Issue by Cheng20010201** [nus-cs2103-AY2021S2/forum#272]
As per title; for local storage files (a `.json` file for example), if we want to make some assumptions to certain fields (i.e. certain format of data), then do we need to account for 'illegal' user modification to the files? More specifically:
- If we want to make the application fail if the modification to the data file is a corrupted one, then what can be considered as 'failing elegantly'?
  - The application cannot launch (gives error message when launching from CLI)
  - The application launches, but without corrupted data loaded
- Do we need to explain it (how an advanced user should modify the data file, if he/she wants to) in our UG(/DG)?

**Comment by damithc** [comment]
@Cheng20010201 The current AB3 UG mentions this aspect in one place. It's good enough if you maintain that level of support in your product as well. Better support is welcome but not required.
