### ISSUE TITLE
Typo in class name JsonSerializableAddressBookStorage in StorageClassDiagram

### ISSUE THREAD

**Issue by candyhy** [nus-cs2103-AY2021S2/forum#273]
Class `JsonSerializableAddressBookStorage` does not exist.
I believe it should be `JsonSerializableAddressBook` instead

<img width="748" alt="Screenshot 2021-03-30 at 2 12 36 AM" src="https://user-images.githubusercontent.com/70088064/112880736-67f27280-90fd-11eb-9823-f4bb0e6f5b96.png">

**Comment by w2vgd** [comment]
Yeahh I realized that in addition to this, there is also a typo in `JsonSerializablePerson`. It should have been `JsonAdaptedPerson` instead.

![image](https://user-images.githubusercontent.com/65358857/112881680-915fce00-90fe-11eb-95a9-2cce984ea5d6.png)

**Comment by damithc** [comment]
Thanks @candyhy and @w2vgd for reporting this. I've reported it at https://github.com/se-edu/addressbook-level3/issues/86

**Comment by damithc** [comment]
Fixed in https://github.com/nus-cs2103-AY2021S2/tp/commit/f741ba434f77b3dd25bc6a84c2cd9ebd4b30df3a
