### ISSUE TITLE
Drawing interfaces in PlantUML

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#276]
Is there a reason why we do not use `Class "<<Interface>>\nNameOfInterface"` to draw an interface (so that it is not in italics) instead of the original `Interface NameOfInterface <<Interface>>` (which gives an italics font)? Will this be considered a bug since italics is supposed to mean abstract classes?

`Class "<<Interface>>\nNameOfInterface"`:
![image](https://user-images.githubusercontent.com/65358857/113085057-bbee7b80-9211-11eb-8602-ee2f0ccbe89b.png)

`Interface NameOfInterface <<Interface>>`:
![image](https://user-images.githubusercontent.com/65358857/113085117-d0cb0f00-9211-11eb-8b13-eb17194b41d0.png)

**Comment by damithc** [comment]
The usage doesn't seem to be consistent even in the current version of AB3 e.g.,
![image](https://user-images.githubusercontent.com/1673303/113085520-8f872f00-9212-11eb-93d7-c3b7aee3e380.png)

For this semester, we'll accept any of those variations  as they don't really cause any confusion or affect the meaning.

Ideally, we should use non-italics for interfaces across all diagrams in AB3. We'll update AB3 diagrams to do so, but probably in a future semester.

**Comment by w2vgd** [comment]
Thanks
