### ISSUE TITLE
User guide uses a different quotation from java? 

### ISSUE THREAD

**Issue by ong6** [nus-cs2103-AY2021S2/forum#277]
The user guide uses this as a quotation `“` but when we paste this into java, it does not register the same as a `"` (a normal quotation from a keyboard input).

If the user decides to copy and paste commands from the user guide and gets a parsing issue, is this a bug on us?

**Comment by damithc** [comment]
@ong6 
1. Does this situation apply it existing AB3 UG?
2. Is that going to cause problems? Nothing like that was reported in previous years.
3. If yes, is there a way to prevent that problem in the first place?

**Comment by ong6** [comment]
Hi prof, sorry for late reply, we managed to solve this by using an escape character!
