### ISSUE TITLE
Why the master branch is not following me?

### ISSUE THREAD

**Issue by AiwassPrime** [nus-cs2103-AY2021S2/forum#28]
![image](https://user-images.githubusercontent.com/58588910/105461616-71f49100-5cc8-11eb-9c8f-898db83a6df1.png)
This project was forked to my own repo and cloned to my local computer. After submited a few commits, I found that the master branch was not following me, whereas in the lecture video when prof added a new commit, the master branch was always moving upward.
Is this normal? Am I doing anything wrong?

**Comment by chesterhow** [comment]
Did you git push your new commits?

**Comment by Cp-John** [comment]
Did you forget to stage your changes before pushing?

**Comment by Cheng20010201** [comment]
If you only added commits and did not push your commits to your remote repo, there will be no remote changes and your master branch will not follow you.

**Comment by AiwassPrime** [comment]
Hi,
![image](https://user-images.githubusercontent.com/58588910/105462955-5c806680-5cca-11eb-8729-15d0efc4de32.png)
![image](https://user-images.githubusercontent.com/58588910/105463188-a79a7980-5cca-11eb-9cc3-7fb9a0b6ed4d.png)

I did try to push to my remote repo. But it keeps rejecting me.

**Comment by damithc** [comment]
Looks like you committed while not on any branch (the so called 'detached head' situation)
Try this:
```
git branch temp
git checkout master
git merge temp
```

**Comment by damithc** [comment]
To run commands, you need to open a git bash terminal, using this button:
![image](https://user-images.githubusercontent.com/1673303/105463684-622a7c00-5ccb-11eb-8bf8-c7ac928093bb.png)

**Comment by AiwassPrime** [comment]
> Looks like you committed while not on any branch (the so called 'detached head' situation)
> Try this:
> 
> ```
> git branch temp
> git checkout master
> git merge temp
> ```

Thank you prof, that solves my problem!

**Comment by damithc** [comment]
> Thank you prof, that solves my problem!

Great. See the _accepted_ answer of [this s/o thread](https://stackoverflow.com/questions/10228760/fix-a-git-detached-head) for more info on how those commands fixed the problem.
