### ISSUE TITLE
Intellij running window off screen

### ISSUE THREAD

**Issue by xuanqi966** [nus-cs2103-AY2021S2/forum#280]
Hi, I'm encountering an issue with the position of the app window.
When I run the app by running Main in Intellij, the app is running and the app icon appears on the task bar (circled in red in the image below), but the app window is no where to be found. I've tried deleting the .ideas files or resetting workspace.xml but none of these worked. My teammates are still able to run the app as usual so I suspect there's something wrong with my Intellij. My Intellij version is 2020.3.3 Ultimate.
![Screenshot 2021-04-01 164652](https://user-images.githubusercontent.com/58899539/113269577-2cc58e80-930b-11eb-81da-82b87cb9af57.png)

**Comment by damithc** [comment]
Try after running  `gradlew clean` to get rid of any output files created earlier.

**Comment by xuanqi966** [comment]
> Try after running `gradlew clean` to get rid of any output files created earlier.

Hi prof, I tried but still doesn't work.

**Comment by damithc** [comment]
> Hi prof, I tried but still doesn't work.

Try deleting the `out` folder manually. BTW, what happens if generate a JAR file and run that instead? Does the Window show up?

**Comment by xuanqi966** [comment]
> > Hi prof, I tried but still doesn't work.
> 
> Try deleting the `out` folder manually. BTW, what happens if generate a JAR file and run that instead? Does the Window show up?

Deleting the out folder doesn't work as well. Running the JAR directly is okay, the window shows up properly.

**Comment by damithc** [comment]
Delete the `preferences.json` file at the root of the project folder and see if that works.

**Comment by xuanqi966** [comment]
> Delete the `preferences.json` file at the root of the project folder and see if that works.

It worked after deleting preferences.json, thank you prof!

**Comment by damithc** [comment]
Explanation: AB3 'remembers' its last Window position/size, which is stored in `preferences.json` file. I suspected the data in that file is corrupted and deleting it might solve the problem. But I thought the file is stored either in the `build` folder or `out` folder but as neither worked, I dug around in my AB3 code a bit more to find where exactly is that file, which turned out to be in the project root.
