### ISSUE TITLE
macos-latest not starting

### ISSUE THREAD

**Issue by banchiang** [nus-cs2103-AY2021S2/forum#281]
Hi Prof @damithc the check for macos is not loading (10mins in and it had not started), I refreshed twice and the issue still exists. The build is not starting though it is queued.
![build](https://user-images.githubusercontent.com/72375578/113294121-30680e00-9329-11eb-91b1-05fb20be5145.png)

**Comment by riyadh-h** [comment]
My team and I are facing a similar issue as well.

> Hi Prof @damithc the check for macos is not loading (10mins in and it had not started), I refreshed twice and the issue still exists. The build is not starting though it is queued.
> ![build](https://user-images.githubusercontent.com/72375578/113294121-30680e00-9329-11eb-91b1-05fb20be5145.png)

**Comment by mechastriker3** [comment]
My team and I are facing the same issue too.
<img width="1263" alt="Screen Shot 2021-04-01 at 9 21 21 PM" src="https://user-images.githubusercontent.com/33394879/113300184-4200e400-9330-11eb-9c66-fea176831864.png">

**Comment by shuyang0** [comment]
Same issue here.
![image](https://user-images.githubusercontent.com/42297329/113301735-ea637800-9331-11eb-9422-183b9d69e584.png)

**Comment by pyuxiang** [comment]
Me too.

![image](https://user-images.githubusercontent.com/28663438/113303101-52ff2480-9333-11eb-9013-a1218cf97ed8.png)

**Comment by glennljs** [comment]
Me too.
![photo_2021-04-01 21 44 21](https://user-images.githubusercontent.com/43852051/113303226-73c77a00-9333-11eb-9515-654ca35d7294.jpeg)

**Comment by garyljj** [comment]
Me too.

![image](https://user-images.githubusercontent.com/71179511/113303294-8477f000-9333-11eb-8130-e1f4a74bcfcf.png)

**Comment by nickyfoo** [comment]
Me too.
![image](https://user-images.githubusercontent.com/67411893/113303287-80e46900-9333-11eb-908d-bee56101c7f9.png)

**Comment by Ellevy** [comment]
Me too.
![image](https://user-images.githubusercontent.com/46534252/113303327-8c379480-9333-11eb-9e3a-8d3e1720d204.png)

**Comment by zhengruoxin** [comment]
Me too.

![photo_2021-04-01 21 43 55](https://user-images.githubusercontent.com/65821483/113303293-83df5980-9333-11eb-9b46-6fb95e1d9dbf.jpeg)

**Comment by tlylt** [comment]
![image](https://user-images.githubusercontent.com/41845017/113303490-b8ebac00-9333-11eb-806c-b037d408634e.png)

**Comment by SoonKeatNeo** [comment]
I’m guessing it’s an issue with the macOS CI client on Github’s end?

**Comment by banchiang** [comment]
Okay looks like it works now!
