### ISSUE TITLE
latest PR's / commits not reflecting on reposense

### ISSUE THREAD

**Issue by umergta** [nus-cs2103-AY2021S2/forum#282]
I wonder if it is just my group but the latest pushes in our project are not being reflected on reposense for a few days already.
For e.g. all of us made PR's and merged it into master on 31st March but none of those are reflected on reposense.
Any idea how to fix it or is it a problem with reposense not detecting them? (i doubt this is the case)

**Comment by damithc** [comment]
@umergta I updated the code dashboard just now. Still not detected? if that is the case, please share the link to a PR/commit that is not reflected so that I can get someone to investigate.

**Comment by damithc** [comment]
@umergta looks like only one of you have commits done on 31st? https://github.com/AY2021S2-CS2103T-T13-2/tp/commits/master

**Comment by umergta** [comment]
Hi prof @damithc I just looked at the latest PRs. I think i got confused as I thought the PR's weree reflected. However, reposense shows each commit in a PR so its broken down. Thank you for the clarification! I think reposense has captured everything not to worry :)
