### ISSUE TITLE
Java CI testcase fail despite passing locally

### ISSUE THREAD

**Issue by xuanqi966** [nus-cs2103-AY2021S2/forum#284]
I can pass all test cases locally with ```gradlew test``` or running the whole test folder but some test cases keep failing on GitHub. This branch has already been merged with the latest master.
![image](https://user-images.githubusercontent.com/58899539/113399828-737ebb80-93d3-11eb-9c2d-3d9e8ffbc9a7.png)

**Comment by samuelfangjw** [comment]
<img width="670" alt="Screenshot 2021-04-02 at 5 58 43 PM" src="https://user-images.githubusercontent.com/60355570/113405848-12f47c00-93dd-11eb-8bd0-7d5450f42299.png">

Hi, I downloaded a copy of your program from your `add-tests` branch and ran the tests locally using `gradlew test`. Got a few failing test cases as shown in the screenshot above. Can you double check to make sure the test cases run locally?

**Comment by xuanqi966** [comment]
> <img alt="Screenshot 2021-04-02 at 5 58 43 PM" width="670" src="https://user-images.githubusercontent.com/60355570/113405848-12f47c00-93dd-11eb-8bd0-7d5450f42299.png">
> 
> Hi, I downloaded a copy of your program from your `add-tests` branch and ran the tests locally using `gradlew test`. Got a few failing test cases as shown in the screenshot above. Can you double check to make sure the test cases run locally?

Hi, I have double checked and my team mate has also tried testing my program, but the test cases still run locally. Can I trouble you to take screenshoots of the errors you have discovered so that I can try to make some sense out of it? Thank you!

**Comment by GabrielSimbingyang** [comment]
Hi @xuanqi966 ,

Ex-student of CS2103T here, 

Could I check what do you mean by this: 

> but the test cases still run locally

Are the test still succeeding on your local computer but not on your github?  Also, would you mind linking me to the repo link so I check it on my end?

Regards, 
Gabriel Sim

**Comment by kouyk** [comment]
> Hi, I downloaded a copy of your program from your `add-tests` branch and ran the tests locally using `gradlew test`. Got a few failing test cases as shown in the screenshot above. Can you double check to make sure the test cases run locally?

Same I could reproduce the same errors. You might want to run `./gradlew clean` for a rebuild before running the tests again to see if it helps. Below are the detailed errors.

```
LogicManagerTest > execute_invalidCommandFormat_throwsParseException() FAILED
    org.opentest4j.AssertionFailedError at LogicManagerTest.java:143
        Caused by: seedu.booking.logic.commands.exceptions.CommandException at LogicManagerTest.java:143

LogicManagerTest > execute_validCommand_success() FAILED
    java.lang.IllegalArgumentException at LogicManagerTest.java:103

LogicManagerTest > execute_storageThrowsIoException_throwsCommandException() FAILED
    org.opentest4j.AssertionFailedError at LogicManagerTest.java:143
        Caused by: java.lang.IllegalArgumentException at LogicManagerTest.java:143

LogicManagerTest > execute_commandExecutionError_throwsCommandException() FAILED
    org.opentest4j.AssertionFailedError at LogicManagerTest.java:143
```

**Comment by damithc** [comment]
When tests fail in one computer but not another, some OS-specific thing could be at play too. e.g.,  using `/` vs `\` as file path separators. Just in case you have something like that in your code.

**Comment by samuelfangjw** [comment]
> > Hi, I downloaded a copy of your program from your `add-tests` branch and ran the tests locally using `gradlew test`. Got a few failing test cases as shown in the screenshot above. Can you double check to make sure the test cases run locally?
> 
> Same I could reproduce the same errors. You might want to run `./gradlew clean` for a rebuild before running the tests again to see if it helps. Below are the detailed errors.
> 
> ```
> LogicManagerTest > execute_invalidCommandFormat_throwsParseException() FAILED
>     org.opentest4j.AssertionFailedError at LogicManagerTest.java:143
>         Caused by: seedu.booking.logic.commands.exceptions.CommandException at LogicManagerTest.java:143
> 
> LogicManagerTest > execute_validCommand_success() FAILED
>     java.lang.IllegalArgumentException at LogicManagerTest.java:103
> 
> LogicManagerTest > execute_storageThrowsIoException_throwsCommandException() FAILED
>     org.opentest4j.AssertionFailedError at LogicManagerTest.java:143
>         Caused by: java.lang.IllegalArgumentException at LogicManagerTest.java:143
> 
> LogicManagerTest > execute_commandExecutionError_throwsCommandException() FAILED
>     org.opentest4j.AssertionFailedError at LogicManagerTest.java:143
> ```

Hi there, can confirm the same tests are failing. I did some very light testing, the tests in `LogicManagerTest` work when run in isolation but do not work when run together with other tests. Seems like your application takes into account some kind of state when parsing commands, I believe the state is not being reset, causing the tests to fail.

Edit:
The tests also seem inconsistent for me. Running the tests multiple times, sometimes all tests  pass sometimes it fails.

**Comment by samuelfangjw** [comment]
In `LogicManagerTest`, I added the following line to reset the state to inactive before every test and the tests don't seem to be failing anymore.

```java
    @BeforeEach
    public void setUp() {
        JsonBookingSystemStorage bookingSystemStorage =
                new JsonBookingSystemStorage(temporaryFolder.resolve("bookingSystem.json"));
        JsonUserPrefsStorage userPrefsStorage = new JsonUserPrefsStorage(temporaryFolder.resolve("userPrefs.json"));
        StorageManager storage = new StorageManager(bookingSystemStorage, userPrefsStorage);
        logic = new LogicManager(model, storage);
        ModelManager.setStateInactive(); // added this line
    }
```

Seems like a short term band aid solution to the current problem though (shared state between tests).

**Comment by xuanqi966** [comment]
The issue is resolved after adding the logic suggested by @samuelfangjw. The issue is caused by failure to reset class-level states which are shared by several commands. I'm still unsure about why some systems can run some system cannot but at least the error on Java CI has been resolved. Thank you everyone for your kind help:D

**Comment by damithc** [comment]
Thanks @kouyk @GabrielSimbingyang @samuelfangjw 

IIRC, tests are run in random order, which means they can pass in some computers but not others.
