### ISSUE TITLE
Change in tP documentation structure causes grading script to fail documentation progress checks

### ISSUE THREAD

**Issue by pyuxiang** [nus-cs2103-AY2021S2/forum#285]
@damithc, since this seems to be a module-wide behaviour.

## The change

Our group recently refactored our tP documentation structure in a series of commits [`4df1103`](https://github.com/AY2021S2-CS2103-W16-3/tp/commit/4df1103d76c5273f1f2c77c6d5e986c5b262b8c2)...[`73947a7`](https://github.com/AY2021S2-CS2103-W16-3/tp/tree/73947a7f2a5db30bb91a469cb3ac3f10ac258164).
Essentially we changed the hierarchy of documents from:

```
docs
+-- DeveloperGuide.md
+-- Configuration.md
+-- ...
+-- UserGuide.md
```

to the following, to abstract content away from the structure of the developer guide:

```
docs
+-- developer
|   +-- Configuration.md
|   +-- ...
+-- developerGuide
|   +-- architecture
|   |   +-- Logic.md
|   |   +-- ...
|   +-- feature
|   |   +-- Add.md
|   |   +-- ...
|   +-- ...
+-- DeveloperGuide.md
+-- UserGuide.md
```

Sample code snippet of [`DeveloperGuide.md`](https://github.com/AY2021S2-CS2103-W16-3/tp/blame/4df1103d76c5273f1f2c77c6d5e986c5b262b8c2/docs/DeveloperGuide.md#L18-L26) after refactoring:

```
### Architecture

{\% include_relative developerGuide/architecture/index.md %\}`

The sections below give more details of each component.

{\% include_relative developerGuide/architecture/Ui.md %\}

{\% include_relative developerGuide/architecture/Logic.md %\}
```

## The problem

This had the unintended effect of removing the progress check marks on the [dashboard](https://nus-cs2103-ay2021s2.github.io/dashboards/contents/tp-progress.html) for group members, since the grading scripts seem to only capture changes and regenerates statistics only based on the git blame of specific files `/docs/developerGuide.md` and `/docs/UserGuide.md` in the latest commit of the `master` branch:

Sample 1:

![image](https://user-images.githubusercontent.com/28663438/113467234-577f2680-9474-11eb-9ad3-2546ddf50481.png)

Sample 2:

![image](https://user-images.githubusercontent.com/28663438/113467270-944b1d80-9474-11eb-9f02-4688b8406dce.png)

## Proposed fixes

Would it be possible to add an exception to the grading scripts for progress prior to week 12 to track based on the commit [`3ef2209`](https://github.com/AY2021S2-CS2103-W16-3/tp/tree/3ef2209a730b28a6b57338bd447a4c48fcd4622b/docs) immediately before the refactoring? Otherwise what would be the recommended next step forward?

Any help rendered would be greatly appreciated. Thank you!

**Comment by damithc** [comment]
I'll look into this later. Will keep you posted.

**Comment by damithc** [comment]
@pyuxiang should be OK now i.e., anything in `docs/developerGuide/` folder are considered part of DG. Let me know if still not reflected in the dashboard.

**Comment by pyuxiang** [comment]
Confirmed working, thanks for the quick response!
