### ISSUE TITLE
What do we have to do with the assigned bug reports?

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#290]
In the project tasks for this week, it is only mentioned that we add `invalid` labels to issues that are **not useful** at all. 
Does this mean we do not have to reassign severity levels even if it is higher than it is supposed to be? 
Does this also mean we assign `invalid` labels to a bug if we do not agree with it?

**Comment by damithc** [comment]
>add `invalid` labels to issues that are not useful at all.

The above is for us to identify rubbish bug reports. As for the other bug reports, you can deal with them as you wish i.e., triage, apply labels, assign, close etc.

**Comment by w2vgd** [comment]
> > add `invalid` labels to issues that are not useful at all.
> 
> The above is for us to identify rubbish bug reports. As for the other bug reports, you can deal with them as you wish i.e., triage, apply labels, assign, close etc.

Hi Prof, just to confirm, if we do not agree with a bug report, we can just close them without needing to do anything else right?

**Comment by damithc** [comment]
> Hi Prof, just to confirm, if we do not agree with a bug report, we can just close them without needing to do anything else right?

Yes, that's right.

**Comment by w2vgd** [comment]
Thanks for the clarification!
