### ISSUE TITLE
tp progress dashboard suddenly shown 0 commits

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#292]
Hi prof, as I was checking the dashboard, I realized that it is showing that I have 0 commits for all of the past weeks. May I check if there is something wrong with the script or did I do anything that caused this? 

![image](https://user-images.githubusercontent.com/65358857/113508656-d0b96f00-9583-11eb-8089-18453b9eafcb.png)

![image](https://user-images.githubusercontent.com/65358857/113508662-da42d700-9583-11eb-9269-7b08fd7734a7.png)

**Comment by damithc** [comment]
Ah, this is because your commits being excluded due to you being recognized as an AB3 developer (due to the bug fix you submitted to AB3 earlier). Will fix in the next update.

**Comment by w2vgd** [comment]
Ohh, I see. Thanks!
