### ISSUE TITLE
Regarding minimum display sizes, is there an expected minimum size that we have to follow? 

### ISSUE THREAD

**Issue by ong6** [nus-cs2103-AY2021S2/forum#297]
What is a reasonable limit here :P would (1368x768) suffice? 
![image](https://user-images.githubusercontent.com/19247856/113971237-3f4d3580-97ed-11eb-9b60-19a67b1e58df.png)

Also for my previous error command question, I hope this is not too long
![image](https://user-images.githubusercontent.com/19247856/113971490-bc78aa80-97ed-11eb-967b-4ba1b48f7a41.png)

**Comment by damithc** [comment]
> What is a reasonable limit here :P would (1368x768) suffice?

No official requirement. Can discuss with others to try to figure out what's a reasonable lower bound for the target audience. Also, _impossible_ to use in lower resolution is different from _hard_ to use in lower resolutions. The former is a higher priority problem than the latter.


> Also for my previous error command question, I hope this is not too long

Post in that thread and try to get others' opinions? I won't give any answer myself (or else everyone will want to run their PE-D decisions by me :-p)

**Comment by ong6** [comment]
Ok thanks for the feedback prof, appreciate it!
