### ISSUE TITLE
Unable to push the new commits to my fork on GitHub

### ISSUE THREAD

**Issue by 993-asv** [nus-cs2103-AY2021S2/forum#3]
<img width="592" alt="Screenshot 2021-01-16 at 5 41 09 PM" src="https://user-images.githubusercontent.com/77260951/104808554-15095e80-5822-11eb-86ce-708b3994952a.png">

Hi all,

I have been receiving this error message on SourceTree when I try to push my new commits to my fork on GitHub, and I do not know how to get around it. Could I please get some advice? 

Thank you!!

**Comment by damithc** [comment]
Does it work if you use the command line? i.e., `git push origin master`?

**Comment by 993-asv** [comment]
It does work!

**Comment by Jh123x** [comment]
Can you try going to manage windows credentials (control panel->user accounts->credential manager) and deleting anything with bitbucket.org mentioned in the name under the generic credentials section. I.e. it might look like "git:https://username@bitbucket.org" and then trying again to see if it is working

**Comment by raythx98** [comment]
I am not exactly sure, but based on your error message and looking at ur github page, I believe you might be using an erroneous URL, your repo link is

> https://github.com/993-asv/samplerepo-things

To change the remote repo's URL link, go 

`repository > repository settings (ctrl+shift+,) > edit origin > change URL to`

> https://github.com/993-asv/samplerepo-things

Be sure to authenticate using ur github account too, this can be done under 
`tools > options > authentication`

**Comment by Jh123x** [comment]
It seems like it is a very similar issue to [here](https://community.atlassian.com/t5/Sourcetree-questions/Unable-to-push-a-commit-to-Github-repository/qaq-p/1034485)

If the issue still persists, maybe you can try doing the following:
1. Obtain GitHub access token [here](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line)
1. open SourceTree Options: Tools -> Options
1. Input your GitHub access token to "SSH Key"
1. Try to commit again

**Comment by 993-asv** [comment]
Thank you all for the help! It was indeed the problem identified by Jh123x!

**Comment by damithc** [comment]
Thanks @raythx98 @Jh123x

**Comment by richardcom** [comment]
I have met a similar issue last time (Permission Denied). The possible problem might be that the github account for sourcetree was not set up properly. 

You may refer [here](https://confluence.atlassian.com/get-started-with-sourcetree/connect-your-bitbucket-or-github-account-847359096.html) for setting up the github account for sourcetree.

Similar to this screenshot below, but change the Host to Github instead.

![image](https://user-images.githubusercontent.com/65701775/104814633-04b9a980-584b-11eb-9159-6f77c50dc476.png)
