### ISSUE TITLE
Query regarding mock exam released during lecture

### ISSUE THREAD

**Issue by arsatis** [nus-cs2103-AY2021S2/forum#300]
Hi prof,

May I ask if the short mock exam which will be released during the lecture will be accessible to students who do not attend the live lecture as well? Or do we need to attend the live session in order to be able to view the mock exam?

Thank you!

**Comment by damithc** [comment]
No need @arsatis . You can access it even after lecture.

**Comment by arsatis** [comment]
Noted, thank you!
