### ISSUE TITLE
RepoSense: FXML contributions not tracked

### ISSUE THREAD

**Issue by noelmathewisaac** [nus-cs2103-AY2021S2/forum#302]
While going through the tp code dashboard I noticed that none of my commits involving modifications to the `.fxml` files are being tracked by RepoSense while all my other commits are showing up fine. Is this because of the way RepoSense is set up not to track these files? Being in charge of the UI for my team, a lot of my commits involve `.fxml` file modifications.

**Comment by damithc** [comment]
@noelmathewisaac the code dashboard _is_ tracking fxml files. Some of your team members already have fxml files among the code they authored.
Perhaps the code you authored were taken over by someone else in the team?
Can you give the link to a file that contains code that you authored?

**Comment by noelmathewisaac** [comment]
@damithc these are some of the commits that haven't shown up on my dashboard:
- https://github.com/AY2021S2-CS2103T-W14-4/tp/commit/30b59c98a71b414c404536600dc30e486205adfe
- https://github.com/AY2021S2-CS2103T-W14-4/tp/commit/1a58bcdd0ea163f866bcfb9dd9f6f2320a91265c
- https://github.com/AY2021S2-CS2103T-W14-4/tp/commit/07fd289a3e91278cf13d87d6d9ed269101073d08
- https://github.com/AY2021S2-CS2103T-W14-4/tp/commit/487d110b3ce8dcb8947c6c81fa3d6e252b5aa33b
- https://github.com/AY2021S2-CS2103T-W14-4/tp/commit/dea8939f336eed8d91cecc556594befaf32919d8

I noticed that the commits which don't show up have changes purely in fxml/css files. Other commits involving changes to java files as well as fxml/css files show up fine.

**Comment by damithc** [comment]
@noelmathewisaac I've asked the RepoSense team to look into it. Will keep you posted.

**Comment by noelmathewisaac** [comment]
thank you @damithc

**Comment by damithc** [comment]
@noelmathewisaac both commits and the the code is missing from your authorship data or it's just the commits that are missing?

**Comment by noelmathewisaac** [comment]
@damithc only the commits are missing.

**Comment by damithc** [comment]
@noelmathewisaac Should be fixed now. Please check.

**Comment by noelmathewisaac** [comment]
@damithc yeap, everything shows up now. Thank you!
