### ISSUE TITLE
Sequence diagram: can we use a function name that does not exist?

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#303]
In the sequence diagram, if in view of keeping it high level, instead of describing a few functions calls that I invoke from a component, I use a function name that describes what I want to do. But that function actually does not exist. Will that be OK?
E.g.
instead of using the two actual method names (doA and doB are actual methods)
```
X         Y        
| doA     |
| ------> |
| doB     |
| ------> |
```
Can I just use a fake method name (doC is not an actual method in my code) in place of the above?
```
X         Y        
| doC     |
| ------> |
```

**Comment by damithc** [comment]
Yes, but best not to make it appear like a method name which can be misleading . e.g., use `get account details` instead of `getAccountDetails()`.

**Comment by tlylt** [comment]
Got it. Thanks, prof.
