### ISSUE TITLE
Are non-methods allowed in sequence diagrams?

### ISSUE THREAD

**Issue by benedictkhoomw** [nus-cs2103-AY2021S2/forum#306]
If the intended focus of a particular diagram is showing some interesting process that happens after the parsing and execution of commands, is it okay if we make reference to a non-existent method such as `parse and execute("help")` (shown in the example diagram below), assuming we place a note below the diagram to clarify this to the reader. The idea is to reduce clutter by simplifying part of the process which is less important for the diagram.

And, if the answer is yes, then another question: is `parse and execute("help")` preferred, or `parseAndExecute("help")`? I chose the former for this example to emphasize that it is not a real method.

![image](https://user-images.githubusercontent.com/77471078/114264667-c59c8e00-9a1e-11eb-8205-62eb3c429495.png)

**Comment by damithc** [comment]
Relevant https://github.com/nus-cs2103-AY2021S2/forum/issues/303

**Comment by benedictkhoomw** [comment]
Ah, I did not see that thread. Thank you.
