### ISSUE TITLE
LumiNUS mock exam: Question on functional requirement

### ISSUE THREAD

**Issue by SoonKeatNeo** [nus-cs2103-AY2021S2/forum#307]
Hi,

Regarding this question in particular: "Which one is most likely a functional requirement (as opposed to a non-fucntional requirement) for a Learning Management System such as LumiNUS

[Justification: why is it least likely?]"

Was the justification supposed to be most likely?

**Comment by damithc** [comment]
Yup. Fixed. Thanks @SoonKeatNeo  for letting me know.
