### ISSUE TITLE
Clarification: How much to put in DG (implementation)

### ISSUE THREAD

**Issue by pPris** [nus-cs2103-AY2021S2/forum#308]
Hi everyone, can I check if we're supposed to cover all the main features we've added/enhanced in the TP in our DG's implementation section? Or is covering a minimum of one feature + 1-2 diagrams enough? 

Not too sure of how much is required in DG and we can't figure out this information from the website so far.

Thank you!

**Comment by damithc** [comment]
@pPris decide primarily based on the target reader's (i.e., future developers) point of view. Omit if not useful to the target reader.

However, a secondary objective of the DG is to showcase your technical writing skills. If there is not enough content to meet that objective, you can add some more.

**Comment by pPris** [comment]
That helps, thank you prof!
