### ISSUE TITLE
Dependencies between classes and other components in `Storage` class diagram

### ISSUE THREAD

**Issue by riyadh-h** [nus-cs2103-AY2021S2/forum#309]
Hello there!

So, for AB3's `Storage` class diagram (and, by extension, my team's diagram), some of the classes depend on others that can be found in other components. For example, refer to the AB3 diagram below:

![image](https://user-images.githubusercontent.com/69278589/114344149-e1747100-9b91-11eb-8365-39ed041cfde4.png)

According to AB3's code, `JsonAdaptedTag` depends on `Tag`, which is part of the `Model` component:

```
/**
* Converts a given {@code Tag} into this class for Jackson use.
*/
public JsonAdaptedTag(Tag source) { // < Tag is a parameter
    tagName = source.tagName;
}
```

My question is: is it necessary to explicitly show this kind of dependency in the diagram, or is it considered obvious due to the naming of the classes?

*EXTRA:* in case it is requested, here is the current state of the `Storage` model diagram for my team's project:

![image](https://user-images.githubusercontent.com/69278589/114344280-1c76a480-9b92-11eb-8b31-efa3c9084e96.png)

**Comment by damithc** [comment]
> My question is: is it necessary to explicitly show this kind of dependency in the diagram, or is it considered obvious due to the naming of the classes?

Good catch @riyadh-h 
Ideally, we should show a dependency from Storage to Model in the architecture diagram. But no need to do that now.
I guess OK to omit it from this class diagram. Perhaps add a small note in the description to remind the user that there are such dependencies from here to the Model component?

**Comment by riyadh-h** [comment]
Got it, I'll add a note to the description then 👍 
Thanks Prof @damithc !
