### ISSUE TITLE
Requesting permission to use json-simple

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#31]
## Library

[json-simple](https://code.google.com/archive/p/json-simple/downloads)

## Purpose

Use json file for storing/retrieving task information.

## License

[Apache License 2.0](http://www.apache.org/licenses/LICENSE-2.0)

**Comment by damithc** [comment]
Approved.

**Comment by litone01** [comment]
@tjtanjin Do you think it is worth to share with the rest that they are allowed to use this library also? (As it has been approved, they dont really need to get it approved again I suppose.) This is just a personal thought haha.

**Comment by damithc** [comment]
> @tjtanjin Do you think it is worth to share with the rest that they are allowed to use this library also? (As it has been approved, they dont really need to get it approved again I suppose.) This is just a personal thought haha.

Thanks for this suggestion @litone01. I think no further action needed from @tjtanjin
This issue is visible to everyone in the class and they can use the said library without requesting permissions again.

**Comment by litone01** [comment]
@damithc I see, thanks for the reply:)
