### ISSUE TITLE
Github not accepting square brackets for names

### ISSUE THREAD

**Issue by NightRaven49** [nus-cs2103-AY2021S2/forum#310]
Hi, 
Just would like to clarify for the Github final release, would there be any issue if the file name differs from what was told in the email? Whenever I try to upload the final jar file onto the releases page, Github automatically renames the file without the square brackets, like so:
![GIF](https://user-images.githubusercontent.com/11091758/114383420-1a2b3f00-9bc0-11eb-8a4a-bb1605397ba8.gif)
Even manually renaming the file after the upload does not work. It appears to be a limitation within Github, so was just wondering if there is any concession for this.

**Comment by damithc** [comment]
It's fine @NightRaven49, as long as the file name is as expected in the file uploaded to LumiNUS

**Comment by w2vgd** [comment]
> It's fine @NightRaven49, as long as the file name is as expected in the file uploaded to LumiNUS

Can the jar file name in github release be in another format? For example can my jar file name on github be `pocketestate.jar`?

**Comment by damithc** [comment]
> Can the jar file name in github release be in another format? For example can my jar file name on github be `pocketestate.jar`?

Should be OK, as long as it is clear what's the latest JAR file is.

**Comment by w2vgd** [comment]
> > Can the jar file name in github release be in another format? For example can my jar file name on github be `pocketestate.jar`?
> 
> Should be OK, as long as it is clear what's the latest JAR file is.

👍 It is tagged with v1.4
