### ISSUE TITLE
PPP not detected on tp progress page

### ISSUE THREAD

**Issue by lirc572** [nus-cs2103-AY2021S2/forum#311]
Hi Prof @damithc , I noticed that the tp progress page does not detect my PPP but it is already there and has been adapted (it was updated several days ago).

![photo6314232272156470696](https://user-images.githubusercontent.com/34601854/114397511-587d2a00-9bd1-11eb-9666-f30fb21284f9.jpg)

Is there anything I should do about it? Thank you!!

**Comment by damithc** [comment]
@lirc572 can you give the link to the file?

**Comment by lirc572** [comment]
> @lirc572 can you give the link to the file?

It's here: <https://github.com/AY2021S2-CS2103T-T11-2/tp/blob/master/docs/team/lirc572.md>

**Comment by damithc** [comment]
Your PPP file contained some text from the original template file (e.g., `AddressBook Level 3`) that was only removed a few hours ago. That change has not been propagated to the dashboard yet. It should turn green at the next update.

**Comment by lirc572** [comment]
> Your PPP file contained some text from the original template file (e.g., `AddressBook Level 3`) that was only removed a few hours ago. That change has not been propagated to the dashboard yet. It should turn green at the next update.

Okay!! Thank you prof!
