### ISSUE TITLE
Request to use javax email library

### ISSUE THREAD

**Issue by Shizheng001** [nus-cs2103-AY2021S2/forum#312]
## Library

[JavaMail1.4.5](https://www.oracle.com/java/technologies/javamail145.html)

## Purpose

{To enable login authentication and send mail through SMTP}

## License

{Common Development and Distribution License (CDDL) v1.1 and GNU General Public License (GPL) v2 with Classpath Exception (https://oss.oracle.com/licenses/CDDL+GPL-1.1)
}

**Comment by damithc** [comment]
Approved.
