### ISSUE TITLE
Unable to create PE repo with CATcher web version

### ISSUE THREAD

**Issue by arsatis** [nus-cs2103-AY2021S2/forum#313]
Hi prof,

This morning, I've tried to perform the series of steps indicated in the PE instructions email, but encountered a bug when I was trying to setup the PE repo:

![image](https://user-images.githubusercontent.com/55139982/114802070-9e074600-9dcf-11eb-811c-25661d10f7fd.png)

Can I check what could be causing "TypeError: o.addEventListener is not a function" to pop out?

**Comment by damithc** [comment]
@arsatis looks like the repo creation was not successful. Can you try again. If still doesn't work, please post in https://github.com/CATcher-org/CATcher/issues so that the CATcher team can follow up. Please do so soon, as we need to resolve soon.

**Comment by arsatis** [comment]
Just tried it again and it still doesn't work, will post an issue in the CATcher repo.

**Comment by arsatis** [comment]
Just an update: I managed to avoid the error/popup by visiting the website in Chrome's incognito mode, and then signing in to my GitHub account from there.

However, the issue is still happening when I open up CATcher without using incognito.

**Comment by damithc** [comment]
> However, the issue is still happening when I open up CATcher without using incognito.

@arsatis Thanks for the update. At least now we one one way to get around the problem (i.e., use incognito). See if deleting browser cache helps. Let us know how it goes.

**Comment by arsatis** [comment]
Hi prof, I've tried clearing the cache, but the error message still showed up :/

**Comment by damithc** [comment]
> Hi prof, I've tried clearing the cache, but the error message still showed up :/

Noted. CATcher team will follow up at https://github.com/CATcher-org/CATcher/issues/684

**Comment by arsatis** [comment]
Resolved. Issue was caused by a pop-up blocker.
