### ISSUE TITLE
Bug Severity in PE - How do we group bugs? 

### ISSUE THREAD

**Issue by ong6** [nus-cs2103-AY2021S2/forum#315]
It is said that each bug should be separate, but is grouping the same type of bug into one report ok? 

Suppose someone's user guide has many minor typos/ layout issues/other flaws in them (let's say more than 10), do we report each issue individually and label them as very low severity or do we group all of them up into one big Medium severity bug? 

The same goes with the error outputs in the App itself, since some error outputs (in different commands) may result in the same output, do we group them together or put them in one larger bug?

**Comment by damithc** [comment]
Should be separate. Otherwise hard to deal with duplicates e.g., say you reported five typos in one bug while another person reported only one of them in one bug report. We can't treat them as duplicates because they have different severities.

**Comment by ong6** [comment]
Ok thanks prof!
