### ISSUE TITLE
Permission to use javax.mail library

### ISSUE THREAD

**Issue by jay9645** [nus-cs2103-AY2021S2/forum#317]
## Library

JavaMail1.6.2(https://javaee.github.io/javamail/)

## Purpose

Validate email addresses

## License

{COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.1 (https://javaee.github.io/javamail/LICENSE)
}

**Comment by damithc** [comment]
Approved.
