### ISSUE TITLE
Error while accessing dev response

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY2021S2/forum#318]
I'm getting this error when accessing CS2103 PE dev response phase. I don't get it when accessing TIC4002 one though.

![image](https://user-images.githubusercontent.com/1673303/115099868-54ebf900-9f6b-11eb-9242-cc1728f5926d.png)

There was a few failed attempts earlier due to misconfigured repo permission though, if that is relevant. So far, students haven't reported this problem.

**Comment by damithc** [comment]
Sorry, wrong place :-p

**Comment by pyuxiang** [comment]
> So far, students haven't reported this problem.

At least two of us are currently also affected, using Chrome. Unable to access the issues directly on CATcher to respond to bugs.

**Comment by damithc** [comment]
@pyuxiang see if you can just close the error message and proceed.

**Comment by pyuxiang** [comment]
Can proceed as per normal after closing the error, managed to successfully submit a response for a bug report.

> Unable to access the issues directly on CATcher to respond to bugs.

This is an error on my part: I opened the issue in a new tab instead, which redirected me back to the login screen. Opening the bug report in the same tab works fine.

**Comment by damithc** [comment]
> This is an error on my part: I opened the issue in a new tab instead, which redirected me back to the login screen. Opening the bug report in the same tab works fine.

Thanks @pyuxiang for the update. Let us know if you encounter any further errors.
