### ISSUE TITLE
assertEquals method parameters updated in JUnit 5

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#32]
Hi, just wanted to point out that the `assertEquals` method parameters has been updated in JUnit 5, with the optional String message being moved to the last position instead of being at the first position. Thus, I believe that the W3.6 video's example on unit testing are outdated as shown in the screenshot below. (the video's first question can therefore have different answer if one follows the official documentation of JUnit 5, as provided [here](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/Assertions.html).)

<img src="https://user-images.githubusercontent.com/65358857/105518350-26b3a000-5d13-11eb-91a0-6ed077b737c4.png" width="600" height="200">

**Comment by damithc** [comment]
Thanks @w2vgd for the heads up.
I don't think I can fix it in this semester though, as replacing the video will also delete the quiz data.
I'll have to wait till the next semester to fix it.

**Comment by w2vgd** [comment]
Yup sure. I'll close this thread now.
