### ISSUE TITLE
Is adding the new keyword to calls to constructors in sequence diagrams considered a bug

### ISSUE THREAD

**Issue by samuelfangjw** [nus-cs2103-AY2021S2/forum#321]
![](https://raw.githubusercontent.com/nus-cs2103-AY2021S2/pe/main/files/6387002c-ff45-432e-9b04-9955ae9bd2a6.png)

With reference to [issue #707](https://github.com/nus-cs2103-AY2021S2/pe-dev-response/issues/707#issue-859961858) and the image above, the tester agues that using the new keyword in calls to constructor is inaccurate and the new keyword should be omitted from the sequence diagram e.g. `CommandResult(..., uiCommand)` instead of `new CommandResult(..., uiCommand)`. The tester has assigned this as a medium severity bug. 

Is not omitting the new keyword considered a bug and is this part of the module's UML standard? I would argue that there is no loss of information and a reader's understanding is not hindered by the new keyword and therefore not a bug. However, I also think it would be reasonable to accept this bug (at a lower severity level) if this was part of the module's UML standard as some examples in the textbook do omit it, although I am unable to find a definitive source for this in the textbook.

**Comment by damithc** [comment]
I think there is no reason for `new` to be there. But you are right, it doesn't cause much harm. Would be fine to accept as `severity.VeryLow` bug.

**Comment by samuelfangjw** [comment]
Ok thanks prof!
