### ISSUE TITLE
Are unexplainedcomponents bugs?

### ISSUE THREAD

**Issue by nowknowing** [nus-cs2103-AY2021S2/forum#322]
In DG, we did not explain certain components. Are missing component explanations bugs?
For instance, not explaining Common, which came from AB3.

**Comment by damithc** [comment]
OK to omit details if not important or if the omission doesn't hinder/misleads the reader.
Note how AB3 mentions the `Common` classes but doesn't go into details.
'came from AB3' is not a valid reason to omit though, as the reader doesn't know anything about AB3.

**Comment by nowknowing** [comment]
I see thank you!
