### ISSUE TITLE
Clarifications on a few bug scenarios

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#327]
Hello! I would like to make a few clarifications on whether the following could be considered legitimate bugs:

- Poor layout in UG due to negligence of the Web to PDF conversion process (i.e could have been fixed by inserting a page break but did not do so)

- Incomplete description in the DG manual testing section, whereby new and important command usages are not covered at all

- Screenshot containing accidental annotation that does not belong to the actual product screenshot

- Sequence diagram contains small font text that is impossible to read at A4 scale

- References to `AddressBook` in DG and Logging files due to no change in the actual class name in code, result in a mismatch of product name and use of the term `AddressBook` (as product no longer contains addresses). 

Would appreciate some advice since most of the above would not really hinder the usage of the application/guide.

Thank you!

**Comment by damithc** [comment]
> * Poor layout in UG due to negligence of the Web to PDF conversion process (i.e could have been fixed by inserting a page break but did not do so)

Considered a bug only if the problem hinders the reader e.g., a diagram is sliced in the middle

> * Incomplete description in the DG manual testing section, whereby new and important command usages are not covered at all

Bug. 

> * Screenshot containing accidental annotation that does not belong to the actual product screenshot

Bug.

> * Sequence diagram contains small font text that is impossible to read at A4 scale

Bug.

> * References to `AddressBook` in DG and Logging files due to no change in the actual class name in code, result in a mismatch of product name and use of the term `AddressBook` (as product no longer contains addresses).

Bug, if it can result in confusion in the mind of the reader (might be OK if the product hasn't diverged far from AB3). Also note that we made renaming of packages optional.


For all above, severity is case-by-case, depending on the impact on the user/reader.
