### ISSUE TITLE
Sequence diagram: static method call class name should not include colon?

### ISSUE THREAD

**Issue by swayongshen** [nus-cs2103-AY2021S2/forum#329]
Since we are making a static method call and there is no object involved shouldn't it exclude the colon? 

![image](https://user-images.githubusercontent.com/52824657/115333174-c7f3aa80-a1cb-11eb-9035-43ac66cd4aaf.png)

**Comment by damithc** [comment]
Good point. There doesn't seem to be a consensus on this. Let's stick with the colon (for this module) as that's the convention we have chosen.
