### ISSUE TITLE
Tag is shown in sourcetree but not pushed to remote repo

### ISSUE THREAD

**Issue by yanlingkuek** [nus-cs2103-AY2021S2/forum#33]
I have already tagged my commits before pushing them to my remote repo. All of my commits are all up on github, but in the ip progress dashboard, it says that all of my tags are not found in the fork. may I know I did something wrong or why my tags were not pushed for some reason?

**Comment by Cp-John** [comment]
Did you push the tags to your remote repo?
`git push origin <tag name>`

**Comment by damithc** [comment]
Thanks @Cp-John for the inputs.
@yanlingkuek did @Cp-John's reply solve your problem?
