### ISSUE TITLE
PE dev responses cannot be seen

### ISSUE THREAD

**Issue by nowknowing** [nus-cs2103-AY2021S2/forum#330]
![image](https://user-images.githubusercontent.com/49021362/115336435-d2b13e00-a1d1-11eb-9ae4-d0939ab228d1.png)

Hi prof,
I'm facing a situation as such where all the attached images I cannot see.
What might you suggest could be done?
Thank you

**Comment by damithc** [comment]
@nowknowing sorry, forgot to transfer the images. How about now?

**Comment by nowknowing** [comment]
Yes working thank you!
