### ISSUE TITLE
How to find out the status of the original bug for duplicated issues?

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#331]
As per the screenshot below, my bug report is tagged as duplicate but the team's response to the original bug is "no response provided"... In this case how do I know if the team has accepted the original bug, and therefore my bug report, or otherwise?
![image](https://user-images.githubusercontent.com/41845017/115339142-c24f9200-a1d6-11eb-9be8-40557da65b71.png)

**Comment by damithc** [comment]
A cluster of duplicates 'inherit' the type/severity/response labels from the 'original'. So, the team's response in terms of type/severity/response labels communicated back to you apply to both the duplicate (i.e., your bug) and the original. 
For example, if CATcher says the team accepted your bug, what that means is the team accepted the original bug and by extension, your bug as well.

**Comment by tlylt** [comment]
Hi prof, in this case, the team appears to reject the bug report without any explanation. So do I still need to reiterate what was said if I think that the report is valid?

**Comment by damithc** [comment]
Dev team not giving an explanation works in your favor, but you are welcome to add further arguments (if any) on why this is a valid bug.

**Comment by tlylt** [comment]
Ok thanks prof.
