### ISSUE TITLE
Is "implementation choice" and "ease of execution while developing" considered a valid reason for justifying a potential feature flaw?

### ISSUE THREAD

**Issue by umergta** [nus-cs2103-AY2021S2/forum#332]
Hi all, 

I reported a feature flaw related to them having extra commands that won't help users. However, in their reply, they stated that this was "an implementation choice" and that "it was convenient to develop this way"

Is this a valid justification? Personally, it is not a valid justification if it hinders the user's experience and leaves them pondering why there are 2 commands for essentially the same functionality.

**Comment by damithc** [comment]
> Is this a valid justification? Personally, it is not a valid justification if it hinders the user's experience and leaves them pondering why there are 2 commands for essentially the same functionality.

Yes, you can object to that response if you think **with the same amount of effort** they could have implemented the product to be friendlier (or more useful) to the target user.

**Comment by umergta** [comment]
ok noted. Thank you for the prompt reply prof Damith!
