### ISSUE TITLE
How do we change the bug severity through CATcher

### ISSUE THREAD

**Issue by ong6** [nus-cs2103-AY2021S2/forum#335]
Are we allowed to change the bug severity through CATcher? (Can't seem to find out how) 

Or are we supposed to just state it down in the issue response section?

**Comment by damithc** [comment]
@ong6 The latter.
Changing the severity directly is not possible at this stage.
If a tester wants to propose a new severity different from the original and the one proposed by the dev team, they need to state it in their response.

**Comment by ong6** [comment]
Ok thanks prof.
