### ISSUE TITLE
Clarification on more bugs scenarios

### ISSUE THREAD

**Issue by ong6** [nus-cs2103-AY2021S2/forum#336]
Following from #327, I would like to make a few more clarifications:

- Difference in target audience from DG and UG
- UG commands not explained clearly, missing or lacking information.
- 2 Commands doing roughly the same thing, but with different command names
- Major typo in UG causing confusion regarding how the app is supposed to work (Can this be medium?)
- Unable to view the full error message in the application command output window. (Not suited for fast typists as they have to lift their hands off the keyboard and scroll to view the error message) 
- UI elements that change colour or react to them when clicked, but does nothing in the app itself. (Expecting a change in something, but nothing happens)

Would appreciate some advice on these bugs.

Thank you!

**Comment by damithc** [comment]
> * Difference in target audience from DG and UG

Can elaborate more?

> * UG commands not explained clearly, missing or lacking information.
> * Major typo in UG causing confusion regarding how the app is supposed to work (Can this be medium?)
> * UI elements that change colour or react to them when clicked, but does nothing in the app itself. (Expecting a change in something, but nothing happens)

Yes, but the severity depends on how much each hinders the user/reader. 

> * Unable to view the full error message in the application command output window. (Not suited for fast typists as they have to lift their hands off the keyboard and scroll to view the error message)

Not a bug if the error message is expected to be rare. It is not a strict requirement that the user keeps hands on the keyboard all the time. At least, can be categorized `NotInScope` (i.e., to be improved upon later).


> * 2 Commands doing roughly the same thing, but with different command names

Can be argued a feature-flaw as the effort could have been spent on something more useful.

**Comment by ong6** [comment]
> Can elaborate more?

@damithc 

In the UG they say its for audience A 

But in the DG they say it's for audience B

Thus there is a contradiction. 

Would this be considered a bug?

**Comment by damithc** [comment]
> In the UG they say its for audience A
> 
> But in the DG they say it's for audience B
> 
> Thus there is a contradiction.
> 
> Would this be considered a bug?

Not sure what `it` refer to :-)

Yes, it's a bug if the UG says the product is meant for audience X and the DG says the product is meant for Y. 

Of course the UG itself is meant for users and the DG is meant for developers i.e., different target audience. That's not a problem.
