### ISSUE TITLE
Adding more evidence as tester response

### ISSUE THREAD

**Issue by totoyoyo** [nus-cs2103-AY2021S2/forum#339]
Hello!

During the PE tester response phase (now), if a bug report was disputed, is the tester supposed to go find more evidence in support of the same bug? i.e. go back to the program/UG/DG and take more screenshots as evidence. 

If not, how should the testers argue against the developers' responses?

**Comment by damithc** [comment]
Discouraged in general. Reason: doing so is unfair to the dev team as they never had a chance to see that additional evidence before they gave their response.

But if you think the situation calls for an exception  to the above (e.g., you provided enough evidence in the initial bug report but the dev team still says the evidence is not enough), go ahead and add more evidence or strengthen previous evidence. The teaching team will consider those additional evidence at their discretion, if not unfair to the dev team.
