### ISSUE TITLE
Question regarding tagging after merging

### ISSUE THREAD

**Issue by eksinyue** [nus-cs2103-AY2021S2/forum#34]
Hi,

I have merged `branch-Level-8` after `branch-Level-7` into the master. However, some of my `Level-8` changes result in `Level-7` changes to fail. Hence, after the merge commit of `branch-Level-8`, my code will not run due to errors. Should I still tag the merge commit of `branch-Level-8` as `Level-8` or should I tag the commit where I fix all the errors?

Here is the instruction from the module website.

![image](https://user-images.githubusercontent.com/58699564/105573417-696b8b80-5d98-11eb-8c2e-e28ebd86d323.png)

Thank you!!

**Comment by tjtanjin** [comment]
Based on what Prof Damith said [here](https://github.com/nus-cs2103-AY2021S2/forum/issues/24#issuecomment-764187044), I think the tags are for us to measure our own progress. My own branches weren't error free when I pushed them but I tagged them anyways :3

**Comment by damithc** [comment]
Thanks @tjtanjin for the reply
Yes, you can tag the commit at which you _think_ you are done with the increment (doesn't have to be the merge commit either). If it turns out there's more to do, just do them in future commits. No need to tag again. But you are welcome to move the tag to a future commit, if you can figure out how to do it.

**Comment by litone01** [comment]
Maybe I can share a bit about how to move the tag to the future commits in case anyone is curious. Personally I find it easier to be done via SourceTree. It is essentially just **deleting the old tag and create a new one**:)

1. Click on the commit with the tag you wanted to move. 
2. Right click and click on tag to open the dialog where you created the tag.
3. Click on "remove tag" and select the tag you wish to change. I find it useful to also check the "remove tag for all remotes".
![image](https://user-images.githubusercontent.com/56266729/105579102-5c15c780-5dbf-11eb-811d-1b2deedd1a1a.png)
4. After removing the tags, just select the more recent commit and create the tag for it. And then your tag is **'moved'** there!
5. However, do note that these changes may **distort your ordering of tags** when u click on 'tags' page for your forked project on Github. For example, mine looks like this now T_T Even though the commit with tags "A-Enums", "level-2" and "level-4" are older than that for "A-TextUiTesting", these tags are still behind them.   
![image](https://user-images.githubusercontent.com/56266729/105579237-3b01a680-5dc0-11eb-9a5a-50250f207bdf.png)

Hope this can help anyone:)

**Comment by damithc** [comment]
Thanks @litone01 for sharing this info.

**Comment by w2vgd** [comment]
Thanks @litone01 for sharing, and maybe I can add on by sharing how to add/remove past tags from both github and your local repo through the command line.
`git push --delete origin <tag_name>` : removes the tag from the remote repo (github)
`git tag --delete <tag_name>` : removes the tag from your own local repo
`git tag -a <tag_name> <commit_SHA1_hash>` : to manually tag a commit (as compared to `git tag -a <tag_name>` which tags the latest commit only). Note that the SHA1 hash of a commit is a 40-character hash that is computed every time you make a commit, and also you only need to specify around the first 8 of the characters of the hash
An example:
![image](https://user-images.githubusercontent.com/65358857/105580274-65eef900-5dc6-11eb-926a-0a8428996d81.png)
(an example tag command could be `git tag -a Level-8 c0b35c1a`)

Do note that deleting tag in either the remote or local repo does not remove the tag in the other. You have to run both the commands to remove a tag completely from both remote and local repo if you want.

**Comment by damithc** [comment]
@litone01 @w2vgd  Perhaps one of you can post the 'How to move a tag to a different commit' as a separate issue, so that it becomes more visible to others?

**Comment by w2vgd** [comment]
Sure Prof, I'll open a new issue now.

**Comment by eksinyue** [comment]
Thank you @tjtanjin @litone01 @w2vgd for the help!! Will close this issue now!!
