### ISSUE TITLE
Practice exam question bug

### ISSUE THREAD

**Issue by fairyinabottle4** [nus-cs2103-AY2021S2/forum#340]
Hi, I would like to report a bug with one of the practice exam questions. As you can see in the screenshot below, I was wrongly penalised for selecting line 3, even though the comments below also said that the answer is line 3

![image](https://user-images.githubusercontent.com/46418515/115490093-faff7200-a28f-11eb-9d65-8dd5ade2948a.png)

**Comment by damithc** [comment]
Doesn't the question say 'how many lines'?

**Comment by fairyinabottle4** [comment]
Sorry, read the question wrongly. I think I only saw the justification question
