### ISSUE TITLE
Additional Whitespace 

### ISSUE THREAD

**Issue by hengyongming** [nus-cs2103-AY2021S2/forum#342]
Hi Prof, 

Just wanna ask if this constitutes a bug.

Let's say a product disable adding a new task if the name is the same.
If I add test[space]1 and test[space][space]1, it will be added.

However, the tester is arguing users can make a typo and include additional whitespace that is not intended. This means that the 2 tasks are the same task and should not be added.

I feel that this shouldn't be a bug as we cannot be sure if the whitespace is intended and we provide a delete task functionality if users want to delete that task.

Thanks in advance prof!

**Comment by damithc** [comment]
I think the tester raises a fair point. If two item names differ only by spaces, it is very likely to be a typo. Therefore, detecting and blocking such situations can be useful to the user. 
But as you mentioned, there is also a theoretical possibility (although VERY unlikely) that the extra space is intended.
Hence, it is even better if the user is given a warning and allowed either option.
That said, this is a nice-to-have enhancement that you can argue to be `NotInScope` for the current version.

**Comment by hengyongming** [comment]
@damithc Thanks for the reply Prof.

Just a follow-up question, at this point in time, I cannot argue for `NotInScope` since I rejected it in the developer phase.

Will the marker take a look at it and change it to `NotInScope`  or will he/she just accept the bug as it is?

**Comment by damithc** [comment]
> Will the marker take a look at it and change it to `NotInScope` ?

That's what is expected to happen but slight variations are possible given human judgement is involved. The probability could have been higher if you argued for `NotInScope` in the first place.

**Comment by hengyongming** [comment]
@damithc Understood Prof, thank you so much for your response!
