### ISSUE TITLE
Clarifications on the difference between Transaction Processing and Event-driven architectural style

### ISSUE THREAD

**Issue by yienyoong** [nus-cs2103-AY2021S2/forum#343]
Transaction Processing:
https://nus-cs2103-ay2021s2.github.io/website/se-book-adapted/chapters/architecture.html#transaction-processing-architectural-style

Event-driven:
https://nus-cs2103-ay2021s2.github.io/website/se-book-adapted/chapters/architecture.html#event-driven-architectural-style

After studying these two architectural styles for some time, I am still unable to understand the differences between the two. From what I understand so far, they work the same way just that event-driven is specific to *events*, whereby events have a certain definition.

Could someone shed some light regarding the differences? If possible, maybe in relation to examples either from the textbook or further examples?

Thank you in advance!

**Comment by damithc** [comment]
Related (from the previous semester) https://github.com/nus-cs2103-AY2021S1/forum/issues/489

**Comment by yienyoong** [comment]
@damithc Thank you so much for the reply. 

I think I understand but just to clarify again, the architectures work the same way but one works with events (requiring listeners/observers) and one works with transactions (which exhibit different behaviours from events). Am I right to say this?

**Comment by damithc** [comment]
> I think I understand but just to clarify again, the architectures work the same way but one works with events (requiring listeners/observers) and one works with transactions (which exhibit different behaviours from events). Am I right to say this?

Yes. More like the two _looks_ the same, but works differently.

**Comment by yienyoong** [comment]
> > I think I understand but just to clarify again, the architectures work the same way but one works with events (requiring listeners/observers) and one works with transactions (which exhibit different behaviours from events). Am I right to say this?
> 
> Yes. More like the two _looks_ the same, but works differently.

I understand. Thank you Prof!

I will leave this issue open for a while longer for any discussion.
