### ISSUE TITLE
Clarification on final readiness quiz q7 and q19

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [nus-cs2103-AY2021S2/forum#344]
For question 7, I'm not sure if we are allowed to wear headphones for the finals since the general comments stated that it is allowed for PE and the final exam SOP on the module website did not mention anything about headphones.

For question 19, wouldn't the answer be false since the part II diagrams have to be uploaded within an hour as stated in the module website SOP while the question itself specified within 30 minutes?

**Comment by damithc** [comment]
Thanks @yhtMinceraft1010X for the bug reports.

> For question 7, I'm not sure if we are allowed to wear headphones for the finals since the general comments stated that it is allowed for PE and the final exam SOP on the module website did not mention anything about headphones.

Allowed. I'll update the website.


> For question 19, wouldn't the answer be false since the part II diagrams have to be uploaded within an hour as stated in the module website SOP while the question itself specified within 30 minutes?

You are right. I've updated the question 30 minutes -> 1 hour.

**Comment by tlylt** [comment]
Would like to just highlight this small typo in the exam survey as well (from copy pasting? .-.)
- should be during Exam cos PE is over
![image](https://user-images.githubusercontent.com/41845017/115647595-9f4bec00-a356-11eb-81f7-d31ce425d94c.png)

**Comment by damithc** [comment]
> Would like to just highlight this small typo in the exam survey as well (from copy pasting? .-.)

Thnks @tlylt 
Fixed.
