### ISSUE TITLE
A question about Practice Exam question.

### ISSUE THREAD

**Issue by skinnychenpi** [nus-cs2103-AY2021S2/forum#345]
![image](https://user-images.githubusercontent.com/35286219/115570930-18b0f380-a2f1-11eb-87ac-6bb7b4fc9de3.png)
Hi, may I ask why Moo has to be declared as abstract class? I thought that only Foo is abstract. Any clarification on this?

**Comment by ong6** [comment]
> Moo has to be declared as an abstract class?

I think you may have a typo in your question? Were you trying to ask why the code causes a compile error instead?

**Comment by tlylt** [comment]
If `Moo` is not declared as abstract class, then it has to implement the `store` method from the `Goo` interface. Hope this clarifies:)

**Comment by skinnychenpi** [comment]
> If `Moo` is not declared as abstract class, then it has to implement the `store` method from the `Goo` interface. Hope this clarifies:)

Ahh thanks for the reply. I see what's going on here.
