### ISSUE TITLE
Clarification for Class diagram - Person, Inbox, Message

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#346]
For this exercise on class diagram, is it ok to
- state multiplicity of `Message` as * (from Inbox)
- state multiplicity of `Inbox` as 1 (from Person)
- make `Message` and its `read` method abstract?
![image](https://user-images.githubusercontent.com/41845017/115646899-8f7fd800-a355-11eb-9c22-b7d9e4ce16a3.png)

**Comment by damithc** [comment]
In general, it is safer not to put something into the diagram unless there is clear evidence of its existence.

> * state multiplicity of `Message` as * (from Inbox)

Should be OK. Although the description doesn't mention this specifically, we can't expect it to be anything else.

> * state multiplicity of `Inbox` as 1 (from Person)

I would be vary of using `1` unless there is a strong indication to support that it has to be _exactly one_. 

> * make `Message` and its `read` method abstract?

There is no indication in the description that they are. Of course if there is code, we can check and choose accordingly.

In all three cases above, either way should not affect exam marks though.

**Comment by tlylt** [comment]
Roger, thanks prof.
