### ISSUE TITLE
practice paper 1 question 8

### ISSUE THREAD

**Issue by prerthan99** [nus-cs2103-AY2021S2/forum#347]
![Screenshot 2021-04-22 at 3 16 03 PM](https://user-images.githubusercontent.com/54735177/115672740-6fb0da00-a37e-11eb-9478-6ecf8530c6c9.jpg)

why is "reading" not considered a 'magic value'.  shouldn't we name it something like waitingMessage = "reading" or something?  thanks in advance

**Comment by tlylt** [comment]
Hello, perhaps this question is focusing on the coding standard as in [coding style](https://se-education.org/guides/conventions/java/intermediate.html), instead of other aspects of code quality (E.g magic literals).

**Comment by prerthan99** [comment]
ic, thank you.  I think I conflated the 2
