### ISSUE TITLE
Mock exam query

### ISSUE THREAD

**Issue by prerthan99** [nus-cs2103-AY2021S2/forum#348]
![Screenshot 2021-04-22 at 3 16 41 PM](https://user-images.githubusercontent.com/54735177/115673011-b9012980-a37e-11eb-90cd-d997bc9497e7.jpg)

Why is the option "we should aim to achieve zero coupling" the wrong option?  I believe the question is which of the following are not correct.  My point is even though we know that we cannot achieve achieve zero coupling, shouldn't we at least aim for zero.  even though we cant reach it, at least we can reduce it as much as possible.  I was thinking it was something like asymptotic, where we can never reach it but at least get as close as possible?  thanks

**Comment by tlylt** [comment]
Hello, perhaps this is a case of choosing the most appropriate option listed, of the 5 I think the first one about zero coupling seems to be the least reasonable opinion. (Sorry haven't attempted it yet so not sure what the question is asking for).

**Comment by damithc** [comment]
Yes @prerthan99, this option can cause doubts. Keep in mind that we can't even get _close_ to zero coupling (imagine a design where no classes depend on any other class!).  As @tlylt mentions, it's the best choice among the given options.

Anyway, I've rephrased that option as follows, to remove this doubt.
`We can achieve zero coupling if we do a good job with the design.`

**Comment by prerthan99** [comment]
noted, that makes sense.  thanks @damithc and @tlylt :)
