### ISSUE TITLE
Mock Exam Query - Error Counting Question

### ISSUE THREAD

**Issue by ZhangAnli** [nus-cs2103-AY2021S2/forum#349]
Can I just clarify on how we can tell whether this is considered as one/two error? 

From my side, I just viewed the error as the activation bar being too long, so 1 error. 
However, the answer replies saying that it is too long on BOTH ends, so counts as 2 errors. 

May I get the teaching team's input on this and recommendation in the final exam? 

<img width="1232" alt="Screen Shot 2021-04-22 at 8 10 50 PM" src="https://user-images.githubusercontent.com/65236091/115712068-e661cd80-a3a6-11eb-984c-3110d60dd656.png">

<img width="1186" alt="Screen Shot 2021-04-22 at 8 11 31 PM" src="https://user-images.githubusercontent.com/65236091/115712297-2de85980-a3a7-11eb-9cbc-d1e8f1205280.png">

**Comment by damithc** [comment]
The two things are independent. Hence, two errors. If the same thing comes up in the actual exam, now you know how to count them :-)

**Comment by ZhangAnli** [comment]
Okay, thanks Prof! :)
