### ISSUE TITLE
How stringent is A-MoreOOP class names requirement

### ISSUE THREAD

**Issue by rajobasu** [nus-cs2103-AY2021S2/forum#35]
My code already has everything divided/uses slightly differences from the given OOP structure under A-MoreOOP. 
Do I need to change and refactor everything to match the given classnames and OOP-structure? Or is that more of a guideline?

**Comment by damithc** [comment]
@rajobasu It's just for guidance. If you think your design is just as good (or even better), there is no need to change.

**Comment by rajobasu** [comment]
Okay, thank you prof!
