### ISSUE TITLE
Coupling and code quality

### ISSUE THREAD

**Issue by IceBear789** [nus-cs2103-AY2021S2/forum#350]
![Screenshot](https://user-images.githubusercontent.com/75657814/115717766-12804d00-a3ad-11eb-939a-48ee031477d7.png)
The model answer states that magic literals and coupling reduces code quality.

But isn't coupling more of a design issue? In the textbook coupling is also located under the section "Design fundamentals" instead of the section "Code quality".

**Comment by damithc** [comment]
I've revised it as `How many of these are to be avoided/minimized?`

**Comment by IceBear789** [comment]
Ok, thanks prof.
