### ISSUE TITLE
text book exercise example

### ISSUE THREAD

**Issue by prerthan99** [nus-cs2103-AY2021S2/forum#353]
given the question below, are the 2 diagrams correct and equivalent?  If so, how can we show visibility (private, public, static) in the first option.  and also, how do we show that the expected output type for open is void? Is it open() = void ?

Question: 
![Screenshot 2021-04-23 at 11 30 51 AM](https://user-images.githubusercontent.com/54735177/115814549-e2c25b00-a427-11eb-9184-8d25e474dbdc.jpg)

Ans: 
![Screenshot 2021-04-23 at 11 35 08 AM](https://user-images.githubusercontent.com/54735177/115814613-fe2d6600-a427-11eb-96bf-091aaee3a51a.jpg)

**Comment by tlylt** [comment]
Thanks for sharing!
- multiplicity
  - lid and box (outerbox as well), item is wrong, given that they are variables, it should be 0..1, and not *
  - parts should be 0..10
- totalItems is not an association to itself, it is just a class variable
- also the question does not require the visibility

edit: see https://github.com/nus-cs2103-AY2021S2/forum/issues/352#issue-865050502, there is a video in week 8 or 9 that goes through the design process for this exact question

**Comment by damithc** [comment]
To add, it's not possible to show visibility for associations shown as lines (within the scope of notations we cover in the module). Visibility is not that important anyway (compared to showing relationships between classes). Option 1 is still more useful than option 2 as a _visual_ model of the design even if it doesn't show visibility.

**Comment by prerthan99** [comment]
i was wondering if the arrow linking Box and lid should be bidirectional
eg:
lid 0..1 <------------------------> box 0..1?
thank you

**Comment by tlylt** [comment]
@prerthan99 
![image](https://user-images.githubusercontent.com/41845017/115843050-04840800-a451-11eb-8268-a801afdd7f29.png)

**Comment by prerthan99** [comment]
ah ok.  thank you.
