### ISSUE TITLE
Exam Readiness Quiz Closed Early

### ISSUE THREAD

**Issue by BenedictBCJJ** [nus-cs2103-AY2021S2/forum#354]
The exam readiness quiz is closed before the deadline? 
![image](https://user-images.githubusercontent.com/52716670/115819967-7e58c900-a432-11eb-944b-27f327aa86b3.png)

Theres also an error in the description of the quiz. It says PE instead of finals.
![image](https://user-images.githubusercontent.com/52716670/115819934-6d0fbc80-a432-11eb-8618-db16018a3c8e.png)

**Comment by damithc** [comment]
Opps. Reopened. Thanks @BenedictBCJJ for letting me know.
