### ISSUE TITLE
Clarification on allowed materials for Final Exam

### ISSUE THREAD

**Issue by hengyiqun** [nus-cs2103-AY2021S2/forum#355]
I have read the exam website (https://nus-cs2103-ay2021s2.github.io/website/admin/exams.html), and I see the following line:

> "The Browser should only be used to access LumiNUS and the module website."

I would like to clarify if the module website includes the se-education website (i.e. https://se-education.org/guides/index.html) or if it just refers to the main module website (https://nus-cs2103-ay2021s2.github.io/website/index.html).

Thank you!

**Comment by damithc** [comment]
> I would like to clarify if the module website includes the se-education website (i.e. https://se-education.org/guides/index.html) or if it just refers to the main module website (https://nus-cs2103-ay2021s2.github.io/website/index.html).

Yes, https://se-education.org pages referenced within the module website are fine too.

**Comment by hengyiqun** [comment]
Thank you very much for the prompt response!
