### ISSUE TITLE
Object Diagram when to use aggregation

### ISSUE THREAD

**Issue by justgnohUG** [nus-cs2103-AY2021S2/forum#356]
From these 2 code blocks in Week 8 Tutorial,

![image](https://user-images.githubusercontent.com/77429783/115826552-aac61280-a43d-11eb-9cf7-3252a222ac32.png)

![image](https://user-images.githubusercontent.com/77429783/115826565-b0bbf380-a43d-11eb-9945-a9a643405f3d.png)

(`Stock Item` code block is included for relevancy)
![image](https://user-images.githubusercontent.com/77429783/115827372-c847ac00-a43e-11eb-8eed-6fbb903c1eb4.png)

**Alternatively, visit https://nus-cs2103-ay2021s2.github.io/website/schedule/week8/tutorial.html for full context.**

**The Actual Question**
I would like to clarify the relationship between `Item` and `Inventory`. 

Given that `Inventory` has a `List<Item>` reference, I was wondering if Aggregation is possible here in the **Object Diagram**

![image](https://user-images.githubusercontent.com/77429783/115828165-e9f56300-a43f-11eb-812e-19a649f6c9e8.png)

PS: Diagram updated as aggregation direction was incorrect initially.

**Comment by damithc** [comment]
Yes, you can. That said, do note that we recommend not to use aggregation at all, in class or object diagrams. Aggregation doesn't add much value; it's just noise.

**Comment by justgnohUG** [comment]
Thank you for the reply Prof @damithc,

That said, I would think most of the time in the Exam especially, aggregation can be substituted for other forms of association, and a need for aggregation would be close to unnecessary? 

Not trying to sniff out Exam questions, but more curious of the situations we would ever be "forced" to utilize aggregation.

**Comment by damithc** [comment]
In the exam, we do not expect you to use aggregation symbol when drawing class/object diagrams. However, you should still be able to interpret the aggregation symbol in a given diagram.
