### ISSUE TITLE
Are we allowed to refer to our own notes/screenshots?

### ISSUE THREAD

**Issue by jlxw48** [nus-cs2103-AY2021S2/forum#358]
As per title. I noticed that the email sent in Week 13 only states the following: 

![image](https://user-images.githubusercontent.com/65431768/115832678-be757700-a445-11eb-83fc-62eda39bf76f.png)

Hence, I would like to clarify if we are allowed to open OneNote/other PDFs/image files etc.

Thank you!

**Comment by damithc** [comment]
Only PDF files. If you have notes in other formats, convert to PDF format first.

**Comment by jlxw48** [comment]
Okay thank you!
