### ISSUE TITLE
Multiple Association/Association roles?

### ISSUE THREAD

**Issue by yienyoong** [nus-cs2103-AY2021S2/forum#361]
What if a scenario, for example, a person can like another person, a person can also hate another person, occurs. How would the association be drawn? Is it a single association? Or would it be represented as 2 associations? I am unsure as to how I would label roles if it was a single association. 

![image](https://user-images.githubusercontent.com/65435255/115864123-08bc1f80-a469-11eb-81ba-2b4f0c83e3bb.png)

**Comment by damithc** [comment]
If _likes_ and _hates_ are two different relationships (I think they are), they should be two different associations. That way, a person can like one (or more) person, hate another person, and even like_and_ hate yet another person.

**Comment by yienyoong** [comment]
Thank you Prof!
