### ISSUE TITLE
Quiz 7 q1

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#365]
![image](https://user-images.githubusercontent.com/65358857/115886438-82610700-a483-11eb-9ba4-4d1d9c0b75bd.png)

![image](https://user-images.githubusercontent.com/65358857/115886561-a3295c80-a483-11eb-9bad-e89314139e52.png)

Hi, why is the answer for this question "no"? Should it not be "yes" because everything below is optional?

**Comment by damithc** [comment]
You are right @w2vgd. Corrected it just now.
