### ISSUE TITLE
When does freeze period end?

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [nus-cs2103-AY2021S2/forum#369]
I'm not sure if its tomorrow or Tuesday, since the mod website says 14 days after deadline, which would make it 26 April at 2359. 

Also, are we allowed to delete our existing tp forks? I wish to start a new brownfield project from the original AB3 code.

**Comment by damithc** [comment]
> I'm not sure if its tomorrow or Tuesday, since the mod website says 14 days after deadline, which would make it 26 April at 2359.

Apr 26th 23.59


> Also, are we allowed to delete our existing tp forks? I wish to start a new brownfield project from the original AB3 code.

Best not to, at least until exam results are released.
To use another copy of AB3, do the following (instead of forking directly from AB3):
1. Create an empty repo in your GitHub account
2. Clone AB3 to your computer
3. Push the local repo to the empty GitHub repo

**Comment by yhtMinceraft1010X** [comment]
Thanks Prof!
