### ISSUE TITLE
Is there any way to change the user.dir?

### ISSUE THREAD

**Issue by kaixiangtay** [nus-cs2103-AY2021S2/forum#37]
By using the command System.getProperty("user.dir") with other different commands I found online, I could only obtain the current user.dir : "../Duke Project/src/main/java"

However, my intended user.dir should be "../Duke Project" only and not nested all the way to the java folder inside the src folder.

**Comment by rajobasu** [comment]
https://stackoverflow.com/questions/17211066/intellij-idea-module-default-user-dir

Does this help?
