### ISSUE TITLE
Does reimplementing an idea from our own iP count as reuse?

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [nus-cs2103-AY2021S2/forum#370]
Example scenario:
- I added functionality for marking a task as done and notdone in my own iP project
- I then implemented the same functionality for my team's tP project
- Although the basic concept behind this functionality is the same, the code is structured differently to be more in line with the code for original AB3 commands/other members' tP code

To be safe, I credited my own iP github in my tP PPP page.

**Comment by damithc** [comment]
OK to reuse own code from the iP.

**Comment by yhtMinceraft1010X** [comment]
Thanks Prof!
