### ISSUE TITLE
module's coding standard

### ISSUE THREAD

**Issue by maikongeh** [nus-cs2103-AY2021S2/forum#38]
Does anyone know where to find the module's coding standard?

**Comment by lirc572** [comment]
The coding conventions can be found here:

<https://se-education.org/guides/conventions/java/intermediate.html>

From the module's website: Other Links -> Java Coding Standard

**Comment by figo2127** [comment]
This could also be helpful:

https://se-education.org/guides/conventions/git.html

It highlights some git naming conventions etc.

**Comment by damithc** [comment]
A slide from the recent lecture:
![image](https://user-images.githubusercontent.com/1673303/105633333-e67b2b80-5e92-11eb-9639-dbc4f8711ebd.png)

**Comment by GabrielSimbingyang** [comment]
Hi @maikongeh ,

Just a gentle reminder to close the issue if it has been solved (= If you still have more queries, feel free to continue the thread / start a new issue. Thanks!
