### ISSUE TITLE
Regarding pushing after merging branch to master

### ISSUE THREAD

**Issue by figo2127** [nus-cs2103-AY2021S2/forum#39]
![image](https://user-images.githubusercontent.com/61351392/105633215-402f2600-5e92-11eb-8219-e2abc2a6905b.png)
Dear Friends,

Right after merging your branch to your master branch, did you get a notification "2" as seen on the push button on top. May I know why is that the case since I already pushed to my branch before merging with master.

Apologies for the inconvenience. Thanks in advance!

**Comment by lirc572** [comment]
I think it's because you have not pushed the changes on local master branch to the remote master branch (so the local master branch is 2 comits ahead of the remote master branch)

**Comment by SoonKeatNeo** [comment]
Probably because of inconsistency between your local git copy and the remote GitHub copy?

**Comment by figo2127** [comment]
I created a PR to merge to master, and my local copy seems to be the same as the remote copy. The "2" is still there though.

**Comment by damithc** [comment]
> I created a PR to merge to master, and my local copy seems to be the same as the remote copy. The "2" is still there though.

Do a `git push origin master` and see what happens.

**Comment by figo2127** [comment]
I think you guys are right, I merged the branches to master remotely but not on my local copy. Which means I need to pull before pushing due to the commit difference, because I ticked create new commit every time. I think that's the rough idea.

**Comment by GabrielSimbingyang** [comment]
Hi @figo2127 ,

Just a gentle reminder to close the issue if it has been solved (= If you still have more queries, feel free to continue the thread / start a new issue. Thanks!
