### ISSUE TITLE
Unicode characters not supported on Windows command prompt

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#4]
Hi, may I ask if the program output will only be graded in IntelliJ built-in console? I have noticed that IntelliJ supports printing of Unicode characters but Windows command prompt does not (as shown below). Or is there a way to fix this issue?

(From IntelliJ console)
![image](https://user-images.githubusercontent.com/65358857/104808244-d4a8e100-581f-11eb-923d-416087a9bfa3.png)
 
(From Windows command prompt)
![image](https://user-images.githubusercontent.com/65358857/104808305-46812a80-5820-11eb-9d12-3f1d1f3deadb.png)

Thank you.

**Comment by damithc** [comment]
> Hi, may I ask if the program output will only be graded in IntelliJ built-in console?

The product is meant to be used outside of the IDE. As the IDE is a developer tool, the target end users are unlikely to be using one.

**Comment by w2vgd** [comment]
> The product is meant to be used outside of the IDE. As the IDE is a developer tool, the target end users are unlikely to be using one.
Hi Prof, thanks for the clarification. There seems to be a workaround (using chcp 65001) but it involves the end users changing their system configuration. Since this will inconvenience the users, I think I shall just stick to using the normal hyphen (**-**) and not use Unicode characters. Thank you!

**Comment by damithc** [comment]
> Since this will inconvenience the users, I think I shall just stick to using the normal hyphen (**-**) and not use Unicode characters. Thank you!

Yup, that's a good decision. 👍
