### ISSUE TITLE
Unable to run jar file with 'java -jar ip.jar'

### ISSUE THREAD

**Issue by gycc7253** [nus-cs2103-AY2021S2/forum#46]
Hi all,
I've been trying to jar the project for quite a while but got stuck at this error.
![Screenshot (89)](https://user-images.githubusercontent.com/58676681/105736142-70002b80-5f6f-11eb-9399-913cee3f612c.png)

While my project directory and the file path is like this
![Screenshot (90)](https://user-images.githubusercontent.com/58676681/105736250-8e662700-5f6f-11eb-9a82-7470b9c7c204.png)

What I did with Storage class is
> public Storage(String filepath) {
        this.file = new File(filepath);
        FileReader fr;
        try {
            file.createNewFile();
     ...

Can someone please help, what is wrong with my jar? 
I guess there is something wrong with my file path, but I could not figure out why. I followed the steps of creating java jar in the tutorial given in A-Jar segment.
Thx a lot in advance!

**Comment by SoonKeatNeo** [comment]
From the file path and where you’re running the JAR from, I think the relative path there would imply that your duke.txt file is in: `...\Java\compileroutput\artifacts\ip_jar\src\data\duke.txt`, which I guess is not what you have set up? You can verify this if you create the src\data directory in ip_jar folder.

**Comment by gycc7253** [comment]
> From the file path and where you’re running the JAR from, I think the relative path there would imply that your duke.txt file is in: `...\Java\compileroutput\artifacts\ip_jar\src\data\duke.txt`, which I guess is not what you have set up? You can verify this if you create the src\data directory in ip_jar folder.

Hi thx!
I don't have a ip_jar\src folder at all, I just went to check the jar structure and it looks like this
ip.jar
->data
->->duke.txt
->main
->->java
->->->...all classes etc
->META-INF
btw, may i clarify what do you mean by create the src\data directory in ip_jar folder?
Thx again!

**Comment by tjtanjin** [comment]
@gycc7253 You might need to check if the parent directory for your file actually exist before attempting to create it. For example, if you were creating a file as below, the data directory might not be present yet:
```
File file = new File("./data/tasks.txt");
```
In which case, you may need an extra line of code after that to create the data directory:
```
file.getParentFile().mkdirs();
```

**Comment by SoonKeatNeo** [comment]
> btw, may i clarify what do you mean by create the src\data directory in ip_jar folder?
> Thx again!

It looks like the file creation is failing because the src\data directory is not present in ip_jar folder. Which is why if you tried to create the aforementioned folders and it works, then you can implement the fixes that @tjtanjin has suggested :)

**Comment by gycc7253** [comment]
Thx a lot for the help guys!
Yes it solved the issue for me!

**Comment by danadi7** [comment]
@gycc7253 don't forget to close the issue! The `Close Issue` button should be in the reply dialog below, beside the `Comment` button. :)

**Comment by gycc7253** [comment]
@danadi7 thx for the reminder!
