### ISSUE TITLE
junit api not found even though it is installed

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#48]
Hi, followed the instructions in the [JUnit tutorial @se-edu/guides](https://se-education.org/guides/tutorials/junit.html) but somehow gotten a `package org.junit.jupiter.api does not exist` error even though I did follow the guide closely (the code is not highlighted red too).

Is it possible for someone to share how the `ip.iml` file and `test.iml` file should look like because I am not sure if what I have is correct after several attempts to fix stuff. (I think the issue might lie in here?)

Error:
![image](https://user-images.githubusercontent.com/65358857/105749687-b7da7f00-5f7e-11eb-941f-10c9950852f0.png)

My directory has the JUnit5.4 library as shown here
![image](https://user-images.githubusercontent.com/65358857/105749540-7ea20f00-5f7e-11eb-9afc-043171a49f7e.png)

**Comment by rajobasu** [comment]
<img width="330" alt="Screenshot 2021-01-26 at 2 39 49 AM" src="https://user-images.githubusercontent.com/34958324/105750486-c5443900-5f7f-11eb-8eea-eb6c80cf4c17.png">

ip.iml : 

```
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/src/main/java" isTestSource="false" />
      <sourceFolder url="file://$MODULE_DIR$/src/test/java" isTestSource="true" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="module-library" scope="TEST">
      <library name="JUnit4">
        <CLASSES>
          <root url="jar://$MAVEN_REPOSITORY$/junit/junit/4.12/junit-4.12.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar!/" />
        </CLASSES>
        <JAVADOC />
        <SOURCES />
      </library>
    </orderEntry>
    <orderEntry type="module-library" scope="TEST">
      <library name="JUnit5.4">
        <CLASSES>
          <root url="jar://$MAVEN_REPOSITORY$/org/junit/jupiter/junit-jupiter/5.4.2/junit-jupiter-5.4.2.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/junit/jupiter/junit-jupiter-api/5.4.2/junit-jupiter-api-5.4.2.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/opentest4j/opentest4j/1.1.1/opentest4j-1.1.1.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/junit/platform/junit-platform-commons/1.4.2/junit-platform-commons-1.4.2.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/junit/jupiter/junit-jupiter-params/5.4.2/junit-jupiter-params-5.4.2.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/junit/jupiter/junit-jupiter-engine/5.4.2/junit-jupiter-engine-5.4.2.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/junit/platform/junit-platform-engine/1.4.2/junit-platform-engine-1.4.2.jar!/" />
        </CLASSES>
        <JAVADOC />
        <SOURCES />
      </library>
    </orderEntry>
  </component>
</module>
```


test.iml : 
```
<?xml version="1.0" encoding="UTF-8"?>
<module type="WEB_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$" />
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>
```

**Comment by w2vgd** [comment]
Thanks @rajobasu. Can I ask if your junit tests are all working with this 2 files?
And also is it weird that the 
```
<CLASSES>
....
</CLASSES>
```
stuff that are present in your ip.iml file is actually inside my test.iml file? (kinda seem like the 2 files swapped contents for mine)

**Comment by tjtanjin** [comment]
If you need a third comparison, mine also looks flipped compared to @rajobasu.

**Comment by w2vgd** [comment]
> If you need a third comparison, mine also looks flipped compared to @rajobasu.

Hi @tjtanjin, would you mind sharing your version of the two files 😓?

**Comment by tjtanjin** [comment]
Sure thing @w2vgd!

ip.iml (sitting at the root directory of the project):
```
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/src/main/java" isTestSource="false" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" name="com.googlecode.json-simple:json-simple:1.1.1" level="project" />
  </component>
</module>
```

test.iml (sitting within the src/test folder):
```
<?xml version="1.0" encoding="UTF-8"?>
<module type="WEB_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/java" isTestSource="true" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="module-library" scope="TEST">
      <library name="JUnit5.4">
        <CLASSES>
          <root url="jar://$MAVEN_REPOSITORY$/org/junit/jupiter/junit-jupiter/5.4.2/junit-jupiter-5.4.2.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/junit/jupiter/junit-jupiter-api/5.4.2/junit-jupiter-api-5.4.2.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/opentest4j/opentest4j/1.1.1/opentest4j-1.1.1.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/junit/platform/junit-platform-commons/1.4.2/junit-platform-commons-1.4.2.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/junit/jupiter/junit-jupiter-params/5.4.2/junit-jupiter-params-5.4.2.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/junit/jupiter/junit-jupiter-engine/5.4.2/junit-jupiter-engine-5.4.2.jar!/" />
          <root url="jar://$MAVEN_REPOSITORY$/org/junit/platform/junit-platform-engine/1.4.2/junit-platform-engine-1.4.2.jar!/" />
        </CLASSES>
        <JAVADOC />
        <SOURCES />
      </library>
    </orderEntry>
    <orderEntry type="module" module-name="ip" scope="TEST" />
    <orderEntry type="library" scope="TEST" name="com.googlecode.json-simple:json-simple:1.1.1" level="project" />
  </component>
</module>
```
I have extra lines from using json-simple but the general structure should be similar (hopefully) :3

**Comment by w2vgd** [comment]
Thanks a lot for your help @tjtanjin!!! So I have compared my ip.iml file with yours and when I removed the line I highlighted (not even sure why it is there in the first place 😞) and ran my Test class again, it worked!!! 
![image](https://user-images.githubusercontent.com/65358857/105753437-a6e03c80-5f83-11eb-946f-20320a9135be.png)


Apart from the json orderEntry lines, everything else is the same for both files except that in my test.iml file, the 2nd line for mine is `<module type="JAVA_MODULE" version="4">` instead of your `<module type="WEB_MODULE" version="4">`. Not sure if this matters?

**Comment by tjtanjin** [comment]
Ahhh... I think I am starting to get how the `.iml` files work (I hope 😅). Just throwing out a hypothesis but it seems the `<sourceFolder>` tag specifies which modules the `.iml` file applies to. It should then technically be possible for a single `.iml` file to apply to multiple modules in a project (hence the multiple `<sourceFolder>` tag in your original `ip.iml`). Should that be true, it might be that `ip.iml` was taking priority (for whatever reason) over your `test.iml` file, hence triggering the error you saw. I am guessing it would also work if you copy the contents for `JUnit` from the `test.iml` file into `ip.iml` file but since it's working now I guess it's good xD

**Comment by w2vgd** [comment]
> Ahhh... I think I am starting to get how the `.iml` files work (I hope 😅). Just throwing out a hypothesis but it seems the `<sourceFolder>` tag specifies which modules the `.iml` file applies to. It should then technically be possible for a single `.iml` file to apply to multiple modules in a project (hence the multiple `<sourceFolder>` tag in your original `ip.iml`). Should that be true, it might be that `ip.iml` was taking priority (for whatever reason) over your `test.iml` file, hence triggering the error you saw. I am guessing it would also work if you copy the contents for `JUnit` from the `test.iml` file into `ip.iml` file but since it's working now I guess it's good xD

Ohh, I think your are right about the `<sourceFolder>` tag specifying which modules the contents of the `.iml` file affects. This explains why my previous version is not working. Thanks a lot for your help!!


In addition, does anyone know whether there is a difference between `<module type="JAVA_MODULE" version="4">` and `<module type="WEB_MODULE" version="4">`? Which of this is the correct version that we should have in our `test.iml` file?

**Comment by QY-H00** [comment]
Hi @w2vgd, here is one of the explaination on google. Maybe you could refer to it.

> Java modules are the simplest module type and represent a basic Java application project, whether it's a command-line tool, a Swing application, or a JAR library. When configuring this type of module, you can specify a set of Java source paths that will be compiled to a single class folder. The basic capabilities of this module are carried over into the web module.

> The web module is an extension of the Java module that adds support for web applications. In addition to providing the ability to create and build Java sources, it lets you edit your web application's deployment descriptor, build and deploy it to your application server, and configure other web application capabilities. You create a web module for each web application in your project.

On my own opinion, it seems that it doesn't matter for this project. JAVA_MODULE is enough to satisfy the requirement since WEB_MODULE is an extension of the JAVA_MODULE and we don't need any web applications so far. Hope this works!

**Comment by w2vgd** [comment]
> On my own opinion, it seems that it doesn't matter for this project. JAVA_MODULE is enough to satisfy the requirement since WEB_MODULE is an extension of the JAVA_MODULE and we don't need any web applications so far. Hope this works!

Thank you for the explanation.
