### ISSUE TITLE
Regarding .gitignore file

### ISSUE THREAD

**Issue by khiaxeng** [nus-cs2103-AY2021S2/forum#5]
![image](https://user-images.githubusercontent.com/58847287/104808496-a75d3280-5821-11eb-8944-3c0967f3fee3.png)

> To ignore it, follow the same steps you followed above when you set Git to ignore the temp.txt file.

Referring to the image above and the quoted text, it says to follow the same steps I did to ignore an unstaged file. However, in SourceTree, upon right-clicking the ".gitignore" file, there is no option to "Ignore" the file itself. 

What is the proper way of ignoring the ".gitignore" file?

**Comment by w2vgd** [comment]
I believe you can add ".gitignore" inside the _.gitignore_ file itself to ignore it (if the _.gitignore_ file has never been commited before). 
However, if the _.gitignore_ file has already been tracked previously, it will still show up in git status. One way to solve this can be to add the ignores to _.git/info/exclude_ in the repository instead. 
(Refer to https://stackoverflow.com/questions/10176875/add-gitignore-to-gitignore#:~:text=gitignore%20file's%20purpose%20is%20to,be%20included%20in%20the%20repository for more information)

As an aside, regarding the iP, I believe we should still commit the _.gitignore_ file actually.

**Comment by SoonKeatNeo** [comment]
gitignore only prevents files that has not been tracked previously to be ignored from tracking.

As the gitignore file itself has been tracked in the past, the option would not be available and, as above, should continue to be tracked.

If you DO want to stop git from tracking the gitignore file (not recommended), you'd need to right click and select the "Stop Tracking" option in SourceTree instead.

**Comment by tohyuting** [comment]
Hello @khiaxeng, I see that you have reacted with a thumbs up emoji for the replies above. Do remember to close this issue if your question has been resolved  :)

**Comment by khiaxeng** [comment]
Thank you for your clarifications! 
@tohyuting Noted, thank you!
