### ISSUE TITLE
Testing: Do we test private methods?

### ISSUE THREAD

**Issue by douglaswja** [nus-cs2103-AY2021S2/forum#51]
In the article: [Three pillars of Unit Tests](https://blog.aspiresys.pl/technology/three-pillars-of-unit-tests/) by the Aspire Blog Team the claim was made that needing to test private methods is "a sign of a bad design".
However, in the articles comments section people strongly disagreed with this, while others argued for it.

Could I check what the recommendation is for CS2103 when it comes to Private methods.

**Comment by damithc** [comment]
Good question @douglaswja 
There are some relevant links at the end of this topic https://nus-cs2103-ay2021s2.github.io/website/book/cppToJava/junit/basic/

Our usual stance apply here. i.e., There is no one right answer. Learn pros and cons, and choose case-by-case.
