### ISSUE TITLE
Running Jar File gives (The system cannot find the path specified) but works when running in IntelliJ

### ISSUE THREAD

**Issue by zhoube** [nus-cs2103-AY2021S2/forum#52]
When I run my code on IntelliJ, it is able to read and write data into the .txt file normally

But when running it using .jar, it shows `(The system cannot find the path specified)` as error. 

P.S. My code for the file path is
`java.nio.file.Path path = java.nio.file.Paths.get("src", "main", "data", "Kelbot.txt");`

Also I am quite confused by the relative file paths, as the location of the jar file and the main file are different, wouldn't the relative file path be different too?

Thanks in advance!

**Comment by tjtanjin** [comment]
Might be a similar issue to [this](https://github.com/nus-cs2103-AY2021S2/forum/issues/46). See if the solutions there help :D

**Comment by zhoube** [comment]
> Might be a similar issue to [this](https://github.com/nus-cs2103-AY2021S2/forum/issues/46). See if the solutions there help :D

Hello! I don't really think it is similar as my Jar file still runs except it cannot detect the .txt file through that file path, but I am still able to use it ad hoc (without loading and saving)

**Comment by zhoube** [comment]
> Might be a similar issue to [this](https://github.com/nus-cs2103-AY2021S2/forum/issues/46). See if the solutions there help :D

Hello! I don't really think it is similar as my Jar file still runs except it cannot detect the .txt file through that file path, but I am still able to use it ad hoc (without loading and saving)

**Comment by tjtanjin** [comment]
I believe the system is unable to find the path specified because the folders containing your .txt file is not present. If you go to where your jar file is sitting and create the folders as such `./src/main/data/` and run your jar file again, does it work?

**Comment by zhoube** [comment]
> I believe the system is unable to find the path specified because the folders containing your .txt file is not present. If you go to where your jar file is sitting and create the folders as such `./src/main/data/` and run your jar file again, does it work?

Ah, so recreate the exact same relative location to the jar file?

**Comment by tjtanjin** [comment]
Yup! If you created the folders manually and that solved your issue then you can look to implement the file creation in your code instead :D

**Comment by zhoube** [comment]
> Yup! If you created the folders manually and that solved your issue then you can look to implement the file creation in your code instead :D

Interestingly, when I run the jar file from IntelliJ, it works just fine. Might be an issue with my command prompt...

**Comment by tjtanjin** [comment]
Yikes, is it still the same error message and are you running `java -jar` within the same directory in both IntelliJ and on the shell? It might help to attach some screenshots or share the structure of your project currently as well :)

**Comment by zhoube** [comment]
> Yikes, is it still the same error message and are you running `java -jar` within the same directory in both IntelliJ and on the shell? It might help to attach some screenshots or share the structure of your project currently as well :)

Yep same directory, I right clicked on the jar file and opened cmd prompt, as well as right clicked on the jar file and then clicked run.

![image](https://user-images.githubusercontent.com/47862816/105844800-c2475800-6014-11eb-9ff7-0e1bfc670713.png)

**Comment by tjtanjin** [comment]
From the shell, can you check if there is a `src` folder in the same directory as where your Kelbot.jar is? If there is, check if there is a `main` folder within the `src` folder. Finally, check if there is a `data` folder within the `main` folder. If any of the three folders are not present, your code responsible for creating the folders is likely not working as intended.

**Comment by zhoube** [comment]
> From the shell, can you check if there is a `src` folder in the same directory as where your Kelbot.jar is? If there is, check if there is a `main` folder within the `src` folder. Finally, check if there is a `data` folder within the `main` folder. If any of the three folders are not present, your code responsible for creating the folders is likely not working as intended.

There isnt, but as the jar file is in `out/artifacts/kelbot_jar/` directory, there shouldn't be a src or main or data folder right?

![idea64_XdvZqYB2Jr](https://user-images.githubusercontent.com/47862816/105846796-a7c2ae00-6017-11eb-843d-0290133657ed.png)

Here is a screenshot in case I'm not very clear!

**Comment by tjtanjin** [comment]
So I just double checked and I have a data folder created at `./out/artifacts/ip_jar/data` for my case where I stored my data file in `./data/tasks.json`. I believe your code will need to ensure that `./src/main/data` is created at where your jar file is sitting. Give it a try and see if that works :D

Edit: Consider adapting and playing around with the following:
```
File file = new File("./data/tasks.json");
file.getParentFile().mkdirs();
```

**Comment by zhoube** [comment]
> So I just double checked and I have a data folder created at `./out/artifacts/ip_jar/data` for my case where I stored my data file in `./data/tasks.json`. I believe your code will need to ensure that `./src/main/data` is created at where your jar file is sitting. Give it a try and see if that works :D
> 
> Edit: Consider adapting and playing around with the following:
> 
> ```
> File file = new File("./data/tasks.json");
> file.getParentFile().mkdirs();
> ```

I changed my path to be relative, with `java.nio.file.Paths.get("..","..", "data", "Kelbot.txt");`, as I suspected that since my jar file is not in src, the original path is not working there, however i got an access denied...

**Comment by tjtanjin** [comment]
> I changed my path to be relative, with `java.nio.file.Paths.get("..","..", "data", "Kelbot.txt");`, as I suspected that since my jar file is not in src, the original path is not working there, however i got an access denied...

The use of double `..` will bring you two directories up to the `out` folder but I am unsure how this will help with your case :sweat_smile: Since you are getting an access denied error, try running the cmd prompt as an administrator. If this works, you can check your folder/file permissions :)

**Comment by zhoube** [comment]
> > I changed my path to be relative, with `java.nio.file.Paths.get("..","..", "data", "Kelbot.txt");`, as I suspected that since my jar file is not in src, the original path is not working there, however i got an access denied...
> 
> 
> 
> The use of double `..` will bring you two directories up to the `out` folder but I am unsure how this will help with your case :sweat_smile: Since you are getting an access denied error, try running the cmd prompt as an administrator. If this works, you can check your folder/file permissions :)

Ah so the relative path from the jar file should be the same as the relative path from the java file...

I got my access denied from IntelliJ...

**Comment by tjtanjin** [comment]
I suggest working with a simple `./data/Kelbot.txt` for now (which means a data folder at where your jar file is and the text file will be created within it). Access denied does sound like a separate problem which will require you to check read/write permissions but take it step by step and see if you are able to run the jar file as administrator from the cmd prompt first :)

**Comment by zhoube** [comment]
> I suggest working with a simple `./data/Kelbot.txt` for now (which means a data folder at where your jar file is and the text file will be created within it). Access denied does sound like a separate problem which will require you to check read/write permissions but take it step by step and see if you are able to run the jar file as administrator from the cmd prompt first :)

The thing is the file is always created with respect to ip directory, not with respect to wherever the java file/jar file directory is. 
So when I do `..` it actually went out of ip into the parent folder of ip, which is probably the main problem hahahaha

**Comment by tjtanjin** [comment]
When running the code directly in Intellij, the file is created with respect to the root directory of `ip` (`./data/Kelbot.txt` in this case would mean having a data folder in the same place as where your `src` folder is). When you build it as a jar and run it with `java -jar` instead, the file is now created with respect to the jar file. At least that's how I understand/have observed it (I hope I have not been rambling on wrongly ;-;). But stick with `./` and see if it works out. If access denied still pops up, try running as administrator in cmd prompt and see if that helps too :D

**Comment by zhoube** [comment]
I see, so use `./` such that it will create in the ip/data/Kelbot.txt, and when ran in jar file, it will create it in the same directory as jar file. So 2 different data/Kelbot in my ip?

**Comment by tjtanjin** [comment]
Essentially yup! You have 2 different `data/Kelbot.txt` (one from directly in IntelliJ, one from running as jar). In fact you can move the jar file to elsewhere on your computer and the new data folder will take reference from wherever you moved it too.

**Comment by zhoube** [comment]
I see, I got it to work!! Thank you so much!!
