### ISSUE TITLE
"No Tests were found" when running my JUnit tests

### ISSUE THREAD

**Issue by CSmortal** [nus-cs2103-AY2021S2/forum#53]
The JUnit installed in my "test" module has version 5.4, so I'm unsure of why its not working.

**Comment by tjtanjin** [comment]
Did you annotate the test methods with `@Test`? If not, could you share the structure of your project? You might also want to compare your `.iml` files with those in [this issue](https://github.com/nus-cs2103-AY2021S2/forum/issues/48#issuecomment-767041052), hopefully it'll help :D

**Comment by CSmortal** [comment]
This is the structure.

![image](https://user-images.githubusercontent.com/67994626/105853454-aea1ee80-6020-11eb-9df5-00feaa3a3115.png)

I copied and pasted both iml files into mine, still getting the same error. 

![image](https://user-images.githubusercontent.com/67994626/105853344-8adea880-6020-11eb-9617-14da911c20c8.png)

**Comment by tjtanjin** [comment]
I am not sure if this is actually relevant to the error you are facing (although with your current structure, copy pasting the `.iml` files without modifications will likely fail). Nonetheless, if you are willing to do a minor restructure on your project, you can consider the following:

1) Instead of marking the `src` folder as your `Sources Root`, mark the `java` folder within your `main` folder as your `Sources Root` (this does mean you need to change your package statements in your java files). 

2) Then, you may follow this [guide](https://se-education.org/guides/tutorials/junit.html) which essentially brings you through replicating the folder structure under `test` folder to mirror that of the `main` folder (your test classes need to be created in a matching package). You would then end up with a structure similar to this:
```
src
  - main
    - java (Sources Root)
      - duke
        - *.java 
  - test
    - java (Test Sources Root)
      - duke
        - *.java 
```
It's a bit neater to see both `main` and `test` folders mirroring each other and the `.iml` file you referred to earlier should fit nicely with this structure as well. See if this actually helps with your issue, otherwise you might want to share your test class as well :D

**Comment by rajobasu** [comment]
By the way, Also maybe try to make the Java folder inside test as “source of all tests” — there is an option like this in intellij. Maybe that’s the issue?

**Comment by CSmortal** [comment]
@tjtanjin I tried restructuring the proj the way you mentioned. 

I assume this pic below confirms that "java" under src/main is the source root.
![image](https://user-images.githubusercontent.com/67994626/105957234-ea39c880-60b3-11eb-83cf-f4c9ee42b865.png)


Strangely under the same "Project Structure>Project Settings>Modules" window, "java" under src/test is not marked as test sources root, when I have already done so on the left pane of intellij to mark it as the test sources root, and appears green as well.
![image](https://user-images.githubusercontent.com/67994626/105957292-0473a680-60b4-11eb-9e9d-0846d2312c75.png)
![image](https://user-images.githubusercontent.com/67994626/105957580-6a602e00-60b4-11eb-8a91-93a2b41b1997.png)

Under the same window, i tried setting "java" under src/test as the test sources root and i get this issue when applying changes.
![image](https://user-images.githubusercontent.com/67994626/105958331-6ed91680-60b5-11eb-9b25-12d725e5e2ed.png)

And lastly, the imports are all messed up and idk how to solve it. In Deadline.java, it doesn't know what Task is (like IntelliJ doesnt give me the option to import Task but they belong to the same package anw so why is this happening?), and ParserTest.java under test.java.duke has no option to import the classes in main.java.duke
![image](https://user-images.githubusercontent.com/67994626/105958968-44d42400-60b6-11eb-9ebf-640199891673.png)

**Comment by tjtanjin** [comment]
The screenshots are a bit blurry so I cannot see all the import errors but a point to note is that once you mark the `java` folder within the `main` folder as `Sources Root`, you need to change your `package` statements for all your java files to be `package duke;` as `java` would not be part of the package name.

For your ParserTest.java, once the project is structured correctly, you may refer to option 1 of point 8 in this [guide](https://se-education.org/guides/tutorials/junit.html).

I am not sure why there is an error arising from marking roots but you may consider unmarking all of them first then re-marking them again. Hopefully these will help resolve some of your above issues.

**Comment by ypinhsuan** [comment]
Hi! As what @tjtanjin suggested, you can try unmarking all the directories and go to File > New > Module from Existing Sources. Select `src\main`. Mark `src\main\java` as `sources root` and follow the guide on adding JUnit test.

**Comment by CSmortal** [comment]
@tjtanjin changing my package statements for all my java files to `package duke;` still doesn't allow me to import the relevant classes within the same package. 

I just wanna check if I'm marking each directory correctly:

Does this window confirm that the `java` folder within the `main` folder is the source root?
![image](https://user-images.githubusercontent.com/67994626/106102954-22580e80-617b-11eb-9dbe-21c364440588.png)

 The left pane on IntelliJ isn't very helpful cuz it just shows the whole thing `main.java.duke` without allowing me to right click on `java` to check what it is marked as. So i just resorted to the Project Structure window that comes up after pressing Ctrl + Alt + Shift + S above
![image](https://user-images.githubusercontent.com/67994626/106103319-ba55f800-617b-11eb-9a72-b2973cae38a5.png)

Also, I'm kinda confused why both `src/test` and `src/test/java` are both test sources roots, after i followed @ypinhsuan instructions. Is this intended? I'm reading up on what modules in IntelliJ are but im rly confused on what they are.
![image](https://user-images.githubusercontent.com/67994626/106103675-4536f280-617c-11eb-9ecc-d0892ea32bb7.png)
![image](https://user-images.githubusercontent.com/67994626/106103711-5253e180-617c-11eb-92e5-1e3a1f2ed2dc.png)


> 
> 
> Hi! As what @tjtanjin suggested, you can try unmarking all the directories and go to File > New > Module from Existing Sources. Select `src\main`. Mark `src\main\java` as `sources root` and follow the guide on adding JUnit test.

I forgot to mention that I've never seen in the project's instructions that we are supposed to create a new module from `src/main`. I tried to do that and mark `src/main/java` as sources root, and i get this issue when applying changes:
![image](https://user-images.githubusercontent.com/67994626/106104380-56343380-617d-11eb-97a1-d7885cccfde2.png)
Sorry for asking too many questions but I rly don't understand whats going on with the modules and all

**Comment by w2vgd** [comment]
@CSmortal You can open up your expand out all your packages by doing this: Press the settings icon right beside your project, and uncheck Compact middle packages.

![image](https://user-images.githubusercontent.com/65358857/106105304-becfe000-617e-11eb-85d0-64ad7c7b1435.png)

Try to unmark all your packages by right-clicking and selecting "Unmark as ...", and then proceed to only mark your `java` folder in src/main as Sources Root and mark your `java` folder in src/test as Test Sources Root.

![image](https://user-images.githubusercontent.com/65358857/106105545-1cfcc300-617f-11eb-957e-ef456eaaa44b.png)

In addition, you may want to share your `.iml` files if doing the above still doesn't work.

Hope this helps :)

**Comment by ypinhsuan** [comment]
> Also, I'm kinda confused why both src/test and src/test/java are both test sources roots

`src/test` is the module while `src/test/java` is the test source root. You can try unmarking `src/test`

**Comment by damithc** [comment]
Just dropping a note here to say kudos to the OP and the others who are trying to help. Nice to see detailed questions, equally detailed answers, and everyone persisting until a solution is found. 💯

**Comment by CSmortal** [comment]
Thanks @w2vgd for the 1st tip. 

This is my test.iml: 
![image](https://user-images.githubusercontent.com/67994626/106350851-038c8000-6313-11eb-9e16-d745de1b2275.png)



This is my main.iml:
![image](https://user-images.githubusercontent.com/67994626/106350856-0e471500-6313-11eb-9b87-83a68837a4ec.png)


I deleted a module called "ip" that i had previously since there seems to be some conflict with the "main" module (that i showed above but i can't rly understand). 

This is the project structure:
![image](https://user-images.githubusercontent.com/67994626/106350569-30d82e80-6311-11eb-9802-23a66e2646b8.png)

Before i go on, i have another ( noob ) question to ask. How do I resolve this issue of having to put the `main.java.duke.` in front of every declaration of a class from our java files?
![image](https://user-images.githubusercontent.com/67994626/106350741-341fea00-6312-11eb-84e1-90a05bdfb6a6.png)

**Comment by tjtanjin** [comment]
Since all your classes are in a single duke package, all you need to do is ensure that all of your java files have `package duke;` at the very first line and you will be able to refer to the classes directly by their names :)

**Comment by w2vgd** [comment]
> This is my test.iml:

This looks correct.

> This is my main.iml:

It seems weird that you have a `main.iml` file in addition to the `ip.iml` file. When did the `main.iml` file get created? Can you try deleting the `main.iml` file and check the contents of your `ip.iml` file?
You may want to compare it to my `ip.iml` file, and take a look at the highlighted line (which is different from yours)
![image](https://user-images.githubusercontent.com/65358857/106351011-3b47f780-6314-11eb-9e7f-e11c08aecb28.png)

> Before i go on, i have another ( noob ) question to ask. How do I resolve this issue of having to put the `main.java.duke.` in front of every declaration of a class from our java files?

Add `package duke` at the top of each of your java files.

**Comment by CSmortal** [comment]
Ah shucks, i forgot that i need to change the package statement for ALL of the java files.

**I no longer have the "No Tests were found" error!**. It seems like the issue was with the coexistence of the `ip` and `main` module, where i believe my `test` module had `ip` as its dependency, which caused issues with making `src/main/java` the source root. 

@w2vgd I created the `main` module after the `ip` module, and then i later deleted the `ip` module.
![image](https://user-images.githubusercontent.com/67994626/106353535-4ad03c00-6326-11eb-8782-d29e2a6632e0.png)

Cn I ask why exactly if the content root (im assuming this is just the root of a module) of `ip` is `src`, and if I had no `main` module, then why does the error occur (where the `test` module has `ip` module as its dependency)?
