### ISSUE TITLE
A-MoreOOP: Can Ui be an interface instead of a class?

### ISSUE THREAD

**Issue by benedictkhoomw** [nus-cs2103-AY2021S2/forum#54]
Hi, it seems to me that the Ui might be appropriate as an interface which can then be implemented now with a TextUI and later as a GUI. I am opening this thread for two reasons:

1. to ask the teaching team if it is acceptable to define Ui as an interface instead of a class
2. to get other opinions on this subject

I considered a (possibly abstract) base class but it seems like a GUI and a text UI (TUI) might use fundamentally different mechanisms (and hence different member variables) to display stuff hence they largely only have method signatures in common. At this point, using an interface seems more appropriate than a base class. Any thoughts?

**Comment by damithc** [comment]
> 1. to ask the teaching team if it is acceptable to define Ui as an interface instead of a class

Yes, we are fine with either @benedictkhoomw
