### ISSUE TITLE
Regarding adding dependency to another module

### ISSUE THREAD

**Issue by Hzxin** [nus-cs2103-AY2021S2/forum#56]
![error2](https://user-images.githubusercontent.com/61725744/106040822-e0738d80-60d2-11eb-847c-b399c0ea8774.jpg)
![error1](https://user-images.githubusercontent.com/61725744/106040828-e1a4ba80-60d2-11eb-8779-c9d046192133.jpg)
I've tried to follow the instruction and create a new module test from an existing source. But somehow I still having trouble importing duke. Duke. There is no dependencies tab for the test module and when I add reference of Duke in DukeTest, the hint has suggested moving duke. Duke into test/java/duke instead of creating dependencies. Did I miss out on some steps in the instructions or is there something wrong with my setup in the IntelliJ.

**Comment by tjtanjin** [comment]
You might want to try unmarking your `src` folder as `Sources Root` and then marking the `java` folder within your `main` folder as `Sources Root` first. Then, check if the directory structure in your `java` file in the `main` folder mirrors that of the `java` file inside your `test` folder. You shouldn't have to explicitly import `Duke` in your test class. Use `Duke` in the test class as you would normally in the main class and a prompt would pop up for you again to rectify the error. See if any of the above helps :D

**Comment by rajobasu** [comment]
<img width="306" alt="Screenshot 2021-01-28 at 3 25 43 AM" src="https://user-images.githubusercontent.com/34958324/106042823-85648980-6118-11eb-9115-3d75f6968f1e.png">

An example of how it should look like after you follow @tjtanjin ’s comment.

**Comment by Hzxin** [comment]
> You might want to try unmarking your `src` folder as `Sources Root` and then marking the `java` folder within your `main` folder as `Sources Root` first. Then, check if the directory structure in your `java` file in the `main` folder mirrors that of the `java` file inside your `test` folder. You shouldn't have to explicitly import `Duke` in your test class. Use `Duke` in the test class as you would normally in the main class and a prompt would pop up for you again to rectify the error. See if any of the above helps :D

thank you so much!  Manage to solve the issue.

**Comment by damithc** [comment]
Thanks @tjtanjin @rajobasu for the help.
