### ISSUE TITLE
Git sourcetree

### ISSUE THREAD

**Issue by banchiang** [nus-cs2103-AY2021S2/forum#57]
<img width="668" alt="git sourcetree" src="https://user-images.githubusercontent.com/72375578/106088016-1d399600-6160-11eb-97b4-d86099ec6122.png">

Hi guys newbie here. My source tree was looking good but as I was looking to rename my commits I did some rebase commands and in the end now my source tree is a mess :( The pink branch was my main branch but now it does not have a "branch" to it. How do I move my master to the commit of A-more OOP? Thanks in advance!

**Comment by damithc** [comment]
Try the following:
* Switch to the commit tagged `A-MoreOOP`. You can do that by double-clicking on it. You may have to commit any uncommitted changes first.
* Create a branch there (use the `branch` button)
* Merge the new branch to your master branch.

**Comment by banchiang** [comment]
<img width="653" alt="Screenshot_3" src="https://user-images.githubusercontent.com/72375578/106095318-94762680-616e-11eb-8d15-d5f101e482a8.png">

Okay looks good now thanks so much prof :D!

**Comment by damithc** [comment]
You can also delete the temp branch as it is no longer needed. It will not delete any commits.
