### ISSUE TITLE
cannot run runtest.sh file 

### ISSUE THREAD

**Issue by hengyongming** [nus-cs2103-AY2021S2/forum#6]
![image](https://user-images.githubusercontent.com/65388283/104815197-12bcf980-584e-11eb-8954-3e3e731a7907.png)

Hi all, 

I got this error when running the runtest.sh file.
There's nothing we should change in the runtest.sh file right ?

Thanks in advance !

**Comment by richardcom** [comment]
Hi, as you are using Windows, I think your should run `runtest.bat` file instead of the shell file.

Another more complicated and alternative solution is  [here](https://superuser.com/questions/120045/how-to-execute-sh-file-on-windows).

For others using UNIX Systems can use the `runtest.sh` file.

**Comment by damithc** [comment]
Thanks @richardcom for the help.
