### ISSUE TITLE
iP Progress Tracker not detecting A-Jar level

### ISSUE THREAD

**Issue by Juzzanoob** [nus-cs2103-AY2021S2/forum#61]
I had completed the A-Jar level for Week 3 within the deadline, however, the iP progress tracker did not detect it.

I have included snapshots below of my .jar file upload as a new release.
![image](https://user-images.githubusercontent.com/18525019/106147196-89dd8080-61b2-11eb-9d75-dfd7539e30e7.png)
![image](https://user-images.githubusercontent.com/18525019/106147225-9530ac00-61b2-11eb-9070-28f8f06c95b8.png)

Does anyone how to make the script detect my level? Also, will my level be counted as overdue since the deadline is over?

**Comment by rajobasu** [comment]
I think you have to tag the commit with A-Jar as well.

**Comment by Juzzanoob** [comment]
Alright I will try that, thanks!

**Comment by GabrielSimbingyang** [comment]
Hi @Juzzanoob, 

Ex student of CS2103T here. Also, do note that the dashboard takes 1-2 days to refresh and display the relevant changes. If your problem has been solved, please remember to also close this thread to ensure the forum remains a neat and tidy place.

Thank you and all the best!

Regards,
Gabriel Sim

**Comment by Juzzanoob** [comment]
Yup! I've just checked and the script has picked up my A-Jar level after committing with an A-Jar tag. Thanks everyone!
