### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by banchiang** [nus-cs2103-AY2021S2/forum#62]
<img width="339" alt="main" src="https://user-images.githubusercontent.com/72375578/106152707-bb594a80-61b8-11eb-9dee-d2864fc8d6b7.png">
<img width="427" alt="error" src="https://user-images.githubusercontent.com/72375578/106152689-b7c5c380-61b8-11eb-8af0-6a553a24d953.png">

<img width="720" alt="ui1" src="https://user-images.githubusercontent.com/72375578/106152715-bdbba480-61b8-11eb-89d7-263d19b5c3cb.png">

Hi I'm encountering NullPointerException when running Duke so I narrowed down and realized its my ui when running in a duke.run(). If it simply runs outside of the duke.run() it works fine. I'm not sure why is this so. First picture is my Duke.java, second picture is the error occurred and third is the write up of my Ui.java. Thanks in advance!

**Comment by onnwards** [comment]
Is that all there is in your Duke.java? I think you'll need a Duke constructor where you define your Ui, Storage, as attributes of the Duke object (as in the example provided in the project week2 page)

**Comment by damithc** [comment]
@banchiang While waiting for someone to offer some help, 
* Why the first and second lines of the run() method are indented differently?
* Recommended: capture line numbers in your screenshots so that others can refer to them easily in their answer. If your Intellij is not showing line numbers, you can configure it to do so.

**Comment by damithc** [comment]
Hint: a variable declared inside a method will hide/shadow a variable with the same name but declared outside of the method. You end up having two variables with the same name while you might have intended to have only one.

**Comment by tjtanjin** [comment]
It's not clear where the `ui` in the run method of your `Duke` class is coming from. Were you intending to pass `ui` in as parameter? It's strange that it's not flagged in red with what is seen in the screenshot. It might help to show the relevant files in entirety 😅

**Comment by banchiang** [comment]
Thanks @onnwards @damithc @tjtanjin! Will do a better job at screenshotting next time! Also, yeah the error was from the constructor I did not initialise my ui there so there was a null pointer error to the Duke attribute's ui. Thanks so much!
