### ISSUE TITLE
Checkstyles using gradle 

### ISSUE THREAD

**Issue by colintkn** [nus-cs2103-AY2021S2/forum#64]
I'm trying to use checkstyles from gradle, But I keep getting an error 
![image](https://user-images.githubusercontent.com/65516485/106175047-9c66b280-61d0-11eb-93d2-1bfb123487cb.png)

I got my xml files from https://github.com/se-edu/addressbook-level3/blob/master/config/checkstyle/checkstyle.xml

I put the files in the directory as follow :
![image](https://user-images.githubusercontent.com/65516485/106174979-8953e280-61d0-11eb-95a8-2c8719803470.png)

This is how I setup the build.gradle: (is there anything wrong)
![image](https://user-images.githubusercontent.com/65516485/106175025-953fa480-61d0-11eb-9e71-846d0201cb3f.png)

**Comment by ypinhsuan** [comment]
Hi! Does your `build.gradle` contain this?
```
repositories {
    mavenCentral()
}
```

**Comment by colintkn** [comment]
hi @ypinhsuan I added mavenCentral() as you mentioned. 

I get this where I can see the checkstyle errors in a html file. Is this how checkstyle works? 

![image](https://user-images.githubusercontent.com/65516485/106225697-aa442400-6220-11eb-991a-ac8a2ece7d89.png)

Running the following command 
```
gradle checkstyleMain checkstyleTest
```
gives me the checkstyle listed in the terminal which seems to make more sense.

**Comment by tjtanjin** [comment]
You can see the checkstyle violations in the html file but if you scroll up slightly higher the violations are reported directly on the terminal too (and you can click on their links to quickly jump to them).

**Comment by colintkn** [comment]
Thank you. @tjtanjin @ypinhsuan

**Comment by damithc** [comment]
Thanks @tjtanjin @ypinhsuan for the help 💯
