### ISSUE TITLE
JUnit Testing for Objects

### ISSUE THREAD

**Issue by colintkn** [nus-cs2103-AY2021S2/forum#65]
I am trying to test my Parser. This is how my Parser works. 

This is the constructor, taking in the full command. 
```
public Parser(String fullCmd) {
   ... 
    }
```

This is my getCommand() method, that returns a command object.  
```
    public Command getCommand() throws DukeException {
        ...
        case ByeCommand.COMMAND:
            return new ByeCommand();
        default:
            return new UnknownCommand();
        }
    }
```
I'm testing it as follows... 
```
public class ParserTest {
    @Test
    public void testCommandGetter_byeCommand() throws PercyException {
        // assertEquals(ByeCommand(), new Parser("bye").getCommand());
    }
}
```
But I'm failing the test likely because they are not the same object. 
Any suggestions of a way of testing such input/outputs that are object related?  
The one covered in lecture tests for strings.

**Comment by rajobasu** [comment]
objects have a function called ```.equals()```.
You need to override that in your object. Right now they only match the memory location of the object which is obviously different since these are two different objects.

**Comment by colintkn** [comment]
Someone on this forum seems to discourage overriding.
https://stackoverflow.com/questions/27605714/test-two-instances-of-object-are-equal-junit

But for now I'll do it. Thanks for you suggestion @rajobasu

**Comment by georgepwhuang** [comment]
Maybe write a `toString()` method and assert the strings instead?

**Comment by rajobasu** [comment]
@colintkn I assumed you didn’t want to download additional stuff :P
Yes, the methods mentioned in the link might have been better ways to match, can download those.

**Comment by colintkn** [comment]
Yes hahaha... Just exploring the options here. thanks guys appreciate it @georgepwhuang @rajobasu.
