### ISSUE TITLE
CustomImportOrder in checkstyle.xml: 'STANDARD_JAVA_PACKAGE' error

### ISSUE THREAD

**Issue by marcusleeeugene** [nus-cs2103-AY2021S2/forum#67]
Hi, did anyone face similiar issue? Not sure if I have to change the import settings on intellij ide's configuration. I used the checkstyle.xml file in addressbook-level3.

Import statement for 'java.io.File' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line. [CustomImportOrder]

Here's how my imports look like at the moment.
![Screenshot 2021-01-29 at 4 04 42 PM](https://user-images.githubusercontent.com/19762656/106248288-bdb8b480-624b-11eb-8b19-41ebb0b35a36.png)

**Comment by tjtanjin** [comment]
Place the import statements for your own classes below those from the java packages and it should be alright :)

**Comment by marcusleeeugene** [comment]
> Place the import statements for your own classes below those from the java packages and it should be alright :)

Ah that worked, thanks! :)
