### ISSUE TITLE
Java Runtime Version for shadowJar 

### ISSUE THREAD

**Issue by colintkn** [nus-cs2103-AY2021S2/forum#68]
I am using the following command to generate my jar file. 
```
gradle clean shadowJar 
```

When my project SDK is configured to java 11, I get this error when running the jar file. 

```
Error: LinkageError occurred while loading main class Duke
	java.lang.UnsupportedClassVersionError: Duke has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

When I configure it to jdk15, the error stops. 

This project is required to be in java 11. How do I get around this.

**Comment by tjtanjin** [comment]
There's a possibility your `Gradle JVM` is set to jdk15. 

Go to `Preferences` (settings on windows) -> `Build, Execution, Deployment` -> `Build Tools` -> `Gradle`

Check at the bottom if `Gradle JVM` has been set to jdk15. If it has then change it to jdk11 and regenerate your jar file again with project sdk configured to java 11 :D

**Comment by colintkn** [comment]
Ok thank you.
