### ISSUE TITLE
Clarification on class diagram in video under W4.2

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#69]
Hello, 

![image](https://user-images.githubusercontent.com/65358857/106261434-87376580-625c-11eb-988c-b4ee1cc1d1ed.png)

In the class diagram shown, from what I can gather,
- Each `Foo` object is connected to 2 other instances of `Foo` objects
- Each `Foo` object has 0 or more `Foo` objects stored with the variable name `bar`

What I think how the sample code for `Foo` looks like is:
```
class Foo {
    Foo f1;
    Foo f2;   // I am assuming that f2 cannot be the same instance as f1
    Foo bar;  // bar can be the same instance of Foo as f1 or f2
}
```

However, in the video, it is mentioned that option b is correct even though the bottom 2 instances of `Foo` are connected to only 1 other instance of `Foo`. I would think that option b is only correct if the bottom 2 instances of `Foo` are connected to each other (or some other instances). Can someone help clarify if I am wrong in my understanding? Thank you.

**Comment by damithc** [comment]
You are right @w2vgd 
The answer considers only one instance of the association, but there should be more such associations for the bottom two objects (in b) for that object diagram to be complete. Will fix soon.

**Comment by w2vgd** [comment]
Thanks for the clarification prof!
