### ISSUE TITLE
Clarification on allowing/disallowing repeated task names

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#7]
Hello,

I would like to clarify if there is a need for us to concern ourselves with whether repeated task names are allowed/disallowed. Without checking for repeated task names, it would mean the following scenario is possible:

<img width="309" alt="repeated_task_names" src="https://user-images.githubusercontent.com/43908963/104815821-f0c57600-5851-11eb-901f-2a905142dd5b.png">

If repeated task names are allowed, then a follow-up question would be is there a need to distinguish them uniquely when tasks are marked as done (this affects implementation).

Kindly advice, thank you!

**Comment by damithc** [comment]
Both meet our minimum requirement, beyond which it will not affect marks either way.
So, it is up to you @tjtanjin , based on how good you want to make it for your personal interest e.g., to showcase your skills to a future interviewer
When deciding, you can also factor in the utility to the user and the cost of implementing.

**Comment by iamgenechua** [comment]
From the project description, it seems that when you mark tasks as done, you identify the tasks by the order at which they appear.
e.g. `done 2` would mark the second task as done as seen on your interface.
Hence, this would mean that even if you have repeated task names, you would be able to distinguish them uniquely by their ordering with the `done` command.

As for whether you want to allow repeated tasks, it is up to you. Of course, more effort would lead to more learning on your end, so i definitely would encourage you to enhance your project as much as possible (as long as it stays within the scope of the project)

**Comment by tjtanjin** [comment]
Understood, thank you very much!
