### ISSUE TITLE
CheckStyle Error - Unable to instantiate 'FileContentsHolder' class.

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [nus-cs2103-AY2021S2/forum#70]
I just tried to set up CheckStyle but I got the following error when I ran checkStyleMain on Gradle:
```
Unable to instantiate 'FileContentsHolder' class, it is also not possible to instantiate it as .FileContentsHolder, FileContentsHolderCheck, .FileContentsHolderCheck. 
Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. 
Please also recheck that provided ClassLoader to Checker is configured correctly.

```

I'm not sure what this error means. In addition, when I tried setting up on IntelliJ, I got this long error message:
![image](https://user-images.githubusercontent.com/69678785/106290139-19536400-6285-11eb-9999-d63d8a5c0b20.png)

Anyone knows what's going on?

**Comment by rajobasu** [comment]
Could you please provide a higher resolution screenshot thanks!

**EDIT**
Might want to follow [this](https://github.com/checkstyle/checkstyle/issues/5132)

**Comment by yhtMinceraft1010X** [comment]
Here's the updated screenshot:
![ErrorMessage](https://user-images.githubusercontent.com/69678785/106291873-21140800-6287-11eb-8182-966e9488b3c5.png)

I tried removing this line according to what was said in the link:
```
<!-- Required for SuppressionCommentFilter to work -->
    <module name="FileContentsHolder"/>
```

And got a TreeWalker error:
```
TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard.
```

**Comment by tjtanjin** [comment]
You may also see if [this](https://github.com/checkstyle/eclipse-cs/issues/190) helps with your issue :)

**Comment by yhtMinceraft1010X** [comment]
This is what I have done so far:
-Removed the FileContentsHolder module
-Moved LineLength from TreeWalker to Checker

But now I'm getting this on Gradle:
```
Property 'allowMissingPropertyJavadoc' does not exist, please check the documentation
```

I've tried following [this link](https://stackoverflow.com/questions/58214442/gradle-checkstyletest-fails-checkstyleexception-property-allowmissingproperty) and adding this:
```
<module name="MissingJavadocMethodCheck">
  <property name="allowMissingPropertyJavadoc" value="true"/>
</module>
```

and I've also tried removing the `<property name="allowMissingPropertyJavadoc" value="true"/>` line but to no avail...

**Comment by yhtMinceraft1010X** [comment]
Update: I just realised there are 2 JavadocMethod modules, one for public methods, one for non-trivial private methods...

And after I deleted both copies of allowMissingPropertyJavadoc, I got these, which I also successively deleted but gave up because I don't know if these are required for CheckStyle:
```
Property 'allowUndeclaredRTE' does not exist, please check the documentation
Property 'ignoreMethodNamesRegex' does not exist, please check the documentation
Property 'allowThrowsTagsForSubclasses' does not exist, please check the documentation
Property 'allowMissingThrowsTags' does not exist, please check the documentation
```

**Comment by tjtanjin** [comment]
There seems to be a lot of deletion going on and I am not sure if this is the best way forward :sweat_smile:

To clarify, do you have both `checkstyle.xml` and `suppressions.xml` placed under `src/config/checkstyle/` ?

The `build.gradle` file in your latest commit seems alright but if you have made any changes to it you might want to share them as well.

Lastly, are you running the check with `gradle checkstyleMain checkstyleTest`?

It might be worth to double check/retry the setup again just in case a previous error is causing all these unnecessary deletions :)

**Comment by yhtMinceraft1010X** [comment]
For mine, the config folder was separate from the src folder, but I somehow managed to get it to work. These are the Javadoc checkstyle properties that I kept:
```
      <property name="allowedAnnotations" value="Override, Test, BeforeAll, BeforeEach, AfterAll, AfterEach, Subscribe"/>
      <property name="scope" value="public"/>
      <property name="allowMissingParamTags" value="true"/>
      <property name="allowMissingReturnTag" value="true"/>
      <property name="tokens" value="METHOD_DEF, ANNOTATION_FIELD_DEF"/>
```

Everything else was deleted. Here's the full list of my deleted properties in original order for non-trivial private:
```
<property name="minLineCount" value="3"/>
<property name="allowUndeclaredRTE" value="true"/>
<property name="allowThrowsTagsForSubclasses" value="true"/>
<property name="allowMissingThrowsTags" value="true"/>
<property name="allowMissingPropertyJavadoc" value="true"/>
<property name="ignoreMethodNamesRegex" value="(set.*|get.*)"/>
```

And for public:
```
<property name="minLineCount" value="1"/>
<property name="allowUndeclaredRTE" value="true"/>
<property name="allowThrowsTagsForSubclasses" value="true"/>
<property name="allowMissingThrowsTags" value="true"/>
<property name="allowMissingPropertyJavadoc" value="true"/>
<property name="ignoreMethodNamesRegex" value="(set.*|get.*)"/>
```

After all these, I managed to get CheckStyle to run on both my main and test code. I'm keeping this issue open in case there's a more elegant solution without deleting these properties.

**Comment by tjtanjin** [comment]
May I check where you obtained your checkstyle.xml from? I am unable to find the following lines from the checkstyle gotten from [AB3](https://github.com/se-edu/addressbook-level3/blob/master/config/checkstyle/checkstyle.xml):
```
<property name="allowUndeclaredRTE" value="true"/>
<property name="allowThrowsTagsForSubclasses" value="true"/
<property name="allowMissingThrowsTags" value="true"/>
```

**Comment by yhtMinceraft1010X** [comment]
I got it from [here](https://github.com/se-edu/addressbook-level3/releases).

I headed to this link from the user guide, which I accessed from the Week 3 familiarise with AB3 tP task.

Edit: The CheckStyle file was updated to v8.32, but the build.gradle put 8.29. Not sure if I should change the build.gradle checkstyle to 8.32...

Edit 2: Ok, so what I did was download the production release v0.1 source code and get the checkstyle file from there. Maybe that explains why it's different from what's on Github...

**Comment by tjtanjin** [comment]
Yup! There's a checkstyle guide in week 4's project [here](https://se-education.org/guides/tutorials/checkstyle.html). If you are willing to go to the trouble following this week's guide might just solve all your issues :D

**Comment by yhtMinceraft1010X** [comment]
Final Update: I manage to plug back in three properties:
```
   <module name="MissingJavadocMethodCheck">
      <property name="minLineCount" value="1"/>
      <property name="allowMissingPropertyJavadoc" value="true"/>
      <property name="ignoreMethodNamesRegex" value="(set.*|get.*)"/>
    </module>
```

Thanks all!
