### ISSUE TITLE
Use Gradle to checkstyle

### ISSUE THREAD

**Issue by QY-H00** [nus-cs2103-AY2021S2/forum#73]
Hi firends! When I use Gradle to check style, the violation report shows that position of import statement 'Java.uitl.Scanner' is wrong, and it should be in the  'STANDARD_JAVA_PACKAGE' group. Could you tell me how to resolve this violation?

**Comment by w2vgd** [comment]
The order of imports should be as follow (from top to bottom):

1. static imports
2. standard java imports (imports from standard java api, e.g. `import java.util.Scanner`, `java.time.LocalDate`, etc)
3. special imports (such as imports from your own packages, e.g. `import duke.commands`)
4. third party imports (such as from javafx library)

**Comment by QY-H00** [comment]
> The order of imports should be as follow (from top to bottom):
> 
> 1. static imports
> 2. standard java imports (imports from standard java api, e.g. `import java.util.Scanner`, `java.time.LocalDate`, etc)
> 3. special imports (such as imports from your own packages, e.g. `import duke.commands`)
> 4. third party imports (such as from javafx library)

Thanks! Got it.

**Comment by richardcom** [comment]
Yup, @w2vgd  is correct. I have attached a screenshot to illustrate more clearly.
![image](https://user-images.githubusercontent.com/65701775/106349295-e2726200-6307-11eb-9926-b1fd0ab4df26.png)
