### ISSUE TITLE
JavaFx importing issue

### ISSUE THREAD

**Issue by hengyongming** [nus-cs2103-AY2021S2/forum#74]
Can someone help me why there's an error in importing the javafx module when i alr added it to the dependency?
TIA!
![image](https://user-images.githubusercontent.com/65388283/106353773-f7f78400-6327-11eb-85e5-962c9918b47c.png)
![image](https://user-images.githubusercontent.com/65388283/106353822-50c71c80-6328-11eb-8935-ce005f08098b.png)

**Comment by w2vgd** [comment]
@hengyongming Have you reload your gradle project? After you add dependencies into your `build.gradle` file, you have to load them first.

Try pressing this button.
![image](https://user-images.githubusercontent.com/65358857/106354663-6dfee980-632e-11eb-9bd5-59b8877ab792.png)

**Comment by hengyongming** [comment]
@w2vgd I am such an idiot. It works now thank you so much !
