### ISSUE TITLE
Gradle Checkstyle "unable to create root module"

### ISSUE THREAD

**Issue by fairyinabottle4** [nus-cs2103-AY2021S2/forum#76]
Remember to give sufficient details e.g.,
* Your development environment (IntelliJ March'20, Java 11, Windows 10, ...)
* Relevant code, error message, stack trace
* Relevant code snippet (an example given below), or link to the relevant code on your GitHub repo

Hi, I tried running the checkstyle on the gradle and I am getting this issue, which I do not understand what it means. Could someone point me in the right direction? Thank you

https://drive.google.com/file/d/1ND1cA3OVn5wHP17gsw8kMd_wnK2tSFwp/view?usp=sharing

**Comment by fairyinabottle4** [comment]
The reason was because I did not have the suppressions.xml file in the checkstyle folder, which caused the issue

**Comment by tjtanjin** [comment]
Hello! You might want to double check if you have both checkstyle.xml and suppressions.xml placed under src/config/checkstyle/ 

Check your build.gradle file as well and make sure you got your checkstyle.xml from [here](https://github.com/se-edu/addressbook-level3/tree/master/config/checkstyle)

**Comment by sheetalj2205** [comment]
> Hello! You might want to double check if you have both checkstyle.xml and suppressions.xml placed under src/config/checkstyle/
> 
> Check your build.gradle file as well and make sure you got your checkstyle.xml from [here](https://github.com/se-edu/addressbook-level3/tree/master/config/checkstyle)

Hey @tjtanjin why it is important to have the checkstyle.xml file only from this repo?

**Comment by tjtanjin** [comment]
Hey @sheetalj2205! The `checkstyle.xml` above was referenced from a repository used in the teaching of a software engineering module. This forum was also used for students to have related discussions (hence the specificity in the answer you quoted). Hope this clarifies any confusion! :)
