### ISSUE TITLE
Better way of assigning value to variable

### ISSUE THREAD

**Issue by JonahhGohh** [nus-cs2103-AY2021S2/forum#78]
`taskList = storage.load();`
`storage.load(taskList);`

Are both ways of loading the storage into taskList ok? Is there a better one of the two?
I usually see code being written in the first way, but I am not really sure what the drawbacks if any of the second one are.

**Comment by JulietTeoh** [comment]
for my storage class, it loads the data file from memory directly and then returned the taskList from the data and so I use ```taskList = storage.load();```. 

I think line 2, ```storage.load(taskList);``` works by first loading the dataList onto an arrayList, perhaps by using another class like parser, and then ```storage.load(taskList)``` loads the taskList into duke's tasklist. 

I think that the first way is more convenient, but both ways are valid and your implementation depends on your definition of storage, i.e is storage suppose to load the data from memory into duke or is storage loading the data already in duke to its tasklist.

**Comment by damithc** [comment]
> `taskList = storage.load();`
> `storage.load(taskList);`
> 
> Are both ways of loading the storage into taskList ok? Is there a better one of the two?
> I usually see code being written in the first way, but I am not really sure what the drawbacks if any of the second one are.

@JonahhGohh I don't think there is a big difference. You can go with either one. But there are some minor differences. For example, the second approach is passing an existing data object to another method, which means you are trusting that method to not mess up the object given. No such risk in the first approach.
