### ISSUE TITLE
Cannot resolve class 'MainWindow'

### ISSUE THREAD

**Issue by QY-H00** [nus-cs2103-AY2021S2/forum#79]
Hi friends! When I follow the guidance of JavaFX tutorial, it shows that the following error in the MainWindow.fxml. Could you tell me how to resolve this problem?

![image](https://user-images.githubusercontent.com/55167052/106372998-5ec08000-63b0-11eb-984f-d804e503b648.png)
![image](https://user-images.githubusercontent.com/55167052/106373031-9f1ffe00-63b0-11eb-9790-89fe069daffc.png)

**Comment by tjtanjin** [comment]
Where did you place your `MainWindow.java` file? Did you import it if you placed it in another package?

**Comment by QY-H00** [comment]
> Where did you place your `MainWindow.java` file? Did you import it if you placed it in another package?

Got it. I place it in a seperated package. So the controller should be "{packageName}.MainWindow". Thank you!
