### ISSUE TITLE
Use of partial solutions shown in CS2103/T webpage

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [nus-cs2103-AY2021S2/forum#8]
For things like Task class in Level-3, are we allowed to make use of the partial solution shown in the webpage? If so, how do we note this down and give credit?

**Comment by damithc** [comment]
Yes @yhtMinceraft1010X you may use those partial solutions. No need to give credit for partial solutions we have given ourselves.

**Comment by yhtMinceraft1010X** [comment]
Thank you Prof!
