### ISSUE TITLE
Unable to import javafx.fxml.FXML

### ISSUE THREAD

**Issue by fairyinabottle4** [nus-cs2103-AY2021S2/forum#80]
* Your development environment (Intellij 2020.3, Java 11.0.9, Windows 10 64 bit, ...)

Hi all, I'm doing the GUI tutorial and all is well until the last section of part 4, where I am unable to import the fxml packages. 

I'm wondering if gradle forgot to download that particular package? I don't think this is the case but I don't know what else to do either. 

You can see the problem in this screenshot
![fxml](https://user-images.githubusercontent.com/46418515/106373548-9d0c6e00-63b5-11eb-8dbe-eb5e5cc74c2d.PNG)

I also have my dependencies in this screenshot
![javafx](https://user-images.githubusercontent.com/46418515/106373551-a39ae580-63b5-11eb-97a3-126ed89516b1.PNG)

**Comment by damithc** [comment]
@fairyinabottle4 some tips, while we wait for someone to offer help:



> Remember to give sufficient details e.g.,
> 
> * Your development environment (Intellij 2020.3, Java 11.0.9, Windows 10 64 bit, ...)
> * Relevant code, error message, stack trace
> * Relevant code snippet (an example given below), or link to the relevant code on your GitHub repo

These are instructions to the issue author, meant to be deleted before you post.


> You can see the problem in this screenshot
> https://drive.google.com/file/d/1et8rEhBuvMjbcRPqFon8aYxC1qktwgb1/view?usp=sharing

You can simply 'paste' images in the issue body. No need to host them elsewhere.

**Comment by fairyinabottle4** [comment]
@damithc noted, didn't know that was possible! Post amended for clarity

**Comment by fairyinabottle4** [comment]
Resolved. The javafx block in the dependency was causing the issue. After I deleted it it worked fine. 

(I only added it because I was referring to some external tutorial on javafx, I suspect it could have conflicted with the other dependencies)
