### ISSUE TITLE
Checkstyle error

### ISSUE THREAD

**Issue by enhao25** [nus-cs2103-AY2021S2/forum#82]
While trying to follow the steps to run checkstyle, I ran into this error.
![image](https://user-images.githubusercontent.com/24240408/106383571-cd79f980-6401-11eb-96dd-8f2fd669d1bd.png)

Anyone know whats wrong?

**Comment by damithc** [comment]
@enhao25 I remember seeing something similar in this forum earlier. Try searching with some keywords, especially among closed issues.

**Comment by enhao25** [comment]
Ok thank you prof. I didn't realize that we had to download and put the folders in the exact place with gradle. Thank you.
