### ISSUE TITLE
Transitivity of Association (navigability) in class/object diagram

### ISSUE THREAD

**Issue by maxxng** [nus-cs2103-AY2021S2/forum#83]
If `foo` is aware of `goo` and `goo` is aware of `bar`, then is `foo` aware of `bar`?
And is there a difference if the navigability is bidirectional, i.e `student` aware of `teacher` and `teacher` aware of `student`, then can a student object be aware of another student object?

**Comment by damithc** [comment]
> If `foo` is aware of `goo` and `goo` is aware of `bar`, then is `foo` aware of `bar`?

No.

> And is there a difference if the navigability is bidirectional, i.e `student` aware of `teacher` and `teacher` aware of `student`, then can a student object be aware of another student object?

No.

In both cases, it's like real life (easy to remember).

**Comment by MatthiasLHK** [comment]
Just imagine this in real life. If you know a `friend A`, who has a `friend B`. Does this mean that you naturally know who `friend B` is? Unless you personally meet `friend B`, or have some form of connection, then you will not know who `friend B` is. So in the case of your example. As `foo` only has a relation to `goo`, hence `foo` will not have a direct relation to `bar`

**Comment by maxxng** [comment]
Got it thanks!
