### ISSUE TITLE
Regarding PR

### ISSUE THREAD

**Issue by Hzxin** [nus-cs2103-AY2021S2/forum#84]
![error3](https://user-images.githubusercontent.com/61725744/106394084-9ea85700-63f2-11eb-82e8-cbb92ad5ba38.jpg)
![error4](https://user-images.githubusercontent.com/61725744/106394082-9cde9380-63f2-11eb-85cb-8c08860a9b73.jpg)

Hi, run into this problem where my pull request did not get updated correctly(The first photo is my current ip). Furthermore, when I close the previous pull request and try to make a new one, it shows the one to be uploaded is the one that was done 2 weeks ago(as seen in the second photo).

**Comment by tjtanjin** [comment]
This is oddly strange all your previous closed pull requests seem to reflect the latest of your code changes. For both the pull requests you mentioned in your first screenshot (and which you have closed), they are both seen to be 40 commits ahead of the upstream master. In the second screenshot, the number of commits also show 40 although it seems the commit lines do not reflect that. Have you tried peeking at your pull requests when signed out/from another browser?

**Comment by damithc** [comment]
> This is oddly strange all your previous closed pull requests seem to reflect the latest of your code changes.

@tjtanjin I think this is the expected behavior. The PR will reflect the latest code even if it is closed.


> Hi, run into this problem where my pull request did not get updated correctly

@Hzxin What do you mean 'not get updated correctly'?

**Comment by richardcom** [comment]
@Hzxin Hi, I have just checked ur closed pr. It seems that it was updated and your commits(e.g. resolve conflicts for level 9) on Jan 30th are shown.

![image](https://user-images.githubusercontent.com/65701775/106410603-24bdaf80-647e-11eb-87ab-d53af9fd4436.png)

**Comment by Hzxin** [comment]
> @Hzxin Hi, I have just checked ur closed pr. It seems that it was updated and your commits(e.g. resolve conflicts for level 9) on Jan 30th are shown.
> 
> ![image](https://user-images.githubusercontent.com/65701775/106410603-24bdaf80-647e-11eb-87ab-d53af9fd4436.png)

I think I saw it wrongly, my bad

**Comment by damithc** [comment]
> I think I saw it wrongly, my bad

Even I was concerned for a while because it looked like none of the PRs are showing the latest commits. It turns out the latest commits are at the bottom of the page :-p
