### ISSUE TITLE
Problem encountered after installing gradle

### ISSUE THREAD

**Issue by xuanqi966** [nus-cs2103-AY2021S2/forum#86]
![image](https://user-images.githubusercontent.com/58899539/106413162-5cc7f100-6484-11eb-8479-018811d63acb.png)
Hi, to set up gradle I followed the tutorial on https://www.jetbrains.com/help/idea/gradle.html#gradle_add_module to add a build.gradle file and installed gradle to my project upon prompted. After installing, my program fails to compile and I'm prompted with the message displayed above. I have added relevant junit dependencies into build.gradle but the problem still remains. Can anyone tell me what's the issue here?

**Comment by tjtanjin** [comment]
Seems to be a similar issue to the one posted [here](https://github.com/nus-cs2103-AY2021S2/forum/issues/48). See if the solutions there help :D
