### ISSUE TITLE
Admin: Unsure of which checkstyle file to use 

### ISSUE THREAD

**Issue by ZhangAnli** [nus-cs2103-AY2021S2/forum#87]
Hi all, 

I am currently trying to adhere to the Java coding standard by using checkstyle. However, after downloading it from the official checkstyle website (version 8.40), I am unsure of which checkstyle file to actually use in my .config/checkstyle, as seen from the screen shot below. 
Am I doing something wrong or are we supposed to use a provided checkstyle.xml file somewhere? 
Thanks in advance! 

<img width="644" alt="Screenshot 2021-02-01 at 1 49 50 PM" src="https://user-images.githubusercontent.com/65236091/106419858-5c375680-6494-11eb-839a-dfecfa8441b4.png">

**Comment by SoonKeatNeo** [comment]
There's a checkstyle.xml included in the addressbook-level3 for the tP, which I believe we're supposed to be able to use:
https://github.com/se-edu/addressbook-level3/blob/master/config/checkstyle/checkstyle.xml

**Comment by damithc** [comment]
> There's a checkstyle.xml included in the addressbook-level3 for the tP, which I believe we're supposed to be able to use:
> https://github.com/se-edu/addressbook-level3/blob/master/config/checkstyle/checkstyle.xml

Yup, follow the given tutorial which also tells you which config files you can use:

>![image](https://user-images.githubusercontent.com/1673303/106422054-dbc72480-6498-11eb-9816-22c2eda4cf11.png)

**Comment by ZhangAnli** [comment]
Ok thank you Soon Keat and Prof!
