### ISSUE TITLE
Do we need to give credit to reused code from JavaFX tutorials provided to us?

### ISSUE THREAD

**Issue by Cheng20010201** [nus-cs2103-AY2021S2/forum#88]
As per above. Thanks! 😃

**Comment by damithc** [comment]
Normally, it is best to acknowledge the use of code from external tutorials. But in this case the tutorial is not actually an 'external' source; so, OK not to give credit specifically although you are welcome to.

**Comment by Cheng20010201** [comment]
Thanks prof. 👍🏻
