### ISSUE TITLE
Typo in iP: Duke Level-3 example

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#9]
Hi, just noticed a small typo `Taks` instead of `Task` at line 1 under the `Duke Level-3` ->  `Extension: A-classes` ->  `Partial Solution` example. And I think there is a need to add a semicolon at the end of line 2 as well. 

![image](https://user-images.githubusercontent.com/65358857/104831372-4b4aea80-58c3-11eb-816f-caca5257d232.png)

Thank you.

**Comment by damithc** [comment]
Thanks @w2vgd for the bug report. Will fix soon.

**Comment by damithc** [comment]
Fixed.
