### ISSUE TITLE
InvocationTargetException and NullPointerException

### ISSUE THREAD

**Issue by kaixiangtay** [nus-cs2103-AY2021S2/forum#91]
<img width="1563" alt="Screenshot 2021-02-01 at 21 04 57" src="https://user-images.githubusercontent.com/59237953/106462499-26649300-64d1-11eb-8600-18d311ad8877.png">

Did anyone encounter InvocationTargetException and NullPointerException during the integration of JavaFX into the project?

Apparently, the error happens when I entered something like "todo book" into the textbox. I suspect it is due to the first spacing of the string. When I enter "todobook" or "todobook and", the response can be returned from the DialogBox. I made a duplicate copy of the project without JavaFx and everything is working fine.

**Comment by tjtanjin** [comment]
I bumped into this yesterday while working on part 4 of javafx tutorial. I googled a bit about it but didn't read too much into it except javafx did seem to have a hand in the `InvocationTargetException` :P As far as I can recall I think it "wraps" itself around other exceptions (in your case that would be `NullPointerException) but if you click on the other exception through the bottom left panel in your screenshot, you should be able to get the stacktrace for the underlying error :D

**Comment by kaixiangtay** [comment]
Thanks will look into it
