### ISSUE TITLE
After submitting the review for someone's pull request, is it still possible to add a description for the review?

### ISSUE THREAD

**Issue by clarlzx** [nus-cs2103-AY2021S2/forum#96]
Hi, I had forgotten to add the description before clicking on submit. Is it possible and how should I go about adding this description if I have already submitted my review? Thank you, any help is appreciated 😄.

![image](https://user-images.githubusercontent.com/66005036/106503521-b53cd400-6500-11eb-9951-cf88b778b76b.png)

**Comment by pyuxiang** [comment]
You can continue the conversation thread by going back to the pull request and throwing in a follow up comment in the thread. Alternatively, you might be able to edit your pull request comment on the same page, and selecting `Edit`; see below. 

![20210202_030434](https://user-images.githubusercontent.com/28663438/106505579-7b210180-6503-11eb-9d6b-345010c28600.png)

**Comment by clarlzx** [comment]
I am unable to see the main comment because I did not submit one before submitting the review, so I think I am unable to add the top/main comment. Thanks for the help though, I will try to add an extra trailing comment at the end 😄.
