### ISSUE TITLE
How does IntelliJ initialize Gradle upon start up?

### ISSUE THREAD

**Issue by pyuxiang** [nus-cs2103-AY2021S2/forum#97]
Some observations I gathered while doing the Week 4 tasks:

1. Setup instructions for Gradle requires deleting `.idea` folder and reopening the project (or invalidating caches as suggested by [SO](https://stackoverflow.com/questions/5905896/intellij-inspection-gives-cannot-resolve-symbol-but-still-compiles-code))
1. Project opening time is noticeably longer after Gradle is integrated, with the pop-up mentioning something about indexing project files
1. JavaFX libraries are automatically installed upon [addition of dependencies](https://se-education.org/guides/tutorials/javaFxPart1.html) into `build.gradle` and restart of IntelliJ IDE

My guess is IntelliJ somehow caches project information inside the `.idea` folder, which includes commands to load Gradle and its configuration files upon opening the project. Could someone perhaps point me to resources to find out more? 😃 

The fact that the IDE automatically does dependency checking and library installation without the user initiating these operations sounds a little intrusive 😢 Or maybe I'm too used to a simple text editor environment.

**Comment by damithc** [comment]
Gradle is also a dependency management tool. When Intellij sees your project contains gradle files, it probably assumes you intend to use Gradle for dependency management and start doing that automatically.
I remember Intellij having a setting to indicate if you want it to use Gradle for building and testing. Not sure if it is still there though.

**Comment by w2vgd** [comment]
Yes prof @damithc. We can still configure IntelliJ to build/run using Gradle or IntelliJ itself 😄 

![image](https://user-images.githubusercontent.com/65358857/106708796-6db46600-662e-11eb-8805-095fd3e0013d.png)

**Comment by pyuxiang** [comment]
Great tip, thanks!
