### ISSUE TITLE
Clarification of a few coding standards

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#98]
Hi, I have a few queries about the coding standards/discrepancies with checkstyle that I will like to clarify.

1. Checkstyle complaining about empty line separating 3rd kind of imports (special imports). I realized that javafx imports are considered under special imports instead of third-party imports too.  Do we have to strictly follow the checkstyle rules?
![image](https://user-images.githubusercontent.com/65358857/106503692-f03f0780-6500-11eb-8ca7-94e2a6841dd1.png)

2. Should we make all instance variables that will not be modified `final`? An example is shown below in which these instance attributes are not modified after the constructor. If they are indeed supposed to be marked as `final`, then they are supposed to be capitalized too right?
![image](https://user-images.githubusercontent.com/65358857/106504437-e36ee380-6501-11eb-8b08-7ed03c336e42.png)

Extra: Just want to confirm that we should include a fullstop after each description of a parameter in the javadoc comments too? (The module coding standards did explicitly say we should but just wondering why the official Java API actually has both kinds of documentation. The `StringBuilder` class API uses a fullstop but the `Scanner` class API does not)

**Comment by damithc** [comment]
Thanks for raising these @w2vgd 
1. In general, when there is a discrepancy between the coding standard and the checkstyle file, it is ideal that you update the checkstyle file to match the coding standard. But in terms of grading, we will not fault you for using the given checkstyle file _as is_. That is, when the two differs, we'll accept both versions of the code styles. But if the coding standard has a rule that is not checked by checkstyle, you are still expected to follow it in the code.
2. Apply SCREAMING_SNAKE to ~~`final static` variables, both `private` and `public`. But not for instance level `final` variables (i.e., without `static`).~~ all `final` variables.
3.  In this case, follow the coding standard. Yes it it true that JDK code itself is not entirely consistent in style. I guess given the size of the code base, how old it is, and how it changed companies, we can't expect it to be perfect. Some of that code even could have been absorbed from external OSS projects.

**Comment by tjtanjin** [comment]
Hi prof @damithc, I would like to make a clarification for point 2.

Is the capitalisation for instance level final variables strictly not allowed? The example provided in coding standard for a non-static `final` variable is as below:
<img width="995" alt="Screenshot 2021-02-02 at 1 25 34 PM" src="https://user-images.githubusercontent.com/43908963/106557146-278ed200-655c-11eb-89d2-0d4fef45b567.png">
Thank you in advance!

**Comment by damithc** [comment]
> Hi prof @damithc, I would like to make a clarification for point 2.
> 
> Is the capitalisation for instance level final variables strictly not allowed? The example provided in coding standard for a non-static `final` variable is as below:
> <img alt="Screenshot 2021-02-02 at 1 25 34 PM" width="995" src="https://user-images.githubusercontent.com/43908963/106557146-278ed200-655c-11eb-89d2-0d4fef45b567.png">
> Thank you in advance!

Good point @w2vgd . Edited my previous comment accordingly as the coding standard seems to suggest that it applies to all `final` variables.

**Comment by w2vgd** [comment]
Thanks for the clarification prof. Shall leave this thread open a bit longer before closing.

**Comment by damithc** [comment]
> Thanks for the clarification prof. Shall leave this thread open a bit longer before closing.

Let's close as per our usual practice. Anybody interested can still find it among closed issues.

**Comment by w2vgd** [comment]
Yepp sure

**Comment by w2vgd** [comment]
Hi Prof @damithc,

Is this the preferred way to write the constructor because of the capitalized final instance attributes and camelCase parameter names? Thanks.
![image](https://user-images.githubusercontent.com/65358857/106624854-0dcbaa00-65b1-11eb-9c40-f9f53dcf237b.png)

**Comment by damithc** [comment]
> Hi Prof @damithc,
> 
> Is this the preferred way to write the constructor because of the capitalized final instance attributes and camelCase parameter names? Thanks.
> ![image](https://user-images.githubusercontent.com/65358857/106624854-0dcbaa00-65b1-11eb-9c40-f9f53dcf237b.png)

Yes @w2vgd , looks fine to me.
