### ISSUE TITLE
Unable to import JUnit with Gradle

### ISSUE THREAD

**Issue by skinnychenpi** [nus-cs2103-AY2021S2/forum#99]
Hello guys, I find out that when I use gradle, the test classes that I created last week will not compile since IntelliJ can't find the package that I want to import even with I download those libraries with gradle. Any solutions?

![Screen Shot 2021-02-02 at 16 50 28](https://user-images.githubusercontent.com/35286219/106576219-dee51200-6577-11eb-8343-fbc918bcbb0f.png)
![Screen Shot 2021-02-02 at 16 51 29](https://user-images.githubusercontent.com/35286219/106576259-e5738980-6577-11eb-97a7-72ff8f989c25.png)

**Comment by tjtanjin** [comment]
I think you are using a third-party test plugin because my dependencies section back while adding JUnit looked only like this:
```
dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'
}
```
On a side note, have you tried reloading/reopening the project?

**Comment by skinnychenpi** [comment]
> I think you are using a third-party test plugin because my dependencies section back while adding JUnit looked only like this:
> 
> ```
> dependencies {
>     testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
>     testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'
> }
> ```
> 
> On a side note, have you tried reloading/reopening the project?

Thanks for the reply, I've modified my dependencies just like you suggested. However, the compile error still exist:`error: package org.junit.jupiter.api does not exist
import org.junit.jupiter.api.Test;`
